// GENERATED by projen watch - DO NOT EDIT.
// Regenerated from the exporting modules in ./src.
// Hand edits are overwritten on the next watch; this file is read-only.

export * as config from "./src/config";
export * as emailHtml from "./src/email-html";
export * as markdown from "./src/markdown";
export * as outbox from "./src/outbox";
export * as plugin from "./src/plugin";
export * as sender from "./src/sender";
export * as tool from "./src/tool";
export * as transport from "./src/transport";
export type { SmtpConfig, EmailPluginConfig, ResolvedSmtpConfig, ResolvedFileConfig, ResolvedEmailConfig } from "./src/config";
export type { EmailHtmlOptions } from "./src/email-html";
export type { EmailToolOptions } from "./src/tool";
export type { EmailRuntime } from "./src/transport";
