[package]
name = "dbx-tools-u2m-bindings"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "UniFFI language bindings for dbx-tools-u2m"
license.workspace = true
repository.workspace = true

[lib]
name = "dbx_tools_u2m_bindings"
crate-type = ["lib", "cdylib"]

[[bin]]
name = "uniffi-bindgen"
path = "uniffi-bindgen.rs"

[features]
default = ["keyring"]
keyring = ["dbx-tools-u2m/keyring"]
postgres = ["dep:dbx-tools-u2m-postgres"]

[dependencies]
dbx-tools-u2m = { path = "../dbx-tools-u2m", default-features = false }
dbx-tools-u2m-postgres = { path = "../dbx-tools-u2m-postgres", optional = true }
thiserror.workspace = true
time.workspace = true
uniffi.workspace = true

[dev-dependencies]
tokio.workspace = true
