// GENERATED by projen watch - DO NOT EDIT.
// Regenerated from the exporting modules in ./src.
// Hand edits are overwritten on the next watch; this file is read-only.

export const PACKAGE_IDENTIFIER = "@dbx-tools/demo-appkit-app";
export const PACKAGE_VERSION = "0.9.25";
export * as app from "./src/App.tsx";
export * as errorBoundary from "./src/ErrorBoundary.tsx";
export * as pagesBrand from "./src/pages/Brand.tsx";
export * as pagesBus from "./src/pages/Bus.tsx";
export * as pagesCards from "./src/pages/Cards.tsx";
export * as pagesChat from "./src/pages/Chat.tsx";
export * as pagesSearch from "./src/pages/Search.tsx";
export { ErrorBoundary } from "./src/ErrorBoundary.tsx";
