/**
 * Two barrel-generator behaviors that a concurrent `sync --watch` broke, both of
 * which are timing-dependent enough to look fine in isolation:
 *
 * - An UNCHANGED barrel must not be touched at all. The generator used to clear the
 *   read-only bit before parsing and restore it after, so every no-op cycle - which
 *   is nearly all of them - left a window where a sibling writer (the projenrc
 *   watcher's post-synth sweep, or a second `sync --watch`) found the file locked
 *   mid-write and failed with `EACCES: permission denied, open '<pkg>/index.ts'`.
 * - One failing package must not abandon the others. `generateBarrels` used to let
 *   the first error propagate, so every package after it in iteration order was
 *   silently skipped with nothing in the log naming them.
 * - A hand-written module must keep ownership of a name its own GENERATED sibling
 *   also declares. Once `shared-genie` held codegen'd `dashboards.ts` next to
 *   curated `genie-model.ts`, the two were treated as an ordinary ambiguous
 *   collision, so `GenieMessage` / `GenieSpace` / `MessageStatus` silently vanished
 *   from the barrel and every consumer importing them by name stopped compiling.
 */
import assert from "node:assert/strict";
import { mkdirSync, mkdtempSync, readFileSync, rmSync, statSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, it } from "node:test";
import { generateBarrels } from "../src/barrels.ts";

/**
 * Scaffold `<tmp>/<name>/src/<module>.ts` exporting one const, and return the package
 * dir. The export is deliberately NOT named after its module: a name matching the
 * generated `export * as <ns>` namespace is blocked from flat hoisting, so reusing the
 * module name would hide whether hoisting ran at all.
 */
function fixturePackage(name: string, module = "graph"): string {
  const dir = join(mkdtempSync(join(tmpdir(), "barrels-")), name);
  mkdirSync(join(dir, "src"), { recursive: true });
  writeFileSync(
    join(dir, "package.json"),
    `${JSON.stringify({ name: `@test/${name}` }, null, 2)}\n`,
  );
  writeFileSync(join(dir, "src", `${module}.ts`), `export const ${module}Value = "x";\n`);
  return dir;
}

/** `[mode, mtimeMs]` for the package's generated barrel. */
function barrelStat(dir: string): [number, number] {
  const s = statSync(join(dir, "index.ts"));
  return [s.mode & 0o777, s.mtimeMs];
}

describe("generateBarrels", () => {
  it("writes a read-only barrel for a package it has not seen before", () => {
    const dir = fixturePackage("fresh");
    assert.equal(generateBarrels({ dirs: [dir] }), 1);

    const barrel = readFileSync(join(dir, "index.ts"), "utf8");
    assert.match(barrel, /^\/\/ GENERATED by projen watch - DO NOT EDIT\./);
    assert.match(barrel, /export const PACKAGE_IDENTIFIER = "@test\/fresh";/);
    assert.match(barrel, /export \* as graph from "\.\/src\/graph\.ts";/);
    // The package-unique name is hoisted flat alongside the namespace line.
    assert.match(barrel, /export \{ graphValue \} from "\.\/src\/graph\.ts";/);
    assert.equal(barrelStat(dir)[0], 0o444);
  });

  it("reserves PACKAGE_IDENTIFIER for generated package identity", () => {
    const dir = fixturePackage("identity");
    writeFileSync(
      join(dir, "src", "identity.ts"),
      'export const PACKAGE_IDENTIFIER = "not-the-package";\n',
    );

    generateBarrels({ dirs: [dir] });
    const barrel = readFileSync(join(dir, "index.ts"), "utf8");

    assert.match(barrel, /export const PACKAGE_IDENTIFIER = "@test\/identity";/);
    assert.equal(barrel.match(/\bPACKAGE_IDENTIFIER\b/g)?.length, 1);
  });

  it("leaves an unchanged barrel byte-for-byte AND mode-for-mode alone", () => {
    const dir = fixturePackage("noop");
    assert.equal(generateBarrels({ dirs: [dir] }), 1);
    const [mode, mtime] = barrelStat(dir);
    // A structural no-op must return before package identity needs a manifest read.
    rmSync(join(dir, "package.json"));

    // Second pass over an unchanged export surface: no rewrite, and - the part that
    // regressed - no transient unlock either.
    assert.equal(generateBarrels({ dirs: [dir] }), 0);
    assert.deepEqual(barrelStat(dir), [mode, mtime]);
    assert.equal(mode, 0o444);
  });

  it("rewrites a read-only barrel when a module is added, and re-locks it", () => {
    const dir = fixturePackage("grow");
    generateBarrels({ dirs: [dir] });
    assert.equal(barrelStat(dir)[0], 0o444);
    writeFileSync(join(dir, "src", "edge.ts"), 'export const edgeValue = "y";\n');

    // Proves the unlock-then-write path still works against an already-locked file.
    assert.equal(generateBarrels({ dirs: [dir] }), 1);
    assert.match(readFileSync(join(dir, "index.ts"), "utf8"), /export \* as edge from/);
    assert.equal(barrelStat(dir)[0], 0o444);
  });

  it("drops a stale barrel once a package has no exporting modules left", () => {
    const dir = fixturePackage("emptied");
    generateBarrels({ dirs: [dir] });
    // Not an export, so the module stops being barrel-eligible.
    writeFileSync(join(dir, "src", "graph.ts"), 'const graphValue = "x";\n');

    assert.equal(generateBarrels({ dirs: [dir] }), 0);
    assert.throws(() => statSync(join(dir, "index.ts")), { code: "ENOENT" });
  });

  it("attempts every package and reports the failures together", () => {
    // A directory where the barrel should go makes only THIS package's write fail,
    // leaving the others perfectly writable.
    const broken = fixturePackage("broken");
    mkdirSync(join(broken, "index.ts"), { recursive: true });
    const healthy = [fixturePackage("after-one"), fixturePackage("after-two")];

    assert.throws(
      () => generateBarrels({ dirs: [broken, ...healthy] }),
      (err: unknown) => {
        assert.ok(err instanceof AggregateError);
        assert.match(err.message, /1 barrel failed:/);
        assert.match(err.message, /broken/);
        return true;
      },
    );

    // The whole point: the packages ordered after the failure still got barrels.
    for (const dir of healthy) {
      assert.match(readFileSync(join(dir, "index.ts"), "utf8"), /export \* as graph from/);
    }
  });
  it("lets a hand-written module own a name its generated sibling also declares", () => {
    const dir = fixturePackage("curated");
    // The codegen'd module, carrying the do-not-edit banner the generator stamps.
    writeFileSync(
      join(dir, "src", "wire.ts"),
      "// GENERATED by projen synth (codegen: ts-to-zod) - DO NOT EDIT.\n" +
        "export type Message = { id: string };\n",
    );
    // The curated view: extends and re-exports the generated shape under the SAME name.
    writeFileSync(
      join(dir, "src", "model.ts"),
      'import type { Message as Wire } from "./wire.ts";\n' +
        "export type Message = Wire & { extra: string };\n",
    );

    generateBarrels({ dirs: [dir] });
    const barrel = readFileSync(join(dir, "index.ts"), "utf8");

    // Hoisted from the HAND-WRITTEN module, and never from the generated one.
    assert.match(barrel, /export type \{[^}]*\bMessage\b[^}]*\} from "\.\/src\/model\.ts";/);
    assert.doesNotMatch(barrel, /export type \{[^}]*\bMessage\b[^}]*\} from "\.\/src\/wire\.ts";/);
  });

  it("still treats two hand-written modules claiming one name as ambiguous", () => {
    const dir = fixturePackage("ambiguous");
    writeFileSync(join(dir, "src", "left.ts"), "export type Shared = string;\n");
    writeFileSync(join(dir, "src", "right.ts"), "export type Shared = number;\n");

    generateBarrels({ dirs: [dir] });
    const barrel = readFileSync(join(dir, "index.ts"), "utf8");

    // Namespace-only: hoisting either would emit two conflicting re-exports.
    assert.doesNotMatch(barrel, /\bShared\b/);
    assert.match(barrel, /export \* as left from/);
    assert.match(barrel, /export \* as right from/);
  });
});
