/**
 * Two barrel-generator behaviors that a concurrent `sync --watch` broke, both of
 * which are timing-dependent enough to look fine in isolation:
 *
 * - An UNCHANGED barrel must not be touched at all. The generator used to clear the
 *   read-only bit before parsing and restore it after, so every no-op cycle - which
 *   is nearly all of them - left a window where a sibling writer (the projenrc
 *   watcher's post-synth sweep, or a second `sync --watch`) found the file locked
 *   mid-write and failed with `EACCES: permission denied, open '<pkg>/index.ts'`.
 * - One failing package must not abandon the others. `generateBarrels` used to let
 *   the first error propagate, so every package after it in iteration order was
 *   silently skipped with nothing in the log naming them.
 */
import assert from "node:assert/strict";
import { mkdirSync, mkdtempSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, it } from "node:test";
import { generateBarrels } from "../src/barrels.ts";

/**
 * Scaffold `<tmp>/<name>/src/<module>.ts` exporting one const, and return the package
 * dir. The export is deliberately NOT named after its module: a name matching the
 * generated `export * as <ns>` namespace is blocked from flat hoisting, so reusing the
 * module name would hide whether hoisting ran at all.
 */
function fixturePackage(name: string, module = "graph"): string {
  const dir = join(mkdtempSync(join(tmpdir(), "barrels-")), name);
  mkdirSync(join(dir, "src"), { recursive: true });
  writeFileSync(join(dir, "src", `${module}.ts`), `export const ${module}Value = "x";\n`);
  return dir;
}

/** `[mode, mtimeMs]` for the package's generated barrel. */
function barrelStat(dir: string): [number, number] {
  const s = statSync(join(dir, "index.ts"));
  return [s.mode & 0o777, s.mtimeMs];
}

describe("generateBarrels", () => {
  it("writes a read-only barrel for a package it has not seen before", () => {
    const dir = fixturePackage("fresh");
    assert.equal(generateBarrels({ dirs: [dir] }), 1);

    const barrel = readFileSync(join(dir, "index.ts"), "utf8");
    assert.match(barrel, /^\/\/ GENERATED by projen watch - DO NOT EDIT\./);
    assert.match(barrel, /export \* as graph from "\.\/src\/graph\.ts";/);
    // The package-unique name is hoisted flat alongside the namespace line.
    assert.match(barrel, /export \{ graphValue \} from "\.\/src\/graph\.ts";/);
    assert.equal(barrelStat(dir)[0], 0o444);
  });

  it("leaves an unchanged barrel byte-for-byte AND mode-for-mode alone", () => {
    const dir = fixturePackage("noop");
    assert.equal(generateBarrels({ dirs: [dir] }), 1);
    const [mode, mtime] = barrelStat(dir);

    // Second pass over an unchanged export surface: no rewrite, and - the part that
    // regressed - no transient unlock either.
    assert.equal(generateBarrels({ dirs: [dir] }), 0);
    assert.deepEqual(barrelStat(dir), [mode, mtime]);
    assert.equal(mode, 0o444);
  });

  it("rewrites a read-only barrel when a module is added, and re-locks it", () => {
    const dir = fixturePackage("grow");
    generateBarrels({ dirs: [dir] });
    assert.equal(barrelStat(dir)[0], 0o444);
    writeFileSync(join(dir, "src", "edge.ts"), 'export const edgeValue = "y";\n');

    // Proves the unlock-then-write path still works against an already-locked file.
    assert.equal(generateBarrels({ dirs: [dir] }), 1);
    assert.match(readFileSync(join(dir, "index.ts"), "utf8"), /export \* as edge from/);
    assert.equal(barrelStat(dir)[0], 0o444);
  });

  it("drops a stale barrel once a package has no exporting modules left", () => {
    const dir = fixturePackage("emptied");
    generateBarrels({ dirs: [dir] });
    // Not an export, so the module stops being barrel-eligible.
    writeFileSync(join(dir, "src", "graph.ts"), 'const graphValue = "x";\n');

    assert.equal(generateBarrels({ dirs: [dir] }), 0);
    assert.throws(() => statSync(join(dir, "index.ts")), { code: "ENOENT" });
  });

  it("attempts every package and reports the failures together", () => {
    // A directory where the barrel should go makes only THIS package's write fail,
    // leaving the others perfectly writable.
    const broken = fixturePackage("broken");
    mkdirSync(join(broken, "index.ts"), { recursive: true });
    const healthy = [fixturePackage("after-one"), fixturePackage("after-two")];

    assert.throws(
      () => generateBarrels({ dirs: [broken, ...healthy] }),
      (err: unknown) => {
        assert.ok(err instanceof AggregateError);
        assert.match(err.message, /1 barrel failed:/);
        assert.match(err.message, /broken/);
        return true;
      },
    );

    // The whole point: the packages ordered after the failure still got barrels.
    for (const dir of healthy) {
      assert.match(readFileSync(join(dir, "index.ts"), "utf8"), /export \* as graph from/);
    }
  });
});
