/**
 * `pnpm-workspace.yaml` is written by projen's NATIVE
 * `javascript.PnpmWorkspaceYaml`; the engine only supplies the options it
 * renders. Two things that arrangement has to keep working, both of which broke
 * once already:
 *
 * - Build allowances stay the `allowBuilds` MAP. The pnpm this repo installs
 *   with reads that key and does not know `onlyBuiltDependencies` at all, so
 *   projen's own `allowScripts` (which renders the list) would leave every build
 *   script skipped.
 * - Late mutation still lands in the file. `NodePackage` SPREADS
 *   `workspaceYamlOptions` inside its own constructor, so the engine's state must
 *   be reached through stable mutable references - a getter would fire before the
 *   root has scanned anything, and members/catalog pins are added after
 *   construction.
 */
import assert from "node:assert/strict";
import { existsSync, mkdtempSync, readFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { before, describe, it } from "node:test";
import { DBXToolsNodeProject, DBXToolsTypeScriptProject } from "../src/project";

let outdir: string;
let yaml: string;

before(() => {
  process.env.PROJEN_DISABLE_POST = "1"; // no install/barrels during synth
  outdir = mkdtempSync(join(tmpdir(), "pnpm-workspace-"));

  const root = new DBXToolsNodeProject({
    name: "pnpm-workspace-fixture",
    outdir,
    defaultTagMixins: false,
    allowBuilds: { protobufjs: true },
    workspaceYaml: { overrides: { glob: "^13.0.0" } },
  });
  new DBXToolsTypeScriptProject({
    parent: root,
    outdir: "packages/member",
    name: "@fixture/member",
  });
  // Added AFTER construction, the way a tag mixin or a consumer's .projenrc.ts
  // does: it must still reach the rendered file.
  root.pnpmWorkspace?.addCatalog("react", "^19.9.9");
  root.pnpmWorkspace?.addCatalog("@scoped/name", "^2.0.0");
  root.pnpmWorkspace?.addCatalog("socket.io", "^4.8.1");
  root.pnpmWorkspace?.allowBuild("esbuild");
  root.synth();

  yaml = readFileSync(join(outdir, "pnpm-workspace.yaml"), "utf8");
});

describe("pnpm-workspace.yaml", () => {
  it("is written by projen, not a second engine-owned file", () => {
    assert.ok(existsSync(join(outdir, "pnpm-workspace.yaml")));
    // The engine used to write this file itself during preSynthesize; only
    // projen's own component should be producing it now.
    assert.match(yaml, /Generated by projen/i);
  });

  it("lists the discovered subproject as a member", () => {
    assert.match(yaml, /^ {2}- packages\/member$/m);
  });

  it("carries catalog pins added after construction", () => {
    assert.match(yaml, /^ {2}react: \^19\.9\.9$/m);
    assert.match(yaml, /^ {2}"@scoped\/name": \^2\.0\.0$/m);
  });

  it("keeps a DOTTED package name one catalog key", () => {
    // Guards the reason pins are set as plain object keys rather than through
    // projen's `file.addOverride("catalog.<name>", ...)`, which SPLITS its path
    // on `.`: that route renders `socket.io` as `socket: { io: ... }`, a catalog
    // entry no `catalog:` specifier can resolve, with no error.
    assert.match(yaml, /^ {2}socket\.io: \^4\.8\.1$/m);
    assert.doesNotMatch(yaml, /^ {2}socket:$/m);
  });

  it("renders build allowances as the allowBuilds map pnpm reads", () => {
    assert.match(yaml, /^allowBuilds:$/m);
    assert.match(yaml, /^ {2}esbuild: true$/m);
    assert.match(yaml, /^ {2}protobufjs: true$/m);
  });

  it("never emits the build lists this pnpm ignores", () => {
    // pnpm reads neither; a tree that lists them installs with every build
    // script silently skipped.
    assert.doesNotMatch(yaml, /onlyBuiltDependencies/);
    assert.doesNotMatch(yaml, /ignoredBuiltDependencies/);
  });

  it("passes any other pnpm setting through projen's typed schema", () => {
    assert.match(yaml, /^overrides:$/m);
    assert.match(yaml, /^ {2}glob: \^13\.0\.0$/m);
  });

  it("is emitted for the ROOT only, never a member package", () => {
    // projen's NodePackage attaches a PnpmWorkspaceYaml to EVERY pnpm project. A
    // nested one would make that member look like its own workspace root; it
    // stays off disk only because nothing feeds a member's schema (`omitEmpty`).
    assert.ok(!existsSync(join(outdir, "packages/member/pnpm-workspace.yaml")));
  });

  it("keeps the settings a projen-managed monorepo wants", () => {
    // The catalog is generated, so `pnpm add` must not write into it.
    assert.match(yaml, /^catalogMode: manual$/m);
    // Packages resolve siblings from source, so a stale node_modules should warn.
    assert.match(yaml, /^verifyDepsBeforeRun: warn$/m);
    // An unreviewed build script must NOT fail the install: leaving this off is
    // what lets `allowBuilds` hold allowances only, with no declined entries.
    assert.doesNotMatch(yaml, /strictDepBuilds/);
  });
});
