import assert from "node:assert/strict";
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, describe, it } from "node:test";
import { pathToFileURL } from "node:url";

import { Project } from "projen";

import { PythonNodeBundle } from "../src/python-node-bundle.ts";

const temporaryDirectories: string[] = [];

afterEach(() => {
  for (const directory of temporaryDirectories.splice(0)) {
    rmSync(directory, { recursive: true, force: true });
  }
});

describe("PythonNodeBundle", () => {
  it("generates paired tasks with repeatable function overrides", () => {
    const project = new Project({ name: "fixture" });
    const bundle = new PythonNodeBundle(project, {
      name: "auth",
      entry: "src/index.ts",
      output: "python/_runtime.js",
      source: "fixture runtime",
      shimRoot: "shims",
      functionOverrides: [
        {
          module: "@fixture/core/file-lock",
          export: "acquireFileLock",
          handler: "shims/file-lock.ts",
        },
        {
          module: "@fixture/core/process",
          export: "run",
          handler: "shims/process.ts",
          handlerExport: "runProcess",
        },
      ],
    });

    assert.equal(
      bundle.buildTask.steps[0]?.exec,
      [
        "bun projen/tasks/python-node-bindings.ts",
        "--entry src/index.ts",
        "--output python/_runtime.js",
        "--shim-root shims",
        "--source 'fixture runtime'",
        "--function-override @fixture/core/file-lock#acquireFileLock=shims/file-lock.ts#acquireFileLock",
        "--function-override @fixture/core/process#run=shims/process.ts#runProcess",
      ].join(" "),
    );
    assert.equal(bundle.checkTask.steps[0]?.exec, `${bundle.buildTask.steps[0]?.exec} --check`);
    assert.ok(project.testTask.steps.some((step) => step.spawn === bundle.checkTask.name));
  });

  it("replaces only the selected export in a real bundle", async () => {
    const directory = temporaryDirectory();
    const targetDirectory = join(directory, "node_modules/fixture-target");
    mkdirSync(targetDirectory, { recursive: true });
    writeFileSync(
      join(targetDirectory, "package.json"),
      JSON.stringify({ name: "fixture-target", type: "module", exports: "./index.ts" }),
    );
    writeFileSync(
      join(targetDirectory, "index.ts"),
      [
        'export const preserved = "original";',
        'export function replaced(): string { return "original"; }',
      ].join("\n"),
    );
    writeFileSync(
      join(directory, "handler.ts"),
      'export function replacement(): string { return "override"; }\n',
    );
    writeFileSync(
      join(directory, "entry.ts"),
      'export { preserved, replaced } from "fixture-target";\n',
    );
    const output = join(directory, "runtime.js");
    const task = join(import.meta.dirname, "../tasks/python-node-bindings.ts");
    const result = Bun.spawnSync(
      [
        "bun",
        task,
        "--root",
        directory,
        "--entry",
        "entry.ts",
        "--output",
        "runtime.js",
        "--source",
        "fixture",
        "--function-override",
        "fixture-target#replaced=handler.ts#replacement",
      ],
      {
        stderr: "pipe",
        stdout: "pipe",
      },
    );
    assert.equal(result.exitCode, 0, result.stderr.toString());
    const runtime = (await import(pathToFileURL(output).href)) as {
      preserved: string;
      replaced(): string;
    };
    assert.equal(runtime.preserved, "original");
    assert.equal(runtime.replaced(), "override");
    assert.match(readFileSync(output, "utf8"), /GENERATED by/);
  });

  it("rejects malformed and duplicate overrides", () => {
    const directory = temporaryDirectory();
    writeFileSync(join(directory, "entry.ts"), "export {};\n");
    writeFileSync(join(directory, "handler.ts"), "export const value = 1;\n");
    const task = join(import.meta.dirname, "../tasks/python-node-bindings.ts");
    const common = [
      "bun",
      task,
      "--root",
      directory,
      "--entry",
      "entry.ts",
      "--output",
      "runtime.js",
      "--source",
      "fixture",
    ];
    const malformed = Bun.spawnSync([...common, "--function-override", "invalid"], {
      stderr: "pipe",
    });
    assert.notEqual(malformed.exitCode, 0);
    assert.match(malformed.stderr.toString(), /expected <module>#<export>=<file>#<export>/);

    const value = "fixture-target#value=handler.ts#value";
    const duplicate = Bun.spawnSync(
      [...common, "--function-override", value, "--function-override", value],
      {
        stderr: "pipe",
      },
    );
    assert.notEqual(duplicate.exitCode, 0);
    assert.match(duplicate.stderr.toString(), /Duplicate function override/);
  });
});

function temporaryDirectory(): string {
  const directory = mkdtempSync(join(tmpdir(), "python-node-bundle-"));
  temporaryDirectories.push(directory);
  return directory;
}
