// GENERATED by projen watch - DO NOT EDIT.
// Regenerated from the exporting modules in ./src.
// Hand edits are overwritten on the next watch; this file is read-only.

export const PACKAGE_IDENTIFIER = "@dbx-tools/cli-service";
export const PACKAGE_VERSION = "0.9.43";
export * as cli from "./src/cli.ts";
export * as definition from "./src/definition.ts";
export * as icon from "./src/icon.ts";
export * as service from "./src/service.ts";
export { CliServiceInstallOptionsSchema } from "./src/cli.ts";
export type { CliServiceDefinitionSource, CliServiceCliDependencies } from "./src/cli.ts";
export { CliServiceCommandSchema, CliServiceMenuItemSchema, CliServiceDefinitionSchema } from "./src/definition.ts";
export type { CliServiceCommand, CliServiceCommandInput, CliServiceMenuItem, CliServiceDefinition, CliServiceDefinitionOptions } from "./src/definition.ts";
export { CliService } from "./src/service.ts";
export type { CliServiceCompiler, CliServiceRuntimeInstaller, CliServiceRuntimeOptions, CliServiceStatus, CliServiceLifecycle } from "./src/service.ts";
