#!/usr/bin/env -S bun
import {
  cpSync,
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  readdirSync,
  renameSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { basename, dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { parseArgs } from "node:util";
import { spawnSync } from "node:child_process";
import { makeReadonly, makeWritable, stampGenerated } from "../src/generated.ts";
import {
  addExplicitInterfaceReexports,
  makeDefaultedInterfaceParametersOptional,
} from "../src/uniffi.ts";

const { values } = parseArgs({
  options: {
    crate: { type: "string" },
    node: { type: "string" },
    python: { type: "string" },
    "cargo-target": { type: "string" },
    "node-package-base": { type: "string" },
  },
});
if (!values.crate || (!values.node && !values.python)) {
  throw new Error("Expected --crate and at least one of --node or --python");
}

const root = resolve(dirname(fileURLToPath(import.meta.url)), "../..");
const crate = values.crate;
const libraryName = crate.replaceAll("-", "_");
const extension =
  process.platform === "darwin" ? "dylib" : process.platform === "win32" ? "dll" : "so";
const prefix = process.platform === "win32" ? "" : "lib";
const targetDirectory = values["cargo-target"]
  ? join(root, "target", values["cargo-target"], "release")
  : join(root, "target", "release");
const library = join(targetDirectory, `${prefix}${libraryName}.${extension}`);
const normalizedOutput = (value: string): string =>
  value
    .replace(/[\p{Extended_Pictographic}\uFE0F]/gu, "")
    .replace(/[ \t]+$/gm, "")
    .trim();
const run = (command: string, args: string[]) => {
  const result = spawnSync(command, args, { cwd: root, encoding: "utf8" });
  const stdout = normalizedOutput(result.stdout ?? "");
  const stderr = normalizedOutput(result.stderr ?? "");
  if (stdout) process.stdout.write(`${stdout}\n`);
  if (stderr) process.stderr.write(`${stderr}\n`);
  if (result.status !== 0) throw new Error(`${command} exited with ${result.status}`);
};

const replaceGenerated = (source: string, destination: string): void => {
  const deadline = Date.now() + 5_000;
  while (!existsSync(source) && Date.now() < deadline) Bun.sleepSync(25);
  if (!existsSync(source)) throw new Error(`Missing generated binding: ${source}`);
  mkdirSync(dirname(destination), { recursive: true });
  makeWritable(destination);
  rmSync(destination, { force: true });
  renameSync(source, destination);
};

const stampGeneratedPython = (file: string): void => {
  makeWritable(file);
  const body = readFileSync(file, "utf8");
  writeFileSync(
    file,
    [
      "# GENERATED by UniFFI binding generation - DO NOT EDIT.",
      `# Regenerated from the ${crate} Rust exports.`,
      "# Hand edits are overwritten on the next watch; this file is read-only.",
      "",
      body,
    ].join("\n"),
  );
  makeReadonly(file);
};

run("cargo", [
  "build",
  "--release",
  "--package",
  crate,
  ...(values["cargo-target"] ? ["--target", values["cargo-target"]] : []),
]);
if (!existsSync(library)) throw new Error(`Missing compiled UniFFI library: ${library}`);

if (values.node) {
  const nodeSource = resolve(root, values.node, "src");
  const nodeOutput = mkdtempSync(join(tmpdir(), `${libraryName}-node-`));
  run(join(root, "node_modules/.bin/ubrn"), [
    "generate",
    "napi",
    "bindings",
    "--library",
    "--ts-dir",
    nodeOutput,
    ...(values["node-package-base"]
      ? ["--lib-package-base", values["node-package-base"], "--lib-node-triple"]
      : ["--lib-colocated"]),
    library,
  ]);
  const generatedModules = readdirSync(nodeOutput).filter(
    (file) => file.endsWith(".ts") && file !== "index.ts",
  );
  const linkedComponents = generatedModules.length > 2;
  const nodeBindings = join(nodeSource, "bindings.ts");
  const linkedNames = new Map(generatedModules.map((file) => [file, `_bindings-${file}`]));
  const generatedFiles = linkedComponents
    ? generatedModules.map((file) => join(nodeSource, linkedNames.get(file)!))
    : [join(nodeSource, "_bindings.ts"), join(nodeSource, "_bindings-ffi.ts")];
  replaceGenerated(join(nodeOutput, "index.ts"), nodeBindings);
  if (linkedComponents) {
    for (const file of generatedModules) {
      replaceGenerated(join(nodeOutput, file), join(nodeSource, linkedNames.get(file)!));
    }
  } else {
    replaceGenerated(join(nodeOutput, `${libraryName}.ts`), generatedFiles[0]);
    replaceGenerated(join(nodeOutput, `${libraryName}-ffi.ts`), generatedFiles[1]);
    writeFileSync(
      nodeBindings,
      readFileSync(nodeBindings, "utf8").replaceAll(`./${libraryName}`, "./_bindings"),
    );
    writeFileSync(
      generatedFiles[0],
      readFileSync(generatedFiles[0], "utf8").replaceAll(`./${libraryName}-ffi`, "./_bindings-ffi"),
    );
  }
  if (linkedComponents) {
    for (const file of [nodeBindings, ...generatedFiles]) {
      let source = readFileSync(file, "utf8");
      for (const [generated, destination] of linkedNames) {
        const from = generated.slice(0, -3);
        const to = destination.slice(0, -3);
        source = source
          .replaceAll(`'./${from}'`, `'./${to}'`)
          .replaceAll(`"./${from}"`, `"./${to}"`);
      }
      writeFileSync(file, source);
    }
  }
  for (const file of generatedFiles) {
    writeFileSync(file, makeDefaultedInterfaceParametersOptional(readFileSync(file, "utf8")));
  }
  writeFileSync(
    nodeBindings,
    addExplicitInterfaceReexports(
      readFileSync(nodeBindings, "utf8"),
      generatedFiles.map((file) => ({
        specifier: `./${basename(file, ".ts")}`,
        source: readFileSync(file, "utf8"),
      })),
    ),
  );
  for (const file of [nodeBindings, ...generatedFiles]) {
    stampGenerated(file, {
      tool: "UniFFI binding generation",
      source: `the ${crate} Rust exports`,
    });
  }
  if (!values["node-package-base"]) {
    const nodeLibrary = join(nodeSource, basename(library));
    makeWritable(nodeLibrary);
    cpSync(library, nodeLibrary);
    makeReadonly(nodeLibrary);
  }
  rmSync(resolve(root, values.node, "src/generated"), { recursive: true, force: true });
  rmSync(nodeOutput, { recursive: true, force: true });
  run(process.execPath, [
    resolve(dirname(fileURLToPath(import.meta.url)), "barrels.ts"),
    "--dir",
    resolve(root, values.node),
  ]);
}

if (values.python) {
  const pythonPackage = resolve(
    root,
    values.python,
    "src/dbx_tools",
    crate.replace(/^dbx-tools-/, "").replaceAll("-", "_"),
  );
  const pythonOutput = mkdtempSync(join(tmpdir(), `${libraryName}-python-`));
  run("cargo", [
    "run",
    "--release",
    "--package",
    crate,
    "--bin",
    "uniffi-bindgen",
    "--",
    "generate",
    "--language",
    "python",
    "--out-dir",
    pythonOutput,
    library,
  ]);
  const generated = join(pythonOutput, `${libraryName}.py`);
  const pythonBindings = join(pythonPackage, "bindings.py");
  replaceGenerated(generated, pythonBindings);
  stampGeneratedPython(pythonBindings);
  const pythonInit = join(pythonPackage, "__init__.py");
  if (!existsSync(pythonInit)) {
    writeFileSync(
      pythonInit,
      `\"\"\"Python bindings for ${crate}.\"\"\"\n\nfrom .bindings import *  # noqa: F403\n`,
    );
  }
  const pythonLibrary = join(pythonPackage, basename(library));
  makeWritable(pythonLibrary);
  cpSync(library, pythonLibrary);
  makeReadonly(pythonLibrary);
  rmSync(join(pythonPackage, "_generated"), { recursive: true, force: true });
  rmSync(pythonOutput, { recursive: true, force: true });
}
