/**
 * Bun browser-app scaffolding as first-class projen file components.
 *
 * Replaces the old Vite toolchain (`vite.ts`). An `app`-tagged package gets three
 * generated, read-only files that stand in for `vite dev` / `vite build`:
 *
 * - {@link BunfigFile} - `bunfig.toml` wiring `bun-plugin-tailwind` into both the
 *   dev server (`[serve.static]`) and `Bun.build` (`[build]`) so Tailwind v4's
 *   `@import "tailwindcss"` + `@source` directives compile with no separate CLI.
 * - {@link BunDevServerFile} - `dev.ts`: a `Bun.serve()` fullstack dev server that
 *   imports `index.html` and serves the SPA with React hot module reloading.
 * - {@link BunBuildFile} - `build.ts`: a `Bun.build()` production bundle of
 *   `index.html` (the `bun-plugin-tailwind` plugin must run through the JS API,
 *   NOT the `bun build` CLI, which does not load it).
 *
 * Each file supports an unmanaged OVERRIDE beside it (`bunfig.override.toml`,
 * `bun-dev.override.ts`, `bun-build.override.ts`): the dev/build scripts import
 * the override's default export and merge it over the generated options, so a
 * package tweaks its server/bundle WITHOUT editing the projen-owned file - the
 * same escape hatch the Vite generator offered via `vite.config.override.*`.
 *
 * bun runs these `.ts` files directly. Being package-ROOT files (not under
 * `src/`), they are outside the package's `tsconfig` include, so their `Bun.*`
 * usage never trips the `app` package's DOM-only `compile`.
 */
import { type Project, TextFile } from "projen";

/** Unmanaged dev-server override module, merged over the generated options if present. */
export const BUN_DEV_OVERRIDE = "bun-dev.override.ts";
/** Unmanaged build override module, merged over the generated options if present. */
export const BUN_BUILD_OVERRIDE = "bun-build.override.ts";
/** Unmanaged bunfig override (documented; merging TOML is left to the user). */
export const BUN_APP_OVERRIDES = ["bunfig.override.toml", BUN_DEV_OVERRIDE, BUN_BUILD_OVERRIDE];

/**
 * Root `bunfig.toml`: pin bun's HOISTED linker workspace-wide.
 *
 * bun's default (isolated) linker instantiates a peer dependency once PER
 * distinct peer context, so a package with many peers (`@mastra/*`) resolves to
 * two peer-hash variants of the SAME `@mastra/core` version - and TypeScript then
 * rejects passing a value built against one to an API typed by the other
 * ("separate declarations of a private property"). The hoisted linker de-dupes to
 * a single flat copy (npm-style), which is what keeps identity-based singletons
 * (AppKit `CacheManager`, Mastra classes, one React) coherent - the same coherence
 * the old cross-workspace `.pnpmfile.cjs` bridge used to guarantee.
 */
export class RootBunfigFile extends TextFile {
  constructor(project: Project) {
    super(project, "bunfig.toml", {
      marker: false,
      readonly: true,
      lines: [
        '# ~~ Generated by projen. To modify, edit .projenrc.ts and run "bunx projen".',
        "# Hoisted (flat) node_modules so a peer dep like @mastra/core resolves to ONE",
        "# copy - the isolated default splits it into peer-hash variants and breaks",
        "# identity-based singletons + cross-package types.",
        "[install]",
        'linker = "hoisted"',
        "",
      ],
    });
  }
}

/**
 * `bunfig.toml`: wire `bun-plugin-tailwind` into the DEV SERVER.
 *
 * Only `[serve.static]` is set - that is the one config bun reads for plugins. The
 * `bun build` CLI does NOT load `bunfig.toml` plugins (a documented limitation),
 * so the production build goes through `Bun.build()`'s JS API in `build.ts`, which
 * passes the plugin directly. A `[build]` section here would be dead config that
 * falsely implies `bun build ./index.html` applies Tailwind, so it is omitted.
 */
export class BunfigFile extends TextFile {
  constructor(project: Project) {
    super(project, "bunfig.toml", {
      marker: true,
      readonly: true,
      lines: [
        "# Tailwind v4 for the dev server (Bun.serve reads [serve.static] plugins).",
        "# Production build applies the plugin via Bun.build's API in build.ts - the",
        "# `bun build` CLI does not load bunfig plugins, so there is no [build] here.",
        "[serve.static]",
        'plugins = ["bun-plugin-tailwind"]',
        "",
      ],
    });
  }
}

/** `dev.ts`: a `Bun.serve()` fullstack dev server with React HMR. */
export class BunDevServerFile extends TextFile {
  constructor(project: Project) {
    super(project, "dev.ts", {
      marker: true,
      readonly: true,
      lines: String.raw`
import { existsSync } from "node:fs";
import index from "./index.html";

// Unmanaged override (${BUN_DEV_OVERRIDE}): its default export is merged over the
// generated serve options - later wins - so a package tweaks the dev server
// without editing this generated file.
let options: Bun.ServeFunctionOptions<unknown, {}> = {
  port: Number(process.env.PORT ?? 5173),
  development: { hmr: true, console: true },
  routes: { "/*": index },
};

const overrideUrl = new URL("./${BUN_DEV_OVERRIDE}", import.meta.url);
if (existsSync(overrideUrl)) {
  const mod = await import(overrideUrl.href);
  const override = typeof mod.default === "function" ? await mod.default() : mod.default;
  options = { ...options, ...override };
}

const server = Bun.serve(options);
console.log("dev server running at " + server.url.href);
`
        .trimStart()
        .split("\n"),
    });
  }
}

/** `build.ts`: a `Bun.build()` production bundle (Tailwind via the plugin API). */
export class BunBuildFile extends TextFile {
  constructor(project: Project) {
    super(project, "build.ts", {
      marker: true,
      readonly: true,
      lines: String.raw`
import { existsSync } from "node:fs";
import tailwind from "bun-plugin-tailwind";

// Unmanaged override (${BUN_BUILD_OVERRIDE}): its default export is merged over
// the generated build options - later wins.
let options: Bun.BuildConfig = {
  entrypoints: ["./index.html"],
  outdir: "./dist",
  minify: true,
  sourcemap: "linked",
  plugins: [tailwind],
};

const overrideUrl = new URL("./${BUN_BUILD_OVERRIDE}", import.meta.url);
if (existsSync(overrideUrl)) {
  const mod = await import(overrideUrl.href);
  const override = typeof mod.default === "function" ? await mod.default() : mod.default;
  options = { ...options, ...override, plugins: [...(options.plugins ?? []), ...(override.plugins ?? [])] };
}

const result = await Bun.build(options);
if (!result.success) {
  for (const message of result.logs) console.error(message);
  process.exit(1);
}
console.log("built " + result.outputs.length + " files to " + options.outdir);
`
        .trimStart()
        .split("\n"),
    });
  }
}
