/**
 * Experimental Rosetta-source generation.
 *
 * A TypeScript file under `rs-packages/<package>/src/` is the canonical Node
 * implementation. Projen copies its TypeScript surface to the matching
 * `packages/<package>/src/` path and extracts one or more `@rs-python` blocks
 * into a conventional Python package path.
 */
import { existsSync, mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { dirname, extname, join, relative, resolve } from "node:path";
import { json, object } from "@dbx-tools/shared-core";
import { Component, javascript } from "projen";
import { header, makeReadonly, makeWritable } from "./generated.ts";
import { toPosix } from "./packages.ts";

export const DEFAULT_RS_PACKAGE_ROOTS = ["rs-packages"] as const;

const SOURCE_EXTENSIONS = new Set([".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs"]);
const PYTHON_BLOCK = /\/\*\s*@rs-python\s*\n([\s\S]*?)\n\s*@rs-end\s*\*\//g;
const NODE_OVERRIDE = /^\s*\/\/\s*@rs-node\s+(.+?)\s*$/m;
const PYTHON_OVERRIDE = /^\s*\/\/\s*@rs-python-path\s+(.+?)\s*$/m;
const RS_METADATA = /^\s*\/\/\s*@rs-(?:node|python-path)\s+.+?\s*$\n?/gm;
const NODE_MARKER = "// GENERATED by projen synth (rs-packages)";
const PYTHON_MARKER = "# GENERATED by projen synth (rs-packages)";

export interface RsPackageOutput {
  readonly source: string;
  readonly node: string;
  readonly python: string;
}

export interface GenerateRsPackagesOptions {
  readonly projectRoot?: string;
  readonly roots?: readonly string[];
}

function sourceFiles(root: string): string[] {
  if (!existsSync(root)) return [];
  const files: string[] = [];
  const visit = (dir: string): void => {
    for (const entry of readdirSync(dir)) {
      const path = join(dir, entry);
      if (statSync(path).isDirectory()) visit(path);
      else if (SOURCE_EXTENSIONS.has(extname(entry))) files.push(path);
    }
  };
  visit(root);
  return files.sort();
}

function dedent(value: string): string {
  const lines = value.replace(/^\n+|\n+$/g, "").split("\n");
  const indents = lines
    .filter((line) => line.trim())
    .map((line) => line.match(/^\s*/)?.[0].length ?? 0);
  const width = indents.length ? Math.min(...indents) : 0;
  return lines.map((line) => line.slice(width)).join("\n");
}

function defaultOutputPaths(
  projectRoot: string,
  root: string,
  source: string,
): Pick<RsPackageOutput, "node" | "python"> {
  const sourceRelative = toPosix(relative(resolve(projectRoot, root), source));
  const segments = sourceRelative.split("/");
  const srcIndex = segments.indexOf("src");
  if (srcIndex < 1) {
    throw new Error(
      `Rosetta source must live under <package>/src/: ${toPosix(relative(projectRoot, source))}`,
    );
  }

  const packageSegments = segments.slice(0, srcIndex);
  const moduleSegments = segments.slice(srcIndex + 1);
  const moduleFile = moduleSegments.pop();
  if (!moduleFile) throw new Error(`Rosetta source has no module name: ${source}`);

  const pythonDistribution = packageSegments.join("-");
  const pythonImport = packageSegments.join("_").replace(/-/g, "_");
  const pythonModule = `${moduleFile.slice(0, -extname(moduleFile).length).replace(/-/g, "_")}.py`;

  return {
    node: resolve(
      projectRoot,
      "packages",
      ...packageSegments,
      "src",
      ...moduleSegments,
      moduleFile,
    ),
    python: resolve(
      projectRoot,
      "python-packages",
      pythonDistribution,
      "src",
      pythonImport,
      ...moduleSegments,
      pythonModule,
    ),
  };
}

function resolveOutput(
  projectRoot: string,
  override: RegExpMatchArray | null,
  fallback: string,
): string {
  const value = override?.[1]?.trim();
  return value ? resolve(projectRoot, value) : fallback;
}

function assertWritableOutput(projectRoot: string, path: string, marker: string): void {
  if (!existsSync(path)) return;
  if (readFileSync(path, "utf8").startsWith(marker)) return;
  throw new Error(
    `Refusing to overwrite hand-authored Rosetta output: ${toPosix(relative(projectRoot, path))}`,
  );
}

function renderSource(projectRoot: string, root: string, source: string): RsPackageOutput {
  const input = readFileSync(source, "utf8");
  const defaults = defaultOutputPaths(projectRoot, root, source);
  const node = resolveOutput(projectRoot, input.match(NODE_OVERRIDE), defaults.node);
  const python = resolveOutput(projectRoot, input.match(PYTHON_OVERRIDE), defaults.python);
  const pythonBlocks = [...input.matchAll(PYTHON_BLOCK)].map((match) => dedent(match[1] ?? ""));

  if (!pythonBlocks.length) {
    throw new Error(
      `Rosetta source needs at least one /* @rs-python ... @rs-end */ block: ${toPosix(relative(projectRoot, source))}`,
    );
  }

  const nodeBody = input.replace(PYTHON_BLOCK, "").replace(RS_METADATA, "").trim();
  const nodeContent = `${header({
    tool: "projen synth (rs-packages)",
    source: toPosix(relative(projectRoot, source)),
  })}\n${nodeBody}\n`;
  const pythonContent = [
    "# GENERATED by projen synth (rs-packages) - DO NOT EDIT.",
    `# Regenerated from ${toPosix(relative(projectRoot, source))}.`,
    "# Hand edits are overwritten; edit the Rosetta source instead.",
    "",
    pythonBlocks.join("\n\n"),
    "",
  ].join("\n");

  for (const [path, content] of [
    [node, nodeContent],
    [python, pythonContent],
  ] as const) {
    assertWritableOutput(projectRoot, path, path === node ? NODE_MARKER : PYTHON_MARKER);
    mkdirSync(dirname(path), { recursive: true });
    makeWritable(path);
    writeFileSync(path, content);
    makeReadonly(path);
  }

  return { source, node, python };
}

/** Read the roots recorded by synth for standalone tasks and watchers. */
export function configuredRsPackageRoots(projectRoot: string): readonly string[] | false {
  const manifest = json.parseRecord(readFileSync(resolve(projectRoot, "package.json"), "utf8"));
  const config = object.isRecord(manifest?.dbxToolsConfig) ? manifest.dbxToolsConfig : undefined;
  const configured = config?.rsPackageRoots;
  if (configured === false) return false;
  if (Array.isArray(configured)) {
    const roots = configured.filter(
      (value): value is string => typeof value === "string" && !!value,
    );
    if (roots.length) return roots;
  }
  return DEFAULT_RS_PACKAGE_ROOTS;
}

export function discoverRsPackageOutputs(
  options: GenerateRsPackagesOptions = {},
): RsPackageOutput[] {
  const projectRoot = resolve(options.projectRoot ?? process.cwd());
  const roots = options.roots ?? DEFAULT_RS_PACKAGE_ROOTS;
  return roots.flatMap((root) =>
    sourceFiles(resolve(projectRoot, root)).map((source) => {
      const defaults = defaultOutputPaths(projectRoot, root, source);
      const input = readFileSync(source, "utf8");
      return {
        source,
        node: resolveOutput(projectRoot, input.match(NODE_OVERRIDE), defaults.node),
        python: resolveOutput(projectRoot, input.match(PYTHON_OVERRIDE), defaults.python),
      };
    }),
  );
}

export function generateRsPackages(options: GenerateRsPackagesOptions = {}): RsPackageOutput[] {
  const projectRoot = resolve(options.projectRoot ?? process.cwd());
  const roots = options.roots ?? DEFAULT_RS_PACKAGE_ROOTS;
  return roots.flatMap((root) =>
    sourceFiles(resolve(projectRoot, root)).map((source) =>
      renderSource(projectRoot, root, source),
    ),
  );
}

/** Projen lifecycle component that regenerates Rosetta outputs after synth. */
export class RsPackages extends Component {
  private readonly outputs: RsPackageOutput[];

  constructor(
    project: javascript.NodeProject,
    private readonly roots: readonly string[] = DEFAULT_RS_PACKAGE_ROOTS,
  ) {
    super(project);
    // Generate during construction so a brand-new Node package exists before the
    // root's package scan later in the same synth. postSynthesize repeats this to
    // restore outputs after projen has written the rest of the tree.
    this.outputs = generateRsPackages({ projectRoot: project.outdir, roots });
    for (const output of this.outputs) {
      const node = `/${toPosix(relative(project.outdir, output.node))}`;
      const python = `/${toPosix(relative(project.outdir, output.python))}`;
      project.annotateGenerated(node);
      project.annotateGenerated(python);
    }
  }

  public override preSynthesize(): void {
    const eslint = javascript.Eslint.of(this.project);
    if (!eslint) return;
    for (const output of this.outputs) {
      eslint.addIgnorePattern(toPosix(relative(this.project.outdir, output.node)));
    }
  }

  public override postSynthesize(): void {
    generateRsPackages({ projectRoot: this.project.outdir, roots: this.roots });
  }
}
