model_list:
  - model_name: "databricks/*"
    litellm_params:
      model: "databricks/*"
  - model_name: "*"
    litellm_params:
      model: "dbx/*"
      allowed_openai_params:
        - reasoning_effort
        - thinking

litellm_settings:
  callbacks:
    - config_provider.dbx_responses_router
    - config_provider.dbx_access_logger
  custom_provider_map:
    - provider: dbx
      custom_handler: config_provider.dbx_provider
  num_retries: 5
