/**
 * Standalone projen config for the `@dbx-tools/projen` engine.
 *
 * This project is intentionally a VANILLA projen `TypeScriptProject` - it does
 * NOT build on the dbx-tools engine it ships (no self-hosting), so it can be
 * synthesized and edited without the bootstrap cycle that dogfooding created.
 * It lives inside the repo but is NOT a member of the root pnpm workspace; the
 * root links to it (see the repo `.pnpmfile.cjs` / `pnpm-workspace.yaml`).
 *
 * The engine imports three `@dbx-tools/*` utility packages at runtime
 * (`shared-core`, `node-core`, `node-path`). They are resolved to local source
 * under `../workspaces/` by this project's `.pnpmfile.cjs`, so they stay listed
 * here as plain (registry-shaped) dependencies.
 */
import { javascript, typescript } from "projen";
import { NodePackageManager } from "projen/lib/javascript";

/**
 * Tag prefix for this package's releases. The repo root tags its own releases
 * `v*`; the engine needs a disjoint namespace on the shared git repo, so it
 * tags `projen-v*` (scope-independent, so it survives a scope rename). Also the
 * trigger + version-lookup key for the release workflow below.
 */
const RELEASE_TAG_PREFIX = "projen-v";

const project = new typescript.TypeScriptProject({
  name: "@dbx-tools/projen",
  defaultReleaseBranch: "main",
  packageManager: NodePackageManager.PNPM,
  projenrcTs: true,
  typescriptVersion: "^5.9.3",
  // Consumed as TypeScript source via tsx (its `main`/`exports` point at .ts),
  // so there is no build/emit step to wire and no jest/eslint ceremony.
  sampleCode: false,
  jest: false,
  eslint: false,
  // Use projen's built-in release machinery (bump / changelog / npm publish
  // tasks) but NOT its GitHub component: a workflow written under
  // `projen/.github/` would never run, since GitHub Actions only executes
  // workflows from the REPO-ROOT `.github/`. The runnable workflow is authored
  // there separately (see `.github/workflows/projen-release.yml` in the repo
  // root, generated by the root `.projenrc.ts`).
  // No GitHub component (a workflow under `projen/.github/` would never run -
  // GitHub Actions only executes workflows from the REPO-ROOT `.github/`), and
  // no projen `release` component: releasing is the `bump` task below plus the
  // tag-driven `projen-release` workflow authored in the root `.projenrc.ts`.
  github: false,
  buildWorkflow: false,
  release: false,
  entrypoint: "index.ts",
  tsconfig: {
    compilerOptions: {
      rootDir: ".",
      module: "ESNext",
      moduleResolution: javascript.TypeScriptModuleResolution.BUNDLER,
      target: "ES2022",
      lib: ["ES2022"],
      skipLibCheck: true,
    },
    include: ["index.ts", "src/**/*.ts", "tasks/**/*.ts"],
  },
  deps: [
    "@clack/prompts@^1.7.0",
    "@dbx-tools/core@*",
    "@dbx-tools/path@*",
    "@dbx-tools/shared-core@*",
    "@typescript-eslint/typescript-estree@^8",
    "commander@^15.0.0",
    "consola@^3.4.2",
    "constructs@^10.6.0",
    "is-identifier@^1",
    "openapi-typescript@^7.13.0",
    "oxc-parser@^0.90.0",
    "p-memoize@^8.0.0",
    "projen@^0.101.6",
    "ts-to-zod@^5.1.0",
    "tsoa@^6.6.0",
    "tsx@^4.23.0",
    "yaml@^2.9.0",
  ],
  devDeps: ["@types/node@^24.6.0"],
});

// This package is consumed as TS source; publish the source subpaths, not a
// compiled `lib/`.
project.package.addField("type", "module");
project.package.addField("main", "index.ts");
project.package.addField("types", "index.ts");
project.package.addField("exports", {
  ".": "./index.ts",
  "./engine-root": "./src/engine-root.ts",
  "./package.json": "./package.json",
});

// Track the hand-authored files projen's default dotfile ignore would drop:
// the pnpm workspace root marker (keeps this project isolated from the parent
// workspace) and the util-dep link hook.
project.gitignore.include(".pnpmfile.cjs", "pnpm-workspace.yaml");

// ...but keep those local-dev-only files OUT of the published tarball: the link
// hook would misresolve deps for a real npm consumer, and the workspace marker
// is meaningless downstream.
project.npmignore?.exclude(
  ".pnpmfile.cjs",
  "pnpm-workspace.yaml",
  ".projenrc.ts",
  "projenrc/",
);

// `projen bump`: compute the next `projen-v*` version (from the higher of the
// latest remote tag and the local package.json), then commit, tag, and push -
// which triggers `projen-release`. Each step is toggleable via `--no-*`
// (e.g. `pnpm bump --level minor --no-publish` to bump + tag without pushing).
project.addTask("bump", {
  exec: `tsx tasks/bump.ts --prefix ${RELEASE_TAG_PREFIX}`,
  receiveArgs: true,
  description: "Bump the release version (default patch), then commit, tag, and push it",
});

project.synth();
