/**
 * Standalone projen config for the `@dbx-tools/projen` engine.
 *
 * This project is intentionally a VANILLA projen `TypeScriptProject` - it does
 * NOT build on the dbx-tools engine it ships (no self-hosting), so it can be
 * synthesized and edited without the bootstrap cycle that dogfooding created.
 * It lives inside the repo AND is now a member of the single bun workspace (the
 * root lists `projen` via `extraWorkspaceMembers`, since this project synthesizes
 * ITSELF and is not a root subproject).
 *
 * The engine imports three `@dbx-tools/*` utility packages at runtime
 * (`shared-core`, `node-core`, `node-path`). As workspace siblings they are
 * declared `workspace:*` and bun links them from local source - no `.pnpmfile.cjs`.
 */
import { readFileSync } from "node:fs";
import { javascript, typescript } from "projen";
import { NodePackageManager } from "projen/lib/javascript";

/**
 * Tag prefix for this package's releases. The repo root tags its own releases
 * `v*`; the engine needs a disjoint namespace on the shared git repo, so it
 * tags `projen-v*` (scope-independent, so it survives a scope rename). Also the
 * trigger + version-lookup key for the release workflow below.
 */
const RELEASE_TAG_PREFIX = "projen-v";
const PACKAGE_VERSION =
  (JSON.parse(readFileSync(new URL("./package.json", import.meta.url), "utf8")) as {
    version?: string;
  }).version ?? "0.0.0";

const project = new typescript.TypeScriptProject({
  name: "@dbx-tools/projen",
  defaultReleaseBranch: "main",
  // A member of the single bun workspace. No nested `pnpm-workspace.yaml` marker
  // (that was only to isolate the old standalone workspace); bun resolves the
  // `workspace:*` sibling deps from the root install.
  packageManager: NodePackageManager.BUN,
  // The projenrc runner is reset to `bun` below (bun runs `.ts` directly). This
  // package is `type: module` and `.projenrc.ts` does a directory import
  // (`projen/lib/javascript`); bun resolves it fine.
  projenrcTs: false,
  typescriptVersion: "^5.9.3",
  // Consumed as TypeScript source via bun (its `main`/`exports` point at .ts),
  // so there is no build/emit step to wire and no jest/eslint ceremony.
  sampleCode: false,
  jest: false,
  eslint: false,
  // Use projen's built-in release machinery (bump / changelog / npm publish
  // tasks) but NOT its GitHub component: a workflow written under
  // `projen/.github/` would never run, since GitHub Actions only executes
  // workflows from the REPO-ROOT `.github/`. The runnable workflow is authored
  // there separately (see `.github/workflows/projen-release.yml` in the repo
  // root, generated by the root `.projenrc.ts`).
  // No GitHub component (a workflow under `projen/.github/` would never run -
  // GitHub Actions only executes workflows from the REPO-ROOT `.github/`), and
  // no projen `release` component: releasing is the `bump` task below plus the
  // tag-driven `projen-release` workflow authored in the root `.projenrc.ts`.
  github: false,
  buildWorkflow: false,
  release: false,
  entrypoint: "index.ts",
  tsconfig: {
    compilerOptions: {
      rootDir: ".",
      module: "ESNext",
      moduleResolution: javascript.TypeScriptModuleResolution.BUNDLER,
      target: "ES2022",
      lib: ["ES2022"],
      skipLibCheck: true,
      // This package ships SOURCE (run through tsx), so it never emits - but its
      // own modules carry the same explicit `.ts` specifiers the packages use,
      // which the compiler only accepts with this on.
      noEmit: true,
      allowImportingTsExtensions: true,
    },
    include: ["index.ts", "src/**/*.ts", "tasks/**/*.ts"],
  },
  deps: [
    "@clack/prompts@^1.7.0",
    // `workspace:*` now that `projen/` is a MEMBER of the single bun workspace:
    // bun links these three from local source and rewrites them to the real
    // published range at publish time (the shared root bump stamps that version),
    // so the engine still cannot resolve an older sibling than it was built with.
    "@dbx-tools/core@workspace:*",
    "@dbx-tools/path@workspace:*",
    "@dbx-tools/shared-core@workspace:*",
    "commander@^15.0.0",
    // `tasks/sync.ts` imports this to fan the watchers out. It resolved here only
    // because the repo root happens to depend on it; a consumer install has no
    // such luck and `sync --watch` dies on a missing module.
    "concurrently@^10.0.3",
    "constructs@^10.6.0",
    "is-identifier@^1",
    "openapi-typescript@^7.13.0",
    "oxc-parser@^0.90.0",
    "projen@^0.101.16",
    "ts-to-zod@^5.1.0",
    "yaml@^2.9.0",
  ],
  devDeps: [
    "@types/node@^24.6.0",
    // Deliberately NOT a runtime dep. The engine only ever loads tsoa lazily, from
    // `generateOpenapi`, which returns before touching it unless some package has
    // tsoa controllers - and a package can only have those if it carries the
    // `server` tag, which adds `tsoa@catalog:` to that package itself. So every
    // workspace that can reach the require already installed tsoa, while one that
    // cannot would be paying 179 packages (and a deprecated glob@10) for a module
    // it never loads. Here it is a devDep so the engine's own openapi run and its
    // `typeof import("tsoa")` types still resolve, without shipping it.
    "tsoa@^6.6.0",
  ],
});

// Preserve the version stamped by the shared root bump. The TypeScriptProject
// constructor's `version` option is ignored when `release: false`, so write the
// generated manifest field explicitly.
project.package.addField("version", PACKAGE_VERSION);

// This package is consumed as TS source; publish the source subpaths, not a
// compiled `lib/`.
project.package.addField("type", "module");
project.package.addField("main", "index.ts");
project.package.addField("types", "index.ts");
project.package.addField("exports", {
  ".": "./index.ts",
  "./package.json": "./package.json",
});

// This package ships SOURCE (its `main`/`exports`/task scripts all point at
// `.ts`, run via tsx), so the published tarball must contain the TypeScript, not
// the compiled `lib/`. A `files` allowlist is the idiomatic, self-contained way
// to say exactly that - it takes precedence over projen's generated `.npmignore`
// (which excludes `/src/`), so `index.ts` (re-exports `./src/*`), the `src/`
// modules, and the `tasks/` scripts a consumer runs as `tsx <engine>/tasks/*.ts`
// are all present. Without it the published `index.ts` imports a missing
// `./src/barrels` and synth dies with ERR_MODULE_NOT_FOUND.
project.package.addField("files", ["index.ts", "src", "tasks"]);

// Keep `.projenrc.ts`/`projenrc/` out of the published tarball.
project.npmignore?.exclude(".projenrc.ts", "projenrc/");

// `projen bump`: compute the next `projen-v*` version (from the higher of the
// latest remote tag and the local package.json), then commit, tag, and push -
// which triggers `projen-release`. Each step is toggleable via `--no-*`
// (e.g. `bun run bump --level minor --no-publish` to bump + tag without pushing).
project.addTask("bump", {
  exec: `bun tasks/bump.ts --prefix ${RELEASE_TAG_PREFIX}`,
  receiveArgs: true,
  description: "Bump the release version (default patch), then commit, tag, and push it",
});

// Run `.projenrc.ts` through bun (bun runs `.ts` directly). `nodejs()` runner
// declares no ts-node/tsx dep; the exec is reset to a plain `bun` below.
new typescript.ProjenrcTs(project, { runner: typescript.TypeScriptRunner.nodejs() });
project.defaultTask?.reset("bun .projenrc.ts");
project.addTask("demo", {
  exec: `bun tasks/demo.ts`,
  description: "Run the demo",
});
project.synth();
