// GENERATED by projen watch - DO NOT EDIT.
// Regenerated from the exporting modules in ./src.
// Hand edits are overwritten on the next watch; this file is read-only.

export const PACKAGE_IDENTIFIER = "@dbx-tools/ui-search";
export const PACKAGE_VERSION = "0.6.172";
export * as reactSearchBox from "./src/react/search-box.tsx";
export * as reactSearchResults from "./src/react/search-results.tsx";
export * as reactUseSearch from "./src/react/use-search.ts";
export type { SearchBoxProps } from "./src/react/search-box.tsx";
export type { SearchResultsProps } from "./src/react/search-results.tsx";
export type { UseSearchOptions, UseSearchState } from "./src/react/use-search.ts";
