// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	getDesktopStatus: () => typedError<DesktopStatus, string>(__TAURI_INVOKE("get_desktop_status")),
	getMetrics: (model: string | null) => typedError<MetricsSnapshot_Serialize, string>(__TAURI_INVOKE("get_metrics", { model })),
	getAuthStatus: () => typedError<AuthStatus, string>(__TAURI_INVOKE("get_auth_status")),
	listProfiles: (refresh: boolean) => typedError<Profiles, string>(__TAURI_INVOKE("list_profiles", { refresh })),
	switchRuntime: (selection: RuntimeSelection) => typedError<AuthStatus, string>(__TAURI_INVOKE("switch_runtime", { selection })),
	cancelModelWaits: (input: ModelControlInput) => typedError<WaitCancellation, string>(__TAURI_INVOKE("cancel_model_waits", { input })),
	retryModelNow: (input: ModelControlInput) => typedError<CooldownRelease, string>(__TAURI_INVOKE("retry_model_now", { input })),
};

/** Events */
export const events = {
	metricsUpdated: makeEvent<MetricsUpdated_Deserialize>("metrics-updated"),
};

/* Types */
export type AuthStatus = {
	runtime: RuntimeStatusDto,
};

/**  One automatic congestion-control transition. */
export type AutoTransition = {
	kind: AutoTransitionKind,
	penaltyBasisPoints: number,
	baseInputBudget: number,
	effectiveInputBudget: number,
};

/**  Stable transition vocabulary shared by logs, health counters, and metrics. */
export type AutoTransitionKind = "activated" | "tightened" | "relaxed" | "deactivated" | "reactivated";

export type BucketSnapshot = {
	startedAtMs: number,
	requests: number,
	inputTokens: number,
	outputTokens: number,
	errors: number,
	rateLimited: number,
	averageLatencyMs: number,
	maximumLatencyMs: number,
};

export type CooldownRelease = {
	model: string,
	matchedCooldownKeys: number,
	releasedCooldowns: number,
};

export type DesktopStatus = {
	running: boolean,
	address: string | null,
};

/**  Resolved metrics behavior supported by the current binary. */
export type MetricsMode = "on" | "off";

/**  Current dashboard and JSON endpoint payload. */
export type MetricsSnapshot = MetricsSnapshot_Serialize | MetricsSnapshot_Deserialize;

/**  Current dashboard and JSON endpoint payload. */
export type MetricsSnapshot_Deserialize = {
	mode: MetricsMode,
	controlsEnabled: boolean,
	generatedAtMs: number,
	uptimeSeconds: number,
	summary: SummarySnapshot,
	history: BucketSnapshot[],
	rollupHistory: BucketSnapshot[],
	models: ModelSnapshot_Deserialize[],
	reasoningLevels: ReasoningLevelSnapshot[],
	rateLimitEvents: RateLimitEvent[],
	retention: RetentionSnapshot,
};

/**  Current dashboard and JSON endpoint payload. */
export type MetricsSnapshot_Serialize = {
	mode: MetricsMode,
	controlsEnabled: boolean,
	generatedAtMs: number,
	uptimeSeconds: number,
	summary: SummarySnapshot,
	history: BucketSnapshot[],
	rollupHistory: BucketSnapshot[],
	models: ModelSnapshot_Serialize[],
	reasoningLevels: ReasoningLevelSnapshot[],
	rateLimitEvents: RateLimitEvent[],
	retention: RetentionSnapshot,
};

export type MetricsUpdated = MetricsUpdated_Serialize | MetricsUpdated_Deserialize;

export type MetricsUpdated_Deserialize = {
	snapshot: MetricsSnapshot_Deserialize,
};

export type MetricsUpdated_Serialize = {
	snapshot: MetricsSnapshot_Serialize,
};

export type ModelControlInput = {
	model: string,
};

export type ModelSnapshot = ModelSnapshot_Serialize | ModelSnapshot_Deserialize;

export type ModelSnapshot_Deserialize = {
	model: string,
	history: BucketSnapshot[],
	rollupHistory: BucketSnapshot[],
	requests: number,
	inputTokens: number,
	outputTokens: number,
	errors: number,
	rateLimited: number,
	oversizedRejections: number,
	retries: number,
	fallbacks: number,
	queueWaitMs: number,
	queueDepth: number,
	queueDepthMax: number,
	p50LatencyMs: number,
	p95LatencyMs: number,
	p99LatencyMs: number,
	limiter: string,
	penaltyBasisPoints: number,
	inputLimit: number | null,
	effectiveInputBudget: number | null,
	inputWindowUsed: number | null,
	capacityWaiters: number,
	cooldownKeys: number,
	cooldownWaiters: number,
	maxRemainingCooldownMs: number,
	probeKeys: number,
	capacityWaitCancellations: number,
	cooldownWaitCancellations: number,
	cooldownReleases: number,
	reasoningLevels: ReasoningLevelSnapshot[],
};

export type ModelSnapshot_Serialize = {
	model: string,
	history?: BucketSnapshot[],
	rollupHistory?: BucketSnapshot[],
	requests: number,
	inputTokens: number,
	outputTokens: number,
	errors: number,
	rateLimited: number,
	oversizedRejections: number,
	retries: number,
	fallbacks: number,
	queueWaitMs: number,
	queueDepth: number,
	queueDepthMax: number,
	p50LatencyMs: number,
	p95LatencyMs: number,
	p99LatencyMs: number,
	limiter: string,
	penaltyBasisPoints: number,
	inputLimit: number | null,
	effectiveInputBudget: number | null,
	inputWindowUsed: number | null,
	capacityWaiters: number,
	cooldownKeys: number,
	cooldownWaiters: number,
	maxRemainingCooldownMs: number,
	probeKeys: number,
	capacityWaitCancellations: number,
	cooldownWaitCancellations: number,
	cooldownReleases: number,
	reasoningLevels: ReasoningLevelSnapshot[],
};

export type ProfileSummary = {
	name: string,
	host: string | null,
	accountId: string | null,
	workspaceId: string | null,
	target: string,
	authKind: string,
};

export type Profiles = {
	profiles: ProfileSummary[],
};

export type RateLimitEvent = {
	atMs: number,
	model: string,
	transition: AutoTransition,
};

export type ReasoningLevelSnapshot = {
	level: string,
	requests: number,
};

export type RetentionSnapshot = {
	detailedResolutionSeconds: number,
	detailedSeconds: number,
	rollupResolutionSeconds: number,
	rollupSeconds: number,
	modelSeriesLimit: number,
	targetBytes: number,
	estimatedBytes: number,
	processLocal: boolean,
};

/**  Profile source accepted by the runtime manager. */
export type RuntimeSelection = 
/**  Resolve the normal ambient Databricks authentication chain. */
{ kind: "ambient" } | 
/**  Resolve one exact named Databricks CLI profile. */
{ kind: "profile"; profile: string };

export type RuntimeStatusDto = {
	generation: number,
	selection: RuntimeSelection,
	profile: string,
	host: string,
	workspaceId: string | null,
	authKind: string,
	persistence: string,
	switchingEnabled: boolean,
};

export type SummarySnapshot = {
	connections: number,
	activeRequests: number,
	activeStreams: number,
	requestsPerMinute: number,
	tokensPerMinute: number,
	p50LatencyMs: number,
	p95LatencyMs: number,
	p99LatencyMs: number,
	rate429Percent: number | null,
	activeModels: number,
	totalRequests: number,
	totalRateLimited: number,
	totalFallbacks: number,
	cooldownKeys: number,
	rateLimitWaiters: number,
	probeKeys: number,
	waitCancellations: number,
	cooldownReleases: number,
};

export type WaitCancellation = {
	model: string,
	capacityWaiters: number,
	cooldownWaiters: number,
	matchedCooldownKeys: number,
	cancelledWaiters: number,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

