// This file was generated by [rspc](https://github.com/specta-rs/rspc). Do not edit this file manually.

export type Procedures = {
    queries: 
        { key: "auth.profiles", input: boolean, result: Profiles } | 
        { key: "auth.status", input: never, result: AuthStatus } | 
        { key: "desktop.status", input: never, result: DesktopStatus } | 
        { key: "metrics.current", input: string | null, result: MetricsSnapshot },
    mutations: 
        { key: "auth.switch", input: RuntimeSelection, result: AuthStatus } | 
        { key: "rateLimits.cancelWaits", input: ModelControlInput, result: WaitCancellation } | 
        { key: "rateLimits.retryNow", input: ModelControlInput, result: CooldownRelease },
    subscriptions: never
};

export type AuthStatus = { runtime: RuntimeStatusDto }

/**
 * One automatic congestion-control transition.
 */
export type AutoTransition = { kind: AutoTransitionKind; penaltyBasisPoints: number; baseInputBudget: number; effectiveInputBudget: number }

/**
 * Stable transition vocabulary shared by logs, health counters, and metrics.
 */
export type AutoTransitionKind = "activated" | "tightened" | "relaxed" | "deactivated" | "reactivated"

export type BucketSnapshot = { startedAtMs: number; requests: number; inputTokens: number; outputTokens: number; errors: number; rateLimited: number; averageLatencyMs: number; maximumLatencyMs: number }

export type CooldownRelease = { model: string; matchedCooldownKeys: number; releasedCooldowns: number }

export type DesktopStatus = { running: boolean; address: string | null }

/**
 * Resolved metrics behavior supported by the current binary.
 */
export type MetricsMode = "on" | "off"

/**
 * Current dashboard and JSON endpoint payload.
 */
export type MetricsSnapshot = { mode: MetricsMode; controlsEnabled: boolean; generatedAtMs: number; uptimeSeconds: number; summary: SummarySnapshot; history: BucketSnapshot[]; rollupHistory: BucketSnapshot[]; models: ModelSnapshot[]; reasoningLevels: ReasoningLevelSnapshot[]; rateLimitEvents: RateLimitEvent[]; retention: RetentionSnapshot }

export type ModelControlInput = { model: string }

export type ModelSnapshot = { model: string; history: BucketSnapshot[]; rollupHistory: BucketSnapshot[]; requests: number; inputTokens: number; outputTokens: number; errors: number; rateLimited: number; oversizedRejections: number; retries: number; fallbacks: number; queueWaitMs: number; queueDepth: number; queueDepthMax: number; p50LatencyMs: number; p95LatencyMs: number; p99LatencyMs: number; limiter: string; penaltyBasisPoints: number; inputLimit: number | null; effectiveInputBudget: number | null; inputWindowUsed: number | null; capacityWaiters: number; cooldownKeys: number; cooldownWaiters: number; maxRemainingCooldownMs: number; probeKeys: number; capacityWaitCancellations: number; cooldownWaitCancellations: number; cooldownReleases: number; reasoningLevels: ReasoningLevelSnapshot[] }

export type ProfileSummary = { name: string; host: string | null; accountId: string | null; workspaceId: string | null; target: string; authKind: string }

export type Profiles = { profiles: ProfileSummary[] }

export type RateLimitEvent = { atMs: number; model: string; transition: AutoTransition }

export type ReasoningLevelSnapshot = { level: string; requests: number }

export type RetentionSnapshot = { detailedResolutionSeconds: number; detailedSeconds: number; rollupResolutionSeconds: number; rollupSeconds: number; modelSeriesLimit: number; targetBytes: number; estimatedBytes: number; processLocal: boolean }

/**
 * Profile source accepted by the runtime manager.
 */
export type RuntimeSelection = 
/**
 * Resolve the normal ambient Databricks authentication chain.
 */
{ kind: "ambient" } | 
/**
 * Resolve one exact named Databricks CLI profile.
 */
{ kind: "profile"; profile: string }

export type RuntimeStatusDto = { generation: number; selection: RuntimeSelection; profile: string; host: string; workspaceId: string | null; authKind: string; persistence: string; switchingEnabled: boolean }

export type SummarySnapshot = { connections: number; activeRequests: number; activeStreams: number; requestsPerMinute: number; tokensPerMinute: number; p50LatencyMs: number; p95LatencyMs: number; p99LatencyMs: number; rate429Percent: number; activeModels: number; totalRequests: number; totalRateLimited: number; totalFallbacks: number; cooldownKeys: number; rateLimitWaiters: number; probeKeys: number; waitCancellations: number; cooldownReleases: number }

export type WaitCancellation = { model: string; capacityWaiters: number; cooldownWaiters: number; matchedCooldownKeys: number; cancelledWaiters: number }
