[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "dbx-tools-u2m-native"
version = "0.1.0"
requires-python = ">=3.10"
description = "Generated Python bindings for dbx-tools-u2m"

[tool.setuptools.packages.find]
where = ["generated"]

[tool.setuptools.package-data]
dbx_tools_u2m_bindings = ["*.dylib", "*.so", "*.dll"]
