// GENERATED by projen watch - DO NOT EDIT.
// Regenerated from the exporting modules in ./src.
// Hand edits are overwritten on the next watch; this file is read-only.

export const PACKAGE_IDENTIFIER = "@dbx-tools/cli-auth";
export const PACKAGE_VERSION = "0.9.50";
export * as cli from "./src/cli.ts";
export * as options from "./src/options.ts";
export { CommanderError } from "./src/cli.ts";
export { AuthCliOptionsSchema, TokenCommandOptionsSchema } from "./src/options.ts";
export type { AuthCliOptions, TokenCommandOptions } from "./src/options.ts";
