// GENERATED by projen watch - DO NOT EDIT.
// Regenerated from the exporting modules in ./src.
// Hand edits are overwritten on the next watch; this file is read-only.

export const PACKAGE_IDENTIFIER = "@dbx-tools/cli-auth";
export const PACKAGE_VERSION = "0.6.177";
export * as cli from "./src/cli.ts";
export { CommanderError } from "./src/cli.ts";
