// GENERATED by UniFFI binding generation - DO NOT EDIT.
// Regenerated from the dbx-tools-databricks-auth Rust exports.
// Hand edits are overwritten on the next watch; this file is read-only.

/* eslint-disable */
// @ts-nocheck
// This file was autogenerated by some hot garbage in the `uniffi-bindgen-react-native` crate.
// Trust me, you don't want to mess with it!
import nativeModule from "./_bindings-ffi.ts";
import { type UniffiRustFutureContinuationCallback, type UniffiForeignFutureDroppedCallback, type UniffiForeignFutureDroppedCallbackStruct, type UniffiForeignFutureResultRustBuffer, type UniffiForeignFutureCompleterustBuffer, type UniffiForeignFutureResultVoid, type UniffiForeignFutureCompletevoid, type UniffiVTableCallbackInterfaceDbxToolsDatabricksAuthStorageAdapter,
} from "./_bindings-ffi.ts";
import { type FfiConverter, type UniffiByteArray, type UniffiGcObject, type UniffiHandle, type UniffiObjectFactory, type UniffiReferenceHolder, type UniffiRustCallStatus, AbstractFfiConverterByteArray, Cursor, FfiConverterArray, FfiConverterBool, FfiConverterInt64, FfiConverterObject, FfiConverterObjectWithCallbacks, FfiConverterOptional, FfiConverterUInt64, FfiConverterUInt8, RustBuffer, UniffiAbstractObject, UniffiEnum, UniffiError, UniffiInternalError, UniffiResult, UniffiRustCaller, destructorGuardSymbol, pointerLiteralSymbol, uniffiCreateFfiConverterString, uniffiCreateRecord, uniffiRustCallAsync, uniffiTraitInterfaceCall, uniffiTraitInterfaceCallAsyncWithError, uniffiTypeNameSymbol, variantOrdinalSymbol,
} from "@ubjs/core";
const uniffiCaller = new UniffiRustCaller(() => ({ code: 0 }));

const uniffiIsDebug =
  // @ts-ignore -- The process global might not be defined
  typeof process !== "object" ||
  // @ts-ignore -- The process global might not be defined
  process?.env?.NODE_ENV !== "production" ||
  false;

// Public interface members begin here.

export async function createPersistentAuth(options: DatabricksAuthOptions, storage: Storage | undefined = undefined, asyncOpts_?: { signal: AbortSignal }): Promise<PersistentAuthLike> /*throws*/ {
    const __stack = uniffiIsDebug ? new Error().stack : undefined;
    try {
        return await uniffiRustCallAsync(
            /*rustCaller:*/ uniffiCaller,
            /*rustFutureFunc:*/ () => {
                return nativeModule().uniffi_dbx_tools_databricks_auth_fn_func_create_persistent_auth(FfiConverterTypeDatabricksAuthOptions.lower(options, nativeModule().rustbuffer_alloc),FfiConverterOptionalTypeStorage.lower(storage, nativeModule().rustbuffer_alloc)
                );
            },
            /*pollFunc:*/ nativeModule().ffi_dbx_tools_databricks_auth_rust_future_poll_u64,
            /*cancelFunc:*/ nativeModule().ffi_dbx_tools_databricks_auth_rust_future_cancel_u64,
            /*completeFunc:*/ nativeModule().ffi_dbx_tools_databricks_auth_rust_future_complete_u64,
            /*freeFunc:*/ nativeModule().ffi_dbx_tools_databricks_auth_rust_future_free_u64,
            // Async returns always go through the JS-side converter: the
            // FFI symbol returns the future handle (u64), and the user-level
            // RustBuffer comes back via the shared `rust_future_complete_*`
            // export. The bytes the runtime hands back must be deserialized
            // here using the per-callable return-type converter.
            /*liftFunc:*/ FfiConverterTypePersistentAuth.lift.bind(FfiConverterTypePersistentAuth),
            /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString),
            /*asyncOpts:*/ asyncOpts_,
            /*errorHandler:*/ FfiConverterTypeDatabricksAuthError.lift.bind(FfiConverterTypeDatabricksAuthError)
        );
    } catch (__error: any) {
        if (uniffiIsDebug && __error instanceof Error) {
            __error.stack = __stack;
        }
        throw __error;
    }
    }

export async function createPersistentAuthWithStorage(options: DatabricksAuthOptions, storage: StorageAdapter, asyncOpts_?: { signal: AbortSignal }): Promise<PersistentAuthLike> /*throws*/ {
    const __stack = uniffiIsDebug ? new Error().stack : undefined;
    try {
        return await uniffiRustCallAsync(
            /*rustCaller:*/ uniffiCaller,
            /*rustFutureFunc:*/ () => {
                return nativeModule().uniffi_dbx_tools_databricks_auth_fn_func_create_persistent_auth_with_storage(FfiConverterTypeDatabricksAuthOptions.lower(options, nativeModule().rustbuffer_alloc),FfiConverterTypeStorageAdapter.lower(storage, nativeModule().rustbuffer_alloc)
                );
            },
            /*pollFunc:*/ nativeModule().ffi_dbx_tools_databricks_auth_rust_future_poll_u64,
            /*cancelFunc:*/ nativeModule().ffi_dbx_tools_databricks_auth_rust_future_cancel_u64,
            /*completeFunc:*/ nativeModule().ffi_dbx_tools_databricks_auth_rust_future_complete_u64,
            /*freeFunc:*/ nativeModule().ffi_dbx_tools_databricks_auth_rust_future_free_u64,
            // Async returns always go through the JS-side converter: the
            // FFI symbol returns the future handle (u64), and the user-level
            // RustBuffer comes back via the shared `rust_future_complete_*`
            // export. The bytes the runtime hands back must be deserialized
            // here using the per-callable return-type converter.
            /*liftFunc:*/ FfiConverterTypePersistentAuth.lift.bind(FfiConverterTypePersistentAuth),
            /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString),
            /*asyncOpts:*/ asyncOpts_,
            /*errorHandler:*/ FfiConverterTypeDatabricksAuthError.lift.bind(FfiConverterTypeDatabricksAuthError)
        );
    } catch (__error: any) {
        if (uniffiIsDebug && __error instanceof Error) {
            __error.stack = __stack;
        }
        throw __error;
    }
    }

const stringConverter = (() => {
    const encoder = new TextEncoder();
    const decoder = new TextDecoder();
    return {
        stringToBytes: (s: string) => encoder.encode(s),
        bytesToString: (ab: UniffiByteArray) => decoder.decode(ab),
        stringByteLength: (s: string) => encoder.encode(s).byteLength,
        writeStringIntoBuffer: (s: string, buf: any, offset: number): number => {
            const view = new Uint8Array(
                buf.arrayBuffer,
                offset,
                buf.arrayBuffer.byteLength - offset,
            );
            return encoder.encodeInto(s, view).written;
        },
        readStringFromBuffer: (buf: any, offset: number, length: number): string =>
            decoder.decode(new Uint8Array(buf.arrayBuffer, offset, length)),
    };
})();
const FfiConverterString = uniffiCreateFfiConverterString(stringConverter);

export type AccessToken = {
    accessToken: string,
    tokenType: string,
    expiry?: string,
    scopes: Array<string>
}

/**
 * Generated factory for {@link AccessToken} record objects.
 */
export const AccessToken = (() => {
    const defaults = () => ({
    });
    const create = (() => {
        return uniffiCreateRecord<AccessToken, ReturnType<typeof defaults>>(defaults);
    })();
    return Object.freeze({
        create,
        new: create,
        defaults: () => Object.freeze(defaults()) as Partial<AccessToken>,
    });
})();

const FfiConverterTypeAccessToken = (() => {
    type TypeName = AccessToken;
    class FFIConverter extends AbstractFfiConverterByteArray<TypeName> {
        readFromCursor(c: Cursor): TypeName {
            return {
                accessToken: FfiConverterString.readFromCursor(c), 
                tokenType: FfiConverterString.readFromCursor(c), 
                expiry: FfiConverterOptionalString.readFromCursor(c), 
                scopes: FfiConverterSequenceString.readFromCursor(c)
            };
        }
        writeIntoCursor(value: TypeName, c: Cursor): void {
            FfiConverterString.writeIntoCursor(value.accessToken, c);
            FfiConverterString.writeIntoCursor(value.tokenType, c);
            FfiConverterOptionalString.writeIntoCursor(value.expiry, c);
            FfiConverterSequenceString.writeIntoCursor(value.scopes, c);
        }
        allocationSize(value: TypeName): number {
            return FfiConverterString.allocationSize(value.accessToken) +
             FfiConverterString.allocationSize(value.tokenType) +
             FfiConverterOptionalString.allocationSize(value.expiry) +
             FfiConverterSequenceString.allocationSize(value.scopes);
            
        }
    };
    return new FFIConverter();
})();

/**
 * Configuration shared by the generated Node and Python auth bindings.
 */
export type DatabricksAuthOptions = {
    profile?: string,
    host?: string,
    accountId?: string,
    workspaceId?: string,
    configFile?: string,
    clientId?: string,
    /**
     * Optional group role requested by M2M token generation.
     */
    groupId?: string,
    /**
     * Explicit Databricks authentication strategy.
     */
    authType?: string,
    scopes?: Array<string>,
    target?: string,
    cacheDir?: string,
    /**
     * Logo URL or data URI displayed by the browser callback page.
     */
    callbackImageSrc?: string,
    lockTimeoutSeconds: bigint,
    loginTimeoutSeconds: bigint,
    refreshBufferSeconds: bigint,
    /**
     * Whether implicit M2M defaults should select one matching U2M profile.
     */
    preferUserToMachine: boolean
}

/**
 * Generated factory for {@link DatabricksAuthOptions} record objects.
 */
export const DatabricksAuthOptions = (() => {
    const defaults = () => ({
        profile: undefined,
        host: undefined,
        accountId: undefined,
        workspaceId: undefined,
        configFile: undefined,
        clientId: undefined,
        groupId: undefined,
        authType: undefined,
        scopes: undefined,
        target: undefined,
        cacheDir: undefined,
        callbackImageSrc: undefined,
        lockTimeoutSeconds: BigInt("30"),
        loginTimeoutSeconds: BigInt("3600"),
        refreshBufferSeconds: BigInt("300"),
        preferUserToMachine: true
    });
    const create = (() => {
        return uniffiCreateRecord<DatabricksAuthOptions, ReturnType<typeof defaults>>(defaults);
    })();
    return Object.freeze({
        create,
        new: create,
        defaults: () => Object.freeze(defaults()) as Partial<DatabricksAuthOptions>,
    });
})();

const FfiConverterTypeDatabricksAuthOptions = (() => {
    type TypeName = DatabricksAuthOptions;
    class FFIConverter extends AbstractFfiConverterByteArray<TypeName> {
        readFromCursor(c: Cursor): TypeName {
            return {
                profile: FfiConverterOptionalString.readFromCursor(c), 
                host: FfiConverterOptionalString.readFromCursor(c), 
                accountId: FfiConverterOptionalString.readFromCursor(c), 
                workspaceId: FfiConverterOptionalString.readFromCursor(c), 
                configFile: FfiConverterOptionalString.readFromCursor(c), 
                clientId: FfiConverterOptionalString.readFromCursor(c), 
                groupId: FfiConverterOptionalString.readFromCursor(c), 
                authType: FfiConverterOptionalString.readFromCursor(c), 
                scopes: FfiConverterOptionalSequenceString.readFromCursor(c), 
                target: FfiConverterOptionalString.readFromCursor(c), 
                cacheDir: FfiConverterOptionalString.readFromCursor(c), 
                callbackImageSrc: FfiConverterOptionalString.readFromCursor(c), 
                lockTimeoutSeconds: FfiConverterUInt64.readFromCursor(c), 
                loginTimeoutSeconds: FfiConverterUInt64.readFromCursor(c), 
                refreshBufferSeconds: FfiConverterInt64.readFromCursor(c), 
                preferUserToMachine: FfiConverterBool.readFromCursor(c)
            };
        }
        writeIntoCursor(value: TypeName, c: Cursor): void {
            FfiConverterOptionalString.writeIntoCursor(value.profile, c);
            FfiConverterOptionalString.writeIntoCursor(value.host, c);
            FfiConverterOptionalString.writeIntoCursor(value.accountId, c);
            FfiConverterOptionalString.writeIntoCursor(value.workspaceId, c);
            FfiConverterOptionalString.writeIntoCursor(value.configFile, c);
            FfiConverterOptionalString.writeIntoCursor(value.clientId, c);
            FfiConverterOptionalString.writeIntoCursor(value.groupId, c);
            FfiConverterOptionalString.writeIntoCursor(value.authType, c);
            FfiConverterOptionalSequenceString.writeIntoCursor(value.scopes, c);
            FfiConverterOptionalString.writeIntoCursor(value.target, c);
            FfiConverterOptionalString.writeIntoCursor(value.cacheDir, c);
            FfiConverterOptionalString.writeIntoCursor(value.callbackImageSrc, c);
            FfiConverterUInt64.writeIntoCursor(value.lockTimeoutSeconds, c);
            FfiConverterUInt64.writeIntoCursor(value.loginTimeoutSeconds, c);
            FfiConverterInt64.writeIntoCursor(value.refreshBufferSeconds, c);
            FfiConverterBool.writeIntoCursor(value.preferUserToMachine, c);
        }
        allocationSize(value: TypeName): number {
            return FfiConverterOptionalString.allocationSize(value.profile) +
             FfiConverterOptionalString.allocationSize(value.host) +
             FfiConverterOptionalString.allocationSize(value.accountId) +
             FfiConverterOptionalString.allocationSize(value.workspaceId) +
             FfiConverterOptionalString.allocationSize(value.configFile) +
             FfiConverterOptionalString.allocationSize(value.clientId) +
             FfiConverterOptionalString.allocationSize(value.groupId) +
             FfiConverterOptionalString.allocationSize(value.authType) +
             FfiConverterOptionalSequenceString.allocationSize(value.scopes) +
             FfiConverterOptionalString.allocationSize(value.target) +
             FfiConverterOptionalString.allocationSize(value.cacheDir) +
             FfiConverterOptionalString.allocationSize(value.callbackImageSrc) +
             FfiConverterUInt64.allocationSize(value.lockTimeoutSeconds) +
             FfiConverterUInt64.allocationSize(value.loginTimeoutSeconds) +
             FfiConverterInt64.allocationSize(value.refreshBufferSeconds) +
             FfiConverterBool.allocationSize(value.preferUserToMachine);
            
        }
    };
    return new FFIConverter();
})();

export enum Storage {
    Auto,
    Memory,
    File,
    Keyring
}

const FfiConverterTypeStorage = (() => {
    type TypeName = Storage;
    class FFIConverter extends AbstractFfiConverterByteArray<TypeName> {
        readFromCursor(c: Cursor): TypeName {
            switch (c.readI32()) {
                case 1: return Storage.Auto;
                case 2: return Storage.Memory;
                case 3: return Storage.File;
                case 4: return Storage.Keyring;
                default: throw new UniffiInternalError.UnexpectedEnumCase();
            }
        }
        writeIntoCursor(value: TypeName, c: Cursor): void {
            switch (value) {
                case Storage.Auto: return c.writeI32(1);
                case Storage.Memory: return c.writeI32(2);
                case Storage.File: return c.writeI32(3);
                case Storage.Keyring: return c.writeI32(4);
            }
        }
        allocationSize(value: TypeName): number {
            return 4;
        }
    }
    return new FFIConverter();
})();

export type DatabricksAuthStatus = {
    profile: string,
    host: string,
    storage: Storage
}

/**
 * Generated factory for {@link DatabricksAuthStatus} record objects.
 */
export const DatabricksAuthStatus = (() => {
    const defaults = () => ({
    });
    const create = (() => {
        return uniffiCreateRecord<DatabricksAuthStatus, ReturnType<typeof defaults>>(defaults);
    })();
    return Object.freeze({
        create,
        new: create,
        defaults: () => Object.freeze(defaults()) as Partial<DatabricksAuthStatus>,
    });
})();

const FfiConverterTypeDatabricksAuthStatus = (() => {
    type TypeName = DatabricksAuthStatus;
    class FFIConverter extends AbstractFfiConverterByteArray<TypeName> {
        readFromCursor(c: Cursor): TypeName {
            return {
                profile: FfiConverterString.readFromCursor(c), 
                host: FfiConverterString.readFromCursor(c), 
                storage: FfiConverterTypeStorage.readFromCursor(c)
            };
        }
        writeIntoCursor(value: TypeName, c: Cursor): void {
            FfiConverterString.writeIntoCursor(value.profile, c);
            FfiConverterString.writeIntoCursor(value.host, c);
            FfiConverterTypeStorage.writeIntoCursor(value.storage, c);
        }
        allocationSize(value: TypeName): number {
            return FfiConverterString.allocationSize(value.profile) +
             FfiConverterString.allocationSize(value.host) +
             FfiConverterTypeStorage.allocationSize(value.storage);
            
        }
    };
    return new FFIConverter();
})();


// Error type: DatabricksAuthError
export enum DatabricksAuthError_Tags {
    Failure = "Failure"
}
export const DatabricksAuthError = (() => {

    type Failure__interface = {
        tag: DatabricksAuthError_Tags.Failure;
        inner: 
Readonly<{message: string}>
    };
    class Failure_ extends UniffiError implements Failure__interface {
        /**
         * @private
         * This field is private and should not be used, use `tag` instead.
         */
        readonly [uniffiTypeNameSymbol] = "DatabricksAuthError";
        readonly tag = DatabricksAuthError_Tags.Failure;
        readonly inner: 
Readonly<{message: string}>;
        constructor(
inner: {message: string }) {
            super("DatabricksAuthError", "Failure");

            this.inner = Object.freeze(inner);
        }
        static new(
inner: {message: string }): Failure_ {
            return new Failure_(inner);
        }

        static instanceOf(obj: any): obj is Failure_ {
            return obj.tag === DatabricksAuthError_Tags.Failure;
        }
        static hasInner(obj: any): obj is Failure_ {
            return Failure_.instanceOf(obj);
        }

        static getInner(obj: Failure_): 
Readonly<{message: string}> {
            return obj.inner;
        }

    }

    function instanceOf(obj: any): obj is DatabricksAuthError {
        return obj[uniffiTypeNameSymbol] === "DatabricksAuthError";
    }

    return Object.freeze({
        instanceOf,
  Failure: Failure_
    });

})();
export type DatabricksAuthError = InstanceType<
    typeof DatabricksAuthError['Failure']
>;

// FfiConverter for enum DatabricksAuthError
const FfiConverterTypeDatabricksAuthError = (() => {
    type TypeName = DatabricksAuthError;
    class FFIConverter extends AbstractFfiConverterByteArray<TypeName> {
        readFromCursor(c: Cursor): TypeName {
            switch (c.readI32()) {
                case 1: return new DatabricksAuthError.Failure({message: FfiConverterString.readFromCursor(c) });
                default: throw new UniffiInternalError.UnexpectedEnumCase();
            }
        }
        writeIntoCursor(value: TypeName, c: Cursor): void {
            switch (value.tag) {
                case DatabricksAuthError_Tags.Failure: {
                    c.writeI32(1);
                    const inner = value.inner;
                    FfiConverterString.writeIntoCursor(inner.message, c);
                    return;
                }
                default:
                    // Throwing from here means that DatabricksAuthError_Tags hasn't matched an ordinal.
                    throw new UniffiInternalError.UnexpectedEnumCase();
            }
        }
        allocationSize(value: TypeName): number {
            switch (value.tag) {
                case DatabricksAuthError_Tags.Failure: {
                    const inner = value.inner;
                    let size = 4;
                    size += FfiConverterString.allocationSize(inner.message);
                    return size;
                }
                default: throw new UniffiInternalError.UnexpectedEnumCase();
            }
        }
    }
    return new FFIConverter();
})();

export interface PersistentAuthLike {
    
    challenge(asyncOpts_?: { signal: AbortSignal }) /*throws*/: Promise<void>;
    forceRefreshToken(asyncOpts_?: { signal: AbortSignal }) /*throws*/: Promise<AccessToken>;
    logout(asyncOpts_?: { signal: AbortSignal }) /*throws*/: Promise<void>;
    status(): DatabricksAuthStatus;
    token(login?: boolean | undefined, asyncOpts_?: { signal: AbortSignal }) /*throws*/: Promise<AccessToken>;
}
/**
 * @deprecated Use `PersistentAuthLike` instead.
 */
export type PersistentAuthInterface = PersistentAuthLike;


export class PersistentAuth extends UniffiAbstractObject implements PersistentAuthLike {

    readonly [uniffiTypeNameSymbol] = "PersistentAuth";
    readonly [destructorGuardSymbol]: UniffiGcObject;
    readonly [pointerLiteralSymbol]: UniffiHandle;
    // No primary constructor declared for this class.
private constructor(pointer: UniffiHandle) {
    super();
    this[pointerLiteralSymbol] = pointer;
    this[destructorGuardSymbol] = uniffiTypePersistentAuthObjectFactory.bless(pointer);
}

    

    
    async challenge(asyncOpts_?: { signal: AbortSignal }): Promise<void> /*throws*/ {
    const __stack = uniffiIsDebug ? new Error().stack : undefined;
    try {
        return await uniffiRustCallAsync(
            /*rustCaller:*/ uniffiCaller,
            /*rustFutureFunc:*/ () => {
                return nativeModule().uniffi_dbx_tools_databricks_auth_fn_method_persistentauth_challenge(
                    uniffiTypePersistentAuthObjectFactory.clonePointer(this)
                );
            },
            /*pollFunc:*/ nativeModule().ffi_dbx_tools_databricks_auth_rust_future_poll_void,
            /*cancelFunc:*/ nativeModule().ffi_dbx_tools_databricks_auth_rust_future_cancel_void,
            /*completeFunc:*/ nativeModule().ffi_dbx_tools_databricks_auth_rust_future_complete_void,
            /*freeFunc:*/ nativeModule().ffi_dbx_tools_databricks_auth_rust_future_free_void,
            /*liftFunc:*/ (_v) => {},
            /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString),
            /*asyncOpts:*/ asyncOpts_,
            /*errorHandler:*/ FfiConverterTypeDatabricksAuthError.lift.bind(FfiConverterTypeDatabricksAuthError)
        );
    } catch (__error: any) {
        if (uniffiIsDebug && __error instanceof Error) {
            __error.stack = __stack;
        }
        throw __error;
    }
    }
    
    async forceRefreshToken(asyncOpts_?: { signal: AbortSignal }): Promise<AccessToken> /*throws*/ {
    const __stack = uniffiIsDebug ? new Error().stack : undefined;
    try {
        return await uniffiRustCallAsync(
            /*rustCaller:*/ uniffiCaller,
            /*rustFutureFunc:*/ () => {
                return nativeModule().uniffi_dbx_tools_databricks_auth_fn_method_persistentauth_force_refresh_token(
                    uniffiTypePersistentAuthObjectFactory.clonePointer(this)
                );
            },
            /*pollFunc:*/ nativeModule().ffi_dbx_tools_databricks_auth_rust_future_poll_rust_buffer,
            /*cancelFunc:*/ nativeModule().ffi_dbx_tools_databricks_auth_rust_future_cancel_rust_buffer,
            /*completeFunc:*/ nativeModule().ffi_dbx_tools_databricks_auth_rust_future_complete_rust_buffer,
            /*freeFunc:*/ nativeModule().ffi_dbx_tools_databricks_auth_rust_future_free_rust_buffer,
            // Async returns always go through the JS-side converter: the
            // FFI symbol returns the future handle (u64), and the user-level
            // RustBuffer comes back via the shared `rust_future_complete_*`
            // export. The bytes the runtime hands back must be deserialized
            // here using the per-callable return-type converter.
            // Borrowed view over foreign memory: the call site owns the free,
            // as on the sync paths. Unconditional — a no-op where buffers are
            // already JS-owned.
            /*liftFunc:*/ (__rb) => {
                try {
                    return FfiConverterTypeAccessToken.lift(__rb);
                } finally {
                    nativeModule().rustbuffer_free(__rb);
                }
            },
            /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString),
            /*asyncOpts:*/ asyncOpts_,
            /*errorHandler:*/ FfiConverterTypeDatabricksAuthError.lift.bind(FfiConverterTypeDatabricksAuthError)
        );
    } catch (__error: any) {
        if (uniffiIsDebug && __error instanceof Error) {
            __error.stack = __stack;
        }
        throw __error;
    }
    }
    
    async logout(asyncOpts_?: { signal: AbortSignal }): Promise<void> /*throws*/ {
    const __stack = uniffiIsDebug ? new Error().stack : undefined;
    try {
        return await uniffiRustCallAsync(
            /*rustCaller:*/ uniffiCaller,
            /*rustFutureFunc:*/ () => {
                return nativeModule().uniffi_dbx_tools_databricks_auth_fn_method_persistentauth_logout(
                    uniffiTypePersistentAuthObjectFactory.clonePointer(this)
                );
            },
            /*pollFunc:*/ nativeModule().ffi_dbx_tools_databricks_auth_rust_future_poll_void,
            /*cancelFunc:*/ nativeModule().ffi_dbx_tools_databricks_auth_rust_future_cancel_void,
            /*completeFunc:*/ nativeModule().ffi_dbx_tools_databricks_auth_rust_future_complete_void,
            /*freeFunc:*/ nativeModule().ffi_dbx_tools_databricks_auth_rust_future_free_void,
            /*liftFunc:*/ (_v) => {},
            /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString),
            /*asyncOpts:*/ asyncOpts_,
            /*errorHandler:*/ FfiConverterTypeDatabricksAuthError.lift.bind(FfiConverterTypeDatabricksAuthError)
        );
    } catch (__error: any) {
        if (uniffiIsDebug && __error instanceof Error) {
            __error.stack = __stack;
        }
        throw __error;
    }
    }
    
    status(): DatabricksAuthStatus {
    const __rb: Uint8Array = uniffiCaller.rustCall(
            /*caller:*/ (callStatus) => {
                return nativeModule().uniffi_dbx_tools_databricks_auth_fn_method_persistentauth_status(
                uniffiTypePersistentAuthObjectFactory.clonePointer(this),
                callStatus);
            },
            /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString),
    );
    try {
        return FfiConverterTypeDatabricksAuthStatus.lift(__rb);
    } finally {
        nativeModule().rustbuffer_free(__rb);
    }
    }
    
    async token(login: boolean | undefined = undefined, asyncOpts_?: { signal: AbortSignal }): Promise<AccessToken> /*throws*/ {
    const __stack = uniffiIsDebug ? new Error().stack : undefined;
    try {
        return await uniffiRustCallAsync(
            /*rustCaller:*/ uniffiCaller,
            /*rustFutureFunc:*/ () => {
                return nativeModule().uniffi_dbx_tools_databricks_auth_fn_method_persistentauth_token(
                    uniffiTypePersistentAuthObjectFactory.clonePointer(this),FfiConverterOptionalBoolean.lower(login, nativeModule().rustbuffer_alloc)
                );
            },
            /*pollFunc:*/ nativeModule().ffi_dbx_tools_databricks_auth_rust_future_poll_rust_buffer,
            /*cancelFunc:*/ nativeModule().ffi_dbx_tools_databricks_auth_rust_future_cancel_rust_buffer,
            /*completeFunc:*/ nativeModule().ffi_dbx_tools_databricks_auth_rust_future_complete_rust_buffer,
            /*freeFunc:*/ nativeModule().ffi_dbx_tools_databricks_auth_rust_future_free_rust_buffer,
            // Async returns always go through the JS-side converter: the
            // FFI symbol returns the future handle (u64), and the user-level
            // RustBuffer comes back via the shared `rust_future_complete_*`
            // export. The bytes the runtime hands back must be deserialized
            // here using the per-callable return-type converter.
            // Borrowed view over foreign memory: the call site owns the free,
            // as on the sync paths. Unconditional — a no-op where buffers are
            // already JS-owned.
            /*liftFunc:*/ (__rb) => {
                try {
                    return FfiConverterTypeAccessToken.lift(__rb);
                } finally {
                    nativeModule().rustbuffer_free(__rb);
                }
            },
            /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString),
            /*asyncOpts:*/ asyncOpts_,
            /*errorHandler:*/ FfiConverterTypeDatabricksAuthError.lift.bind(FfiConverterTypeDatabricksAuthError)
        );
    } catch (__error: any) {
        if (uniffiIsDebug && __error instanceof Error) {
            __error.stack = __stack;
        }
        throw __error;
    }
    }
    

    uniffiDestroy(): void {
        const ptr = (this as any)[destructorGuardSymbol];
        if (ptr !== undefined) {
            const pointer = uniffiTypePersistentAuthObjectFactory.pointer(this);
            uniffiTypePersistentAuthObjectFactory.freePointer(pointer);
            uniffiTypePersistentAuthObjectFactory.unbless(ptr);
            delete (this as any)[destructorGuardSymbol];
        }
    }

    static instanceOf(obj_: any): obj_ is PersistentAuth {
        return uniffiTypePersistentAuthObjectFactory.isConcreteType(obj_);
    }

    
}

const uniffiTypePersistentAuthObjectFactory: UniffiObjectFactory<PersistentAuthLike> = (() => {
    
    /// <reference lib="es2021" />
    const registry = typeof FinalizationRegistry !== 'undefined' ? new FinalizationRegistry<UniffiHandle>((heldValue: UniffiHandle) => {
        uniffiTypePersistentAuthObjectFactory.freePointer(heldValue);
    }) : null;
    
    return {
    create(pointer: UniffiHandle): PersistentAuthLike {
        const instance = Object.create(PersistentAuth.prototype);
        instance[pointerLiteralSymbol] = pointer;
        instance[destructorGuardSymbol] = this.bless(pointer);
        instance[uniffiTypeNameSymbol] = "PersistentAuth";
        return instance;
    },

    
    bless(p: UniffiHandle): UniffiGcObject {
        const ptr = {
            p, // make sure this object doesn't get optimized away.
            markDestroyed: () => undefined,
        };
        if (registry) {
            registry.register(ptr, p, ptr);
        }
        return ptr;
    },

    unbless(ptr_: UniffiGcObject) {
        if (registry) {
            registry.unregister(ptr_);
        }
    },

    pointer(obj_: PersistentAuthLike): UniffiHandle {
        if ((obj_ as any)[destructorGuardSymbol] === undefined) {
            throw new UniffiInternalError.UnexpectedNullPointer();
        }
        return (obj_ as any)[pointerLiteralSymbol];
    },

    clonePointer(obj_: PersistentAuthLike): UniffiHandle {
        const pointer = this.pointer(obj_);
        return uniffiCaller.rustCall(
            /*caller:*/ (callStatus) => nativeModule().uniffi_dbx_tools_databricks_auth_fn_clone_persistentauth(pointer, callStatus),
            /*liftString:*/ FfiConverterString.lift
        );
    },

    freePointer(pointer: UniffiHandle): void {
        uniffiCaller.rustCall(
            /*caller:*/ (callStatus) => nativeModule().uniffi_dbx_tools_databricks_auth_fn_free_persistentauth(pointer, callStatus),
            /*liftString:*/ FfiConverterString.lift
        );
    },

    isConcreteType(obj_: any): obj_ is PersistentAuthLike {
        return obj_[destructorGuardSymbol] && obj_[uniffiTypeNameSymbol] === "PersistentAuth";
    },
}})();
const FfiConverterTypePersistentAuth = new FfiConverterObject(uniffiTypePersistentAuthObjectFactory);

export interface StorageAdapter {
    
    load(profile: string, asyncOpts_?: { signal: AbortSignal }) /*throws*/: Promise<string | undefined>;
    prepareWrite(asyncOpts_?: { signal: AbortSignal }) /*throws*/: Promise<void>;
    save(profile: string, token: string, asyncOpts_?: { signal: AbortSignal }) /*throws*/: Promise<void>;
    remove(profile: string, asyncOpts_?: { signal: AbortSignal }) /*throws*/: Promise<void>;
    acquireLock(profile: string, timeoutMillis: bigint, asyncOpts_?: { signal: AbortSignal }) /*throws*/: Promise<string>;
    releaseLock(lease: string, asyncOpts_?: { signal: AbortSignal }) /*throws*/: Promise<void>;
    name(): string;
}


export class StorageAdapterImpl extends UniffiAbstractObject implements StorageAdapter {

    readonly [uniffiTypeNameSymbol] = "StorageAdapterImpl";
    readonly [destructorGuardSymbol]: UniffiGcObject;
    readonly [pointerLiteralSymbol]: UniffiHandle;
    // No primary constructor declared for this class.
private constructor(pointer: UniffiHandle) {
    super();
    this[pointerLiteralSymbol] = pointer;
    this[destructorGuardSymbol] = uniffiTypeStorageAdapterImplObjectFactory.bless(pointer);
}

    

    
    async load(profile: string, asyncOpts_?: { signal: AbortSignal }): Promise<string | undefined> /*throws*/ {
    const __stack = uniffiIsDebug ? new Error().stack : undefined;
    try {
        return await uniffiRustCallAsync(
            /*rustCaller:*/ uniffiCaller,
            /*rustFutureFunc:*/ () => {
                return nativeModule().uniffi_dbx_tools_databricks_auth_fn_method_storageadapter_load(
                    uniffiTypeStorageAdapterImplObjectFactory.clonePointer(this),FfiConverterString.lower(profile, nativeModule().rustbuffer_alloc)
                );
            },
            /*pollFunc:*/ nativeModule().ffi_dbx_tools_databricks_auth_rust_future_poll_rust_buffer,
            /*cancelFunc:*/ nativeModule().ffi_dbx_tools_databricks_auth_rust_future_cancel_rust_buffer,
            /*completeFunc:*/ nativeModule().ffi_dbx_tools_databricks_auth_rust_future_complete_rust_buffer,
            /*freeFunc:*/ nativeModule().ffi_dbx_tools_databricks_auth_rust_future_free_rust_buffer,
            // Async returns always go through the JS-side converter: the
            // FFI symbol returns the future handle (u64), and the user-level
            // RustBuffer comes back via the shared `rust_future_complete_*`
            // export. The bytes the runtime hands back must be deserialized
            // here using the per-callable return-type converter.
            // Borrowed view over foreign memory: the call site owns the free,
            // as on the sync paths. Unconditional — a no-op where buffers are
            // already JS-owned.
            /*liftFunc:*/ (__rb) => {
                try {
                    return FfiConverterOptionalString.lift(__rb);
                } finally {
                    nativeModule().rustbuffer_free(__rb);
                }
            },
            /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString),
            /*asyncOpts:*/ asyncOpts_,
            /*errorHandler:*/ FfiConverterTypeDatabricksAuthError.lift.bind(FfiConverterTypeDatabricksAuthError)
        );
    } catch (__error: any) {
        if (uniffiIsDebug && __error instanceof Error) {
            __error.stack = __stack;
        }
        throw __error;
    }
    }
    
    async prepareWrite(asyncOpts_?: { signal: AbortSignal }): Promise<void> /*throws*/ {
    const __stack = uniffiIsDebug ? new Error().stack : undefined;
    try {
        return await uniffiRustCallAsync(
            /*rustCaller:*/ uniffiCaller,
            /*rustFutureFunc:*/ () => {
                return nativeModule().uniffi_dbx_tools_databricks_auth_fn_method_storageadapter_prepare_write(
                    uniffiTypeStorageAdapterImplObjectFactory.clonePointer(this)
                );
            },
            /*pollFunc:*/ nativeModule().ffi_dbx_tools_databricks_auth_rust_future_poll_void,
            /*cancelFunc:*/ nativeModule().ffi_dbx_tools_databricks_auth_rust_future_cancel_void,
            /*completeFunc:*/ nativeModule().ffi_dbx_tools_databricks_auth_rust_future_complete_void,
            /*freeFunc:*/ nativeModule().ffi_dbx_tools_databricks_auth_rust_future_free_void,
            /*liftFunc:*/ (_v) => {},
            /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString),
            /*asyncOpts:*/ asyncOpts_,
            /*errorHandler:*/ FfiConverterTypeDatabricksAuthError.lift.bind(FfiConverterTypeDatabricksAuthError)
        );
    } catch (__error: any) {
        if (uniffiIsDebug && __error instanceof Error) {
            __error.stack = __stack;
        }
        throw __error;
    }
    }
    
    async save(profile: string, token: string, asyncOpts_?: { signal: AbortSignal }): Promise<void> /*throws*/ {
    const __stack = uniffiIsDebug ? new Error().stack : undefined;
    try {
        return await uniffiRustCallAsync(
            /*rustCaller:*/ uniffiCaller,
            /*rustFutureFunc:*/ () => {
                return nativeModule().uniffi_dbx_tools_databricks_auth_fn_method_storageadapter_save(
                    uniffiTypeStorageAdapterImplObjectFactory.clonePointer(this),FfiConverterString.lower(profile, nativeModule().rustbuffer_alloc),FfiConverterString.lower(token, nativeModule().rustbuffer_alloc)
                );
            },
            /*pollFunc:*/ nativeModule().ffi_dbx_tools_databricks_auth_rust_future_poll_void,
            /*cancelFunc:*/ nativeModule().ffi_dbx_tools_databricks_auth_rust_future_cancel_void,
            /*completeFunc:*/ nativeModule().ffi_dbx_tools_databricks_auth_rust_future_complete_void,
            /*freeFunc:*/ nativeModule().ffi_dbx_tools_databricks_auth_rust_future_free_void,
            /*liftFunc:*/ (_v) => {},
            /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString),
            /*asyncOpts:*/ asyncOpts_,
            /*errorHandler:*/ FfiConverterTypeDatabricksAuthError.lift.bind(FfiConverterTypeDatabricksAuthError)
        );
    } catch (__error: any) {
        if (uniffiIsDebug && __error instanceof Error) {
            __error.stack = __stack;
        }
        throw __error;
    }
    }
    
    async remove(profile: string, asyncOpts_?: { signal: AbortSignal }): Promise<void> /*throws*/ {
    const __stack = uniffiIsDebug ? new Error().stack : undefined;
    try {
        return await uniffiRustCallAsync(
            /*rustCaller:*/ uniffiCaller,
            /*rustFutureFunc:*/ () => {
                return nativeModule().uniffi_dbx_tools_databricks_auth_fn_method_storageadapter_remove(
                    uniffiTypeStorageAdapterImplObjectFactory.clonePointer(this),FfiConverterString.lower(profile, nativeModule().rustbuffer_alloc)
                );
            },
            /*pollFunc:*/ nativeModule().ffi_dbx_tools_databricks_auth_rust_future_poll_void,
            /*cancelFunc:*/ nativeModule().ffi_dbx_tools_databricks_auth_rust_future_cancel_void,
            /*completeFunc:*/ nativeModule().ffi_dbx_tools_databricks_auth_rust_future_complete_void,
            /*freeFunc:*/ nativeModule().ffi_dbx_tools_databricks_auth_rust_future_free_void,
            /*liftFunc:*/ (_v) => {},
            /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString),
            /*asyncOpts:*/ asyncOpts_,
            /*errorHandler:*/ FfiConverterTypeDatabricksAuthError.lift.bind(FfiConverterTypeDatabricksAuthError)
        );
    } catch (__error: any) {
        if (uniffiIsDebug && __error instanceof Error) {
            __error.stack = __stack;
        }
        throw __error;
    }
    }
    
    async acquireLock(profile: string, timeoutMillis: bigint, asyncOpts_?: { signal: AbortSignal }): Promise<string> /*throws*/ {
    const __stack = uniffiIsDebug ? new Error().stack : undefined;
    try {
        return await uniffiRustCallAsync(
            /*rustCaller:*/ uniffiCaller,
            /*rustFutureFunc:*/ () => {
                return nativeModule().uniffi_dbx_tools_databricks_auth_fn_method_storageadapter_acquire_lock(
                    uniffiTypeStorageAdapterImplObjectFactory.clonePointer(this),FfiConverterString.lower(profile, nativeModule().rustbuffer_alloc),FfiConverterUInt64.lower(timeoutMillis, nativeModule().rustbuffer_alloc)
                );
            },
            /*pollFunc:*/ nativeModule().ffi_dbx_tools_databricks_auth_rust_future_poll_rust_buffer,
            /*cancelFunc:*/ nativeModule().ffi_dbx_tools_databricks_auth_rust_future_cancel_rust_buffer,
            /*completeFunc:*/ nativeModule().ffi_dbx_tools_databricks_auth_rust_future_complete_rust_buffer,
            /*freeFunc:*/ nativeModule().ffi_dbx_tools_databricks_auth_rust_future_free_rust_buffer,
            // Async returns always go through the JS-side converter: the
            // FFI symbol returns the future handle (u64), and the user-level
            // RustBuffer comes back via the shared `rust_future_complete_*`
            // export. The bytes the runtime hands back must be deserialized
            // here using the per-callable return-type converter.
            // Borrowed view over foreign memory: the call site owns the free,
            // as on the sync paths. Unconditional — a no-op where buffers are
            // already JS-owned.
            /*liftFunc:*/ (__rb) => {
                try {
                    return FfiConverterString.lift(__rb);
                } finally {
                    nativeModule().rustbuffer_free(__rb);
                }
            },
            /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString),
            /*asyncOpts:*/ asyncOpts_,
            /*errorHandler:*/ FfiConverterTypeDatabricksAuthError.lift.bind(FfiConverterTypeDatabricksAuthError)
        );
    } catch (__error: any) {
        if (uniffiIsDebug && __error instanceof Error) {
            __error.stack = __stack;
        }
        throw __error;
    }
    }
    
    async releaseLock(lease: string, asyncOpts_?: { signal: AbortSignal }): Promise<void> /*throws*/ {
    const __stack = uniffiIsDebug ? new Error().stack : undefined;
    try {
        return await uniffiRustCallAsync(
            /*rustCaller:*/ uniffiCaller,
            /*rustFutureFunc:*/ () => {
                return nativeModule().uniffi_dbx_tools_databricks_auth_fn_method_storageadapter_release_lock(
                    uniffiTypeStorageAdapterImplObjectFactory.clonePointer(this),FfiConverterString.lower(lease, nativeModule().rustbuffer_alloc)
                );
            },
            /*pollFunc:*/ nativeModule().ffi_dbx_tools_databricks_auth_rust_future_poll_void,
            /*cancelFunc:*/ nativeModule().ffi_dbx_tools_databricks_auth_rust_future_cancel_void,
            /*completeFunc:*/ nativeModule().ffi_dbx_tools_databricks_auth_rust_future_complete_void,
            /*freeFunc:*/ nativeModule().ffi_dbx_tools_databricks_auth_rust_future_free_void,
            /*liftFunc:*/ (_v) => {},
            /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString),
            /*asyncOpts:*/ asyncOpts_,
            /*errorHandler:*/ FfiConverterTypeDatabricksAuthError.lift.bind(FfiConverterTypeDatabricksAuthError)
        );
    } catch (__error: any) {
        if (uniffiIsDebug && __error instanceof Error) {
            __error.stack = __stack;
        }
        throw __error;
    }
    }
    
    name(): string {
    const __rb: Uint8Array = uniffiCaller.rustCall(
            /*caller:*/ (callStatus) => {
                return nativeModule().uniffi_dbx_tools_databricks_auth_fn_method_storageadapter_name(
                uniffiTypeStorageAdapterImplObjectFactory.clonePointer(this),
                callStatus);
            },
            /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString),
    );
    try {
        return FfiConverterString.lift(__rb);
    } finally {
        nativeModule().rustbuffer_free(__rb);
    }
    }
    

    uniffiDestroy(): void {
        const ptr = (this as any)[destructorGuardSymbol];
        if (ptr !== undefined) {
            const pointer = uniffiTypeStorageAdapterImplObjectFactory.pointer(this);
            uniffiTypeStorageAdapterImplObjectFactory.freePointer(pointer);
            uniffiTypeStorageAdapterImplObjectFactory.unbless(ptr);
            delete (this as any)[destructorGuardSymbol];
        }
    }

    static instanceOf(obj_: any): obj_ is StorageAdapterImpl {
        return uniffiTypeStorageAdapterImplObjectFactory.isConcreteType(obj_);
    }

    
}

const uniffiTypeStorageAdapterImplObjectFactory: UniffiObjectFactory<StorageAdapter> = (() => {
    
    /// <reference lib="es2021" />
    const registry = typeof FinalizationRegistry !== 'undefined' ? new FinalizationRegistry<UniffiHandle>((heldValue: UniffiHandle) => {
        uniffiTypeStorageAdapterImplObjectFactory.freePointer(heldValue);
    }) : null;
    
    return {
    create(pointer: UniffiHandle): StorageAdapter {
        const instance = Object.create(StorageAdapterImpl.prototype);
        instance[pointerLiteralSymbol] = pointer;
        instance[destructorGuardSymbol] = this.bless(pointer);
        instance[uniffiTypeNameSymbol] = "StorageAdapterImpl";
        return instance;
    },

    
    bless(p: UniffiHandle): UniffiGcObject {
        const ptr = {
            p, // make sure this object doesn't get optimized away.
            markDestroyed: () => undefined,
        };
        if (registry) {
            registry.register(ptr, p, ptr);
        }
        return ptr;
    },

    unbless(ptr_: UniffiGcObject) {
        if (registry) {
            registry.unregister(ptr_);
        }
    },

    pointer(obj_: StorageAdapter): UniffiHandle {
        if ((obj_ as any)[destructorGuardSymbol] === undefined) {
            throw new UniffiInternalError.UnexpectedNullPointer();
        }
        return (obj_ as any)[pointerLiteralSymbol];
    },

    clonePointer(obj_: StorageAdapter): UniffiHandle {
        const pointer = this.pointer(obj_);
        return uniffiCaller.rustCall(
            /*caller:*/ (callStatus) => nativeModule().uniffi_dbx_tools_databricks_auth_fn_clone_storageadapter(pointer, callStatus),
            /*liftString:*/ FfiConverterString.lift
        );
    },

    freePointer(pointer: UniffiHandle): void {
        uniffiCaller.rustCall(
            /*caller:*/ (callStatus) => nativeModule().uniffi_dbx_tools_databricks_auth_fn_free_storageadapter(pointer, callStatus),
            /*liftString:*/ FfiConverterString.lift
        );
    },

    isConcreteType(obj_: any): obj_ is StorageAdapter {
        return obj_[destructorGuardSymbol] && obj_[uniffiTypeNameSymbol] === "StorageAdapterImpl";
    },
}})();
const FfiConverterTypeStorageAdapter = new FfiConverterObjectWithCallbacks(uniffiTypeStorageAdapterImplObjectFactory);

// Add a vtable for the callbacks that go in StorageAdapter.

// Put the implementation in a struct so we don't pollute the top-level namespace
const uniffiCallbackInterfaceStorageAdapter: { vtable: any; register: () => void; } = {
    // Create the VTable using a series of closures.
    // ts automatically converts these into C callback functions.
    vtable: {
        load: (
            uniffiHandle: bigint,
            profile: Uint8Array,
            uniffiFutureCallback: UniffiForeignFutureCompleterustBuffer,
            uniffiCallbackData: bigint) => {
            const uniffiMakeCall = 
            async (signal: AbortSignal)
            : Promise<string | undefined> => {
                const jsCallback = FfiConverterTypeStorageAdapter.lift(uniffiHandle);
                return await jsCallback.load(
                    FfiConverterString.lift(profile), { signal }
                )
            };
            const uniffiHandleSuccess = (returnValue: string | undefined) => {
                uniffiFutureCallback.call(
                    uniffiFutureCallback,
                    uniffiCallbackData,
                    /* UniffiForeignFutureResultRustBuffer */{
                        return_value: FfiConverterOptionalString.lower(returnValue, nativeModule().rustbuffer_alloc),
                        call_status: uniffiCaller.createCallStatus()
                    }
                );
            };
            const uniffiHandleError = (code: number, errorBuf: UniffiByteArray) => {
                uniffiFutureCallback.call(
                    uniffiFutureCallback,
                    uniffiCallbackData,
                    /* UniffiForeignFutureResultRustBuffer */{
                        return_value: /*empty*/ new Uint8Array(0),
                        // TODO create callstatus with error.
                        call_status: uniffiCaller.createErrorStatus(code, errorBuf),
                    }
                );
            };
            const uniffiForeignFuture = uniffiTraitInterfaceCallAsyncWithError(
                /*makeCall:*/ uniffiMakeCall,
                /*handleSuccess:*/ uniffiHandleSuccess,
                /*handleError:*/ uniffiHandleError,
                /*isErrorType:*/ DatabricksAuthError.instanceOf,
                /*lowerError:*/ FfiConverterTypeDatabricksAuthError.lower.bind(FfiConverterTypeDatabricksAuthError),
                /*lowerString:*/ FfiConverterString.lower.bind(FfiConverterString),
                /*alloc:*/ nativeModule().rustbuffer_alloc,
            );
            return uniffiForeignFuture;
        },
        prepare_write: (
            uniffiHandle: bigint,
            uniffiFutureCallback: UniffiForeignFutureCompletevoid,
            uniffiCallbackData: bigint) => {
            const uniffiMakeCall = 
            async (signal: AbortSignal)
            : Promise<void> => {
                const jsCallback = FfiConverterTypeStorageAdapter.lift(uniffiHandle);
                return await jsCallback.prepareWrite({ signal }
                )
            };
            const uniffiHandleSuccess = (returnValue: void) => {
                uniffiFutureCallback.call(
                    uniffiFutureCallback,
                    uniffiCallbackData,
                    /* UniffiForeignFutureResultVoid */{
                        call_status: uniffiCaller.createCallStatus()
                    }
                );
            };
            const uniffiHandleError = (code: number, errorBuf: UniffiByteArray) => {
                uniffiFutureCallback.call(
                    uniffiFutureCallback,
                    uniffiCallbackData,
                    /* UniffiForeignFutureResultVoid */{
                        // TODO create callstatus with error.
                        call_status: uniffiCaller.createErrorStatus(code, errorBuf),
                    }
                );
            };
            const uniffiForeignFuture = uniffiTraitInterfaceCallAsyncWithError(
                /*makeCall:*/ uniffiMakeCall,
                /*handleSuccess:*/ uniffiHandleSuccess,
                /*handleError:*/ uniffiHandleError,
                /*isErrorType:*/ DatabricksAuthError.instanceOf,
                /*lowerError:*/ FfiConverterTypeDatabricksAuthError.lower.bind(FfiConverterTypeDatabricksAuthError),
                /*lowerString:*/ FfiConverterString.lower.bind(FfiConverterString),
                /*alloc:*/ nativeModule().rustbuffer_alloc,
            );
            return uniffiForeignFuture;
        },
        save: (
            uniffiHandle: bigint,
            profile: Uint8Array,
            token: Uint8Array,
            uniffiFutureCallback: UniffiForeignFutureCompletevoid,
            uniffiCallbackData: bigint) => {
            const uniffiMakeCall = 
            async (signal: AbortSignal)
            : Promise<void> => {
                const jsCallback = FfiConverterTypeStorageAdapter.lift(uniffiHandle);
                return await jsCallback.save(
                    FfiConverterString.lift(profile), 
                    FfiConverterString.lift(token), { signal }
                )
            };
            const uniffiHandleSuccess = (returnValue: void) => {
                uniffiFutureCallback.call(
                    uniffiFutureCallback,
                    uniffiCallbackData,
                    /* UniffiForeignFutureResultVoid */{
                        call_status: uniffiCaller.createCallStatus()
                    }
                );
            };
            const uniffiHandleError = (code: number, errorBuf: UniffiByteArray) => {
                uniffiFutureCallback.call(
                    uniffiFutureCallback,
                    uniffiCallbackData,
                    /* UniffiForeignFutureResultVoid */{
                        // TODO create callstatus with error.
                        call_status: uniffiCaller.createErrorStatus(code, errorBuf),
                    }
                );
            };
            const uniffiForeignFuture = uniffiTraitInterfaceCallAsyncWithError(
                /*makeCall:*/ uniffiMakeCall,
                /*handleSuccess:*/ uniffiHandleSuccess,
                /*handleError:*/ uniffiHandleError,
                /*isErrorType:*/ DatabricksAuthError.instanceOf,
                /*lowerError:*/ FfiConverterTypeDatabricksAuthError.lower.bind(FfiConverterTypeDatabricksAuthError),
                /*lowerString:*/ FfiConverterString.lower.bind(FfiConverterString),
                /*alloc:*/ nativeModule().rustbuffer_alloc,
            );
            return uniffiForeignFuture;
        },
        remove: (
            uniffiHandle: bigint,
            profile: Uint8Array,
            uniffiFutureCallback: UniffiForeignFutureCompletevoid,
            uniffiCallbackData: bigint) => {
            const uniffiMakeCall = 
            async (signal: AbortSignal)
            : Promise<void> => {
                const jsCallback = FfiConverterTypeStorageAdapter.lift(uniffiHandle);
                return await jsCallback.remove(
                    FfiConverterString.lift(profile), { signal }
                )
            };
            const uniffiHandleSuccess = (returnValue: void) => {
                uniffiFutureCallback.call(
                    uniffiFutureCallback,
                    uniffiCallbackData,
                    /* UniffiForeignFutureResultVoid */{
                        call_status: uniffiCaller.createCallStatus()
                    }
                );
            };
            const uniffiHandleError = (code: number, errorBuf: UniffiByteArray) => {
                uniffiFutureCallback.call(
                    uniffiFutureCallback,
                    uniffiCallbackData,
                    /* UniffiForeignFutureResultVoid */{
                        // TODO create callstatus with error.
                        call_status: uniffiCaller.createErrorStatus(code, errorBuf),
                    }
                );
            };
            const uniffiForeignFuture = uniffiTraitInterfaceCallAsyncWithError(
                /*makeCall:*/ uniffiMakeCall,
                /*handleSuccess:*/ uniffiHandleSuccess,
                /*handleError:*/ uniffiHandleError,
                /*isErrorType:*/ DatabricksAuthError.instanceOf,
                /*lowerError:*/ FfiConverterTypeDatabricksAuthError.lower.bind(FfiConverterTypeDatabricksAuthError),
                /*lowerString:*/ FfiConverterString.lower.bind(FfiConverterString),
                /*alloc:*/ nativeModule().rustbuffer_alloc,
            );
            return uniffiForeignFuture;
        },
        acquire_lock: (
            uniffiHandle: bigint,
            profile: Uint8Array,
            timeoutMillis: bigint,
            uniffiFutureCallback: UniffiForeignFutureCompleterustBuffer,
            uniffiCallbackData: bigint) => {
            const uniffiMakeCall = 
            async (signal: AbortSignal)
            : Promise<string> => {
                const jsCallback = FfiConverterTypeStorageAdapter.lift(uniffiHandle);
                return await jsCallback.acquireLock(
                    FfiConverterString.lift(profile), 
                    FfiConverterUInt64.lift(timeoutMillis), { signal }
                )
            };
            const uniffiHandleSuccess = (returnValue: string) => {
                uniffiFutureCallback.call(
                    uniffiFutureCallback,
                    uniffiCallbackData,
                    /* UniffiForeignFutureResultRustBuffer */{
                        return_value: FfiConverterString.lower(returnValue, nativeModule().rustbuffer_alloc),
                        call_status: uniffiCaller.createCallStatus()
                    }
                );
            };
            const uniffiHandleError = (code: number, errorBuf: UniffiByteArray) => {
                uniffiFutureCallback.call(
                    uniffiFutureCallback,
                    uniffiCallbackData,
                    /* UniffiForeignFutureResultRustBuffer */{
                        return_value: /*empty*/ new Uint8Array(0),
                        // TODO create callstatus with error.
                        call_status: uniffiCaller.createErrorStatus(code, errorBuf),
                    }
                );
            };
            const uniffiForeignFuture = uniffiTraitInterfaceCallAsyncWithError(
                /*makeCall:*/ uniffiMakeCall,
                /*handleSuccess:*/ uniffiHandleSuccess,
                /*handleError:*/ uniffiHandleError,
                /*isErrorType:*/ DatabricksAuthError.instanceOf,
                /*lowerError:*/ FfiConverterTypeDatabricksAuthError.lower.bind(FfiConverterTypeDatabricksAuthError),
                /*lowerString:*/ FfiConverterString.lower.bind(FfiConverterString),
                /*alloc:*/ nativeModule().rustbuffer_alloc,
            );
            return uniffiForeignFuture;
        },
        release_lock: (
            uniffiHandle: bigint,
            lease: Uint8Array,
            uniffiFutureCallback: UniffiForeignFutureCompletevoid,
            uniffiCallbackData: bigint) => {
            const uniffiMakeCall = 
            async (signal: AbortSignal)
            : Promise<void> => {
                const jsCallback = FfiConverterTypeStorageAdapter.lift(uniffiHandle);
                return await jsCallback.releaseLock(
                    FfiConverterString.lift(lease), { signal }
                )
            };
            const uniffiHandleSuccess = (returnValue: void) => {
                uniffiFutureCallback.call(
                    uniffiFutureCallback,
                    uniffiCallbackData,
                    /* UniffiForeignFutureResultVoid */{
                        call_status: uniffiCaller.createCallStatus()
                    }
                );
            };
            const uniffiHandleError = (code: number, errorBuf: UniffiByteArray) => {
                uniffiFutureCallback.call(
                    uniffiFutureCallback,
                    uniffiCallbackData,
                    /* UniffiForeignFutureResultVoid */{
                        // TODO create callstatus with error.
                        call_status: uniffiCaller.createErrorStatus(code, errorBuf),
                    }
                );
            };
            const uniffiForeignFuture = uniffiTraitInterfaceCallAsyncWithError(
                /*makeCall:*/ uniffiMakeCall,
                /*handleSuccess:*/ uniffiHandleSuccess,
                /*handleError:*/ uniffiHandleError,
                /*isErrorType:*/ DatabricksAuthError.instanceOf,
                /*lowerError:*/ FfiConverterTypeDatabricksAuthError.lower.bind(FfiConverterTypeDatabricksAuthError),
                /*lowerString:*/ FfiConverterString.lower.bind(FfiConverterString),
                /*alloc:*/ nativeModule().rustbuffer_alloc,
            );
            return uniffiForeignFuture;
        },
        name: (
            uniffiHandle: bigint,) => {
            const uniffiMakeCall = 
            ()
            : string => {
                const jsCallback = FfiConverterTypeStorageAdapter.lift(uniffiHandle);
                return jsCallback.name(
                )
            };
            const uniffiResult = UniffiResult.ready<Uint8Array>();
            const uniffiHandleSuccess = (obj: any) => {
                UniffiResult.writeSuccess(uniffiResult, FfiConverterString.lower(obj, nativeModule().rustbuffer_alloc));
            };
            const uniffiHandleError = (code: number, errBuf: UniffiByteArray) => {
                UniffiResult.writeError(uniffiResult, code, errBuf);
            };
            uniffiTraitInterfaceCall(
                /*makeCall:*/ uniffiMakeCall,
                /*handleSuccess:*/ uniffiHandleSuccess,
                /*handleError:*/ uniffiHandleError,
                /*lowerString:*/ FfiConverterString.lower.bind(FfiConverterString),
                /*alloc:*/ nativeModule().rustbuffer_alloc,
            )
            return uniffiResult;
        },
        uniffi_free: (uniffiHandle: UniffiHandle): void => {
            // this will throw a stale handle error if the handle isn't found.
            FfiConverterTypeStorageAdapter.drop(uniffiHandle);
        },
        uniffi_clone: (uniffiHandle: UniffiHandle): UniffiHandle => {
            return FfiConverterTypeStorageAdapter.clone(uniffiHandle);
        }
    },
    register: () => {nativeModule().uniffi_dbx_tools_databricks_auth_fn_init_callback_vtable_storageadapter(
            uniffiCallbackInterfaceStorageAdapter.vtable
        );
    },
};

// FfiConverter for string | undefined
const FfiConverterOptionalString = new FfiConverterOptional(FfiConverterString);

// FfiConverter for Array<string>
const FfiConverterSequenceString = new FfiConverterArray(FfiConverterString);

// FfiConverter for Array<string> | undefined
const FfiConverterOptionalSequenceString = new FfiConverterOptional(FfiConverterSequenceString);

// FfiConverter for boolean | undefined
const FfiConverterOptionalBoolean = new FfiConverterOptional(FfiConverterBool);

// FfiConverter for Storage | undefined
const FfiConverterOptionalTypeStorage = new FfiConverterOptional(FfiConverterTypeStorage);


/**
 * This should be called before anything else.
 *
 * It is likely that this is being done for you by the library's `index.ts`.
 *
 * It checks versions of uniffi between when the Rust scaffolding was generated
 * and when the bindings were generated.
 *
 * It also initializes the machinery to enable Rust to talk back to Javascript.
 */
function uniffiEnsureInitialized() {
    // Get the bindings contract version from our ComponentInterface
    const bindingsContractVersion = 30;
    // Get the scaffolding contract version by calling the into the dylib
    const scaffoldingContractVersion = nativeModule().ffi_dbx_tools_databricks_auth_uniffi_contract_version();
    if (bindingsContractVersion !== scaffoldingContractVersion) {
        throw new UniffiInternalError.ContractVersionMismatch(scaffoldingContractVersion, bindingsContractVersion);
    }
    if (nativeModule().uniffi_dbx_tools_databricks_auth_checksum_func_create_persistent_auth() !== 27712) {
        throw new UniffiInternalError.ApiChecksumMismatch("uniffi_dbx_tools_databricks_auth_checksum_func_create_persistent_auth");
    }
    if (nativeModule().uniffi_dbx_tools_databricks_auth_checksum_func_create_persistent_auth_with_storage() !== 7095) {
        throw new UniffiInternalError.ApiChecksumMismatch("uniffi_dbx_tools_databricks_auth_checksum_func_create_persistent_auth_with_storage");
    }
    if (nativeModule().uniffi_dbx_tools_databricks_auth_checksum_method_persistentauth_challenge() !== 63701) {
        throw new UniffiInternalError.ApiChecksumMismatch("uniffi_dbx_tools_databricks_auth_checksum_method_persistentauth_challenge");
    }
    if (nativeModule().uniffi_dbx_tools_databricks_auth_checksum_method_persistentauth_force_refresh_token() !== 11152) {
        throw new UniffiInternalError.ApiChecksumMismatch("uniffi_dbx_tools_databricks_auth_checksum_method_persistentauth_force_refresh_token");
    }
    if (nativeModule().uniffi_dbx_tools_databricks_auth_checksum_method_persistentauth_logout() !== 12456) {
        throw new UniffiInternalError.ApiChecksumMismatch("uniffi_dbx_tools_databricks_auth_checksum_method_persistentauth_logout");
    }
    if (nativeModule().uniffi_dbx_tools_databricks_auth_checksum_method_persistentauth_status() !== 24573) {
        throw new UniffiInternalError.ApiChecksumMismatch("uniffi_dbx_tools_databricks_auth_checksum_method_persistentauth_status");
    }
    if (nativeModule().uniffi_dbx_tools_databricks_auth_checksum_method_persistentauth_token() !== 29228) {
        throw new UniffiInternalError.ApiChecksumMismatch("uniffi_dbx_tools_databricks_auth_checksum_method_persistentauth_token");
    }
    if (nativeModule().uniffi_dbx_tools_databricks_auth_checksum_method_storageadapter_load() !== 41257) {
        throw new UniffiInternalError.ApiChecksumMismatch("uniffi_dbx_tools_databricks_auth_checksum_method_storageadapter_load");
    }
    if (nativeModule().uniffi_dbx_tools_databricks_auth_checksum_method_storageadapter_prepare_write() !== 29978) {
        throw new UniffiInternalError.ApiChecksumMismatch("uniffi_dbx_tools_databricks_auth_checksum_method_storageadapter_prepare_write");
    }
    if (nativeModule().uniffi_dbx_tools_databricks_auth_checksum_method_storageadapter_save() !== 24155) {
        throw new UniffiInternalError.ApiChecksumMismatch("uniffi_dbx_tools_databricks_auth_checksum_method_storageadapter_save");
    }
    if (nativeModule().uniffi_dbx_tools_databricks_auth_checksum_method_storageadapter_remove() !== 54298) {
        throw new UniffiInternalError.ApiChecksumMismatch("uniffi_dbx_tools_databricks_auth_checksum_method_storageadapter_remove");
    }
    if (nativeModule().uniffi_dbx_tools_databricks_auth_checksum_method_storageadapter_acquire_lock() !== 57109) {
        throw new UniffiInternalError.ApiChecksumMismatch("uniffi_dbx_tools_databricks_auth_checksum_method_storageadapter_acquire_lock");
    }
    if (nativeModule().uniffi_dbx_tools_databricks_auth_checksum_method_storageadapter_release_lock() !== 59520) {
        throw new UniffiInternalError.ApiChecksumMismatch("uniffi_dbx_tools_databricks_auth_checksum_method_storageadapter_release_lock");
    }
    if (nativeModule().uniffi_dbx_tools_databricks_auth_checksum_method_storageadapter_name() !== 37598) {
        throw new UniffiInternalError.ApiChecksumMismatch("uniffi_dbx_tools_databricks_auth_checksum_method_storageadapter_name");
    }

    uniffiCallbackInterfaceStorageAdapter.register();
    }

export default Object.freeze({
  initialize: uniffiEnsureInitialized,
  converters: {
    FfiConverterTypeAccessToken,
    FfiConverterTypeDatabricksAuthError,
    FfiConverterTypeDatabricksAuthOptions,
    FfiConverterTypeDatabricksAuthStatus,
    FfiConverterTypePersistentAuth,
    FfiConverterTypeStorage,
    FfiConverterTypeStorageAdapter,
  }
});