// GENERATED by UniFFI binding generation - DO NOT EDIT.
// Regenerated from the dbx-tools-databricks-auth Rust exports.
// Hand edits are overwritten on the next watch; this file is read-only.

/* eslint-disable */
// @ts-nocheck
// This file was autogenerated by some hot garbage in the `uniffi-bindgen-react-native` crate.
// Trust me, you don't want to mess with it!
import nativeModule from "./_bindings-ffi.ts";
import { type UniffiRustFutureContinuationCallback, type UniffiForeignFutureDroppedCallback, type UniffiForeignFutureDroppedCallbackStruct,
} from "./_bindings-ffi.ts";
import { type AccessToken, type StorageHandleLike, AuthError, Storage,
} from "@dbx-tools/auth";
import { type FfiConverter, type UniffiByteArray, type UniffiGcObject, type UniffiHandle, type UniffiObjectFactory, AbstractFfiConverterByteArray, Cursor, FfiConverterArray, FfiConverterBool, FfiConverterInt64, FfiConverterObject, FfiConverterOptional, FfiConverterUInt64, RustBuffer, UniffiAbstractObject, UniffiInternalError, UniffiRustCaller, destructorGuardSymbol, pointerLiteralSymbol, uniffiCreateFfiConverterString, uniffiCreateRecord, uniffiRustCallAsync, uniffiTypeNameSymbol,
} from "@ubjs/core";
import { uniffiModule as uniffiDbxToolsAuthModule } from "@dbx-tools/auth";
const { FfiConverterTypeAccessToken, FfiConverterTypeAuthError, FfiConverterTypeStorage, FfiConverterTypeStorageHandle } = uniffiDbxToolsAuthModule.converters;
const uniffiCaller = new UniffiRustCaller(() => ({ code: 0 }));

const uniffiIsDebug =
  // @ts-ignore -- The process global might not be defined
  typeof process !== "object" ||
  // @ts-ignore -- The process global might not be defined
  process?.env?.NODE_ENV !== "production" ||
  false;

// Public interface members begin here.

export async function createPersistentAuth(options: DatabricksAuthOptions, storage: Storage | undefined = undefined, asyncOpts_?: { signal: AbortSignal }): Promise<PersistentAuthLike> /*throws*/ {
    const __stack = uniffiIsDebug ? new Error().stack : undefined;
    try {
        return await uniffiRustCallAsync(
            /*rustCaller:*/ uniffiCaller,
            /*rustFutureFunc:*/ () => {
                return nativeModule().uniffi_dbx_tools_databricks_auth_fn_func_create_persistent_auth(FfiConverterTypeDatabricksAuthOptions.lower(options, nativeModule().rustbuffer_alloc),FfiConverterOptionalTypeStorage.lower(storage, nativeModule().rustbuffer_alloc)
                );
            },
            /*pollFunc:*/ nativeModule().ffi_dbx_tools_databricks_auth_rust_future_poll_u64,
            /*cancelFunc:*/ nativeModule().ffi_dbx_tools_databricks_auth_rust_future_cancel_u64,
            /*completeFunc:*/ nativeModule().ffi_dbx_tools_databricks_auth_rust_future_complete_u64,
            /*freeFunc:*/ nativeModule().ffi_dbx_tools_databricks_auth_rust_future_free_u64,
            // Async returns always go through the JS-side converter: the
            // FFI symbol returns the future handle (u64), and the user-level
            // RustBuffer comes back via the shared `rust_future_complete_*`
            // export. The bytes the runtime hands back must be deserialized
            // here using the per-callable return-type converter.
            /*liftFunc:*/ FfiConverterTypePersistentAuth.lift.bind(FfiConverterTypePersistentAuth),
            /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString),
            /*asyncOpts:*/ asyncOpts_,
            /*errorHandler:*/ FfiConverterTypeAuthError.lift.bind(FfiConverterTypeAuthError)
        );
    } catch (__error: any) {
        if (uniffiIsDebug && __error instanceof Error) {
            __error.stack = __stack;
        }
        throw __error;
    }
    }

export async function createPersistentAuthWithStorage(options: DatabricksAuthOptions, storage: StorageHandleLike, asyncOpts_?: { signal: AbortSignal }): Promise<PersistentAuthLike> /*throws*/ {
    const __stack = uniffiIsDebug ? new Error().stack : undefined;
    try {
        return await uniffiRustCallAsync(
            /*rustCaller:*/ uniffiCaller,
            /*rustFutureFunc:*/ () => {
                return nativeModule().uniffi_dbx_tools_databricks_auth_fn_func_create_persistent_auth_with_storage(FfiConverterTypeDatabricksAuthOptions.lower(options, nativeModule().rustbuffer_alloc),FfiConverterTypeStorageHandle.lower(storage, nativeModule().rustbuffer_alloc)
                );
            },
            /*pollFunc:*/ nativeModule().ffi_dbx_tools_databricks_auth_rust_future_poll_u64,
            /*cancelFunc:*/ nativeModule().ffi_dbx_tools_databricks_auth_rust_future_cancel_u64,
            /*completeFunc:*/ nativeModule().ffi_dbx_tools_databricks_auth_rust_future_complete_u64,
            /*freeFunc:*/ nativeModule().ffi_dbx_tools_databricks_auth_rust_future_free_u64,
            // Async returns always go through the JS-side converter: the
            // FFI symbol returns the future handle (u64), and the user-level
            // RustBuffer comes back via the shared `rust_future_complete_*`
            // export. The bytes the runtime hands back must be deserialized
            // here using the per-callable return-type converter.
            /*liftFunc:*/ FfiConverterTypePersistentAuth.lift.bind(FfiConverterTypePersistentAuth),
            /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString),
            /*asyncOpts:*/ asyncOpts_,
            /*errorHandler:*/ FfiConverterTypeAuthError.lift.bind(FfiConverterTypeAuthError)
        );
    } catch (__error: any) {
        if (uniffiIsDebug && __error instanceof Error) {
            __error.stack = __stack;
        }
        throw __error;
    }
    }

const stringConverter = (() => {
    const encoder = new TextEncoder();
    const decoder = new TextDecoder();
    return {
        stringToBytes: (s: string) => encoder.encode(s),
        bytesToString: (ab: UniffiByteArray) => decoder.decode(ab),
        stringByteLength: (s: string) => encoder.encode(s).byteLength,
        writeStringIntoBuffer: (s: string, buf: any, offset: number): number => {
            const view = new Uint8Array(
                buf.arrayBuffer,
                offset,
                buf.arrayBuffer.byteLength - offset,
            );
            return encoder.encodeInto(s, view).written;
        },
        readStringFromBuffer: (buf: any, offset: number, length: number): string =>
            decoder.decode(new Uint8Array(buf.arrayBuffer, offset, length)),
    };
})();
const FfiConverterString = uniffiCreateFfiConverterString(stringConverter);

/**
 * Configuration shared by the generated Node and Python auth bindings.
 */
export type DatabricksAuthOptions = {
    profile?: string,
    host?: string,
    accountId?: string,
    workspaceId?: string,
    configFile?: string,
    clientId?: string,
    /**
     * Optional group role requested by M2M token generation.
     */
    groupId?: string,
    /**
     * Explicit Databricks authentication strategy.
     */
    authType?: string,
    scopes?: Array<string>,
    target?: string,
    cacheDir?: string,
    /**
     * Logo URL or data URI displayed by the browser callback page.
     */
    callbackImageSrc?: string,
    lockTimeoutSeconds: bigint,
    loginTimeoutSeconds: bigint,
    refreshBufferSeconds: bigint,
    /**
     * Whether implicit M2M defaults should select one matching U2M profile.
     */
    preferUserToMachine: boolean
}

/**
 * Generated factory for {@link DatabricksAuthOptions} record objects.
 */
export const DatabricksAuthOptions = (() => {
    const defaults = () => ({
        profile: undefined,
        host: undefined,
        accountId: undefined,
        workspaceId: undefined,
        configFile: undefined,
        clientId: undefined,
        groupId: undefined,
        authType: undefined,
        scopes: undefined,
        target: undefined,
        cacheDir: undefined,
        callbackImageSrc: undefined,
        lockTimeoutSeconds: BigInt("30"),
        loginTimeoutSeconds: BigInt("3600"),
        refreshBufferSeconds: BigInt("300"),
        preferUserToMachine: true
    });
    const create = (() => {
        return uniffiCreateRecord<DatabricksAuthOptions, ReturnType<typeof defaults>>(defaults);
    })();
    return Object.freeze({
        create,
        new: create,
        defaults: () => Object.freeze(defaults()) as Partial<DatabricksAuthOptions>,
    });
})();

const FfiConverterTypeDatabricksAuthOptions = (() => {
    type TypeName = DatabricksAuthOptions;
    class FFIConverter extends AbstractFfiConverterByteArray<TypeName> {
        readFromCursor(c: Cursor): TypeName {
            return {
                profile: FfiConverterOptionalString.readFromCursor(c),
                host: FfiConverterOptionalString.readFromCursor(c),
                accountId: FfiConverterOptionalString.readFromCursor(c),
                workspaceId: FfiConverterOptionalString.readFromCursor(c),
                configFile: FfiConverterOptionalString.readFromCursor(c),
                clientId: FfiConverterOptionalString.readFromCursor(c),
                groupId: FfiConverterOptionalString.readFromCursor(c),
                authType: FfiConverterOptionalString.readFromCursor(c),
                scopes: FfiConverterOptionalSequenceString.readFromCursor(c),
                target: FfiConverterOptionalString.readFromCursor(c),
                cacheDir: FfiConverterOptionalString.readFromCursor(c),
                callbackImageSrc: FfiConverterOptionalString.readFromCursor(c),
                lockTimeoutSeconds: FfiConverterUInt64.readFromCursor(c),
                loginTimeoutSeconds: FfiConverterUInt64.readFromCursor(c),
                refreshBufferSeconds: FfiConverterInt64.readFromCursor(c),
                preferUserToMachine: FfiConverterBool.readFromCursor(c)
            };
        }
        writeIntoCursor(value: TypeName, c: Cursor): void {
            FfiConverterOptionalString.writeIntoCursor(value.profile, c);
            FfiConverterOptionalString.writeIntoCursor(value.host, c);
            FfiConverterOptionalString.writeIntoCursor(value.accountId, c);
            FfiConverterOptionalString.writeIntoCursor(value.workspaceId, c);
            FfiConverterOptionalString.writeIntoCursor(value.configFile, c);
            FfiConverterOptionalString.writeIntoCursor(value.clientId, c);
            FfiConverterOptionalString.writeIntoCursor(value.groupId, c);
            FfiConverterOptionalString.writeIntoCursor(value.authType, c);
            FfiConverterOptionalSequenceString.writeIntoCursor(value.scopes, c);
            FfiConverterOptionalString.writeIntoCursor(value.target, c);
            FfiConverterOptionalString.writeIntoCursor(value.cacheDir, c);
            FfiConverterOptionalString.writeIntoCursor(value.callbackImageSrc, c);
            FfiConverterUInt64.writeIntoCursor(value.lockTimeoutSeconds, c);
            FfiConverterUInt64.writeIntoCursor(value.loginTimeoutSeconds, c);
            FfiConverterInt64.writeIntoCursor(value.refreshBufferSeconds, c);
            FfiConverterBool.writeIntoCursor(value.preferUserToMachine, c);
        }
        allocationSize(value: TypeName): number {
            return FfiConverterOptionalString.allocationSize(value.profile) +
             FfiConverterOptionalString.allocationSize(value.host) +
             FfiConverterOptionalString.allocationSize(value.accountId) +
             FfiConverterOptionalString.allocationSize(value.workspaceId) +
             FfiConverterOptionalString.allocationSize(value.configFile) +
             FfiConverterOptionalString.allocationSize(value.clientId) +
             FfiConverterOptionalString.allocationSize(value.groupId) +
             FfiConverterOptionalString.allocationSize(value.authType) +
             FfiConverterOptionalSequenceString.allocationSize(value.scopes) +
             FfiConverterOptionalString.allocationSize(value.target) +
             FfiConverterOptionalString.allocationSize(value.cacheDir) +
             FfiConverterOptionalString.allocationSize(value.callbackImageSrc) +
             FfiConverterUInt64.allocationSize(value.lockTimeoutSeconds) +
             FfiConverterUInt64.allocationSize(value.loginTimeoutSeconds) +
             FfiConverterInt64.allocationSize(value.refreshBufferSeconds) +
             FfiConverterBool.allocationSize(value.preferUserToMachine);

        }
    };
    return new FFIConverter();
})();

export type DatabricksAuthStatus = {
    profile: string,
    host: string,
    storage: Storage
}

/**
 * Generated factory for {@link DatabricksAuthStatus} record objects.
 */
export const DatabricksAuthStatus = (() => {
    const defaults = () => ({
    });
    const create = (() => {
        return uniffiCreateRecord<DatabricksAuthStatus, ReturnType<typeof defaults>>(defaults);
    })();
    return Object.freeze({
        create,
        new: create,
        defaults: () => Object.freeze(defaults()) as Partial<DatabricksAuthStatus>,
    });
})();

const FfiConverterTypeDatabricksAuthStatus = (() => {
    type TypeName = DatabricksAuthStatus;
    class FFIConverter extends AbstractFfiConverterByteArray<TypeName> {
        readFromCursor(c: Cursor): TypeName {
            return {
                profile: FfiConverterString.readFromCursor(c),
                host: FfiConverterString.readFromCursor(c),
                storage: FfiConverterTypeStorage.readFromCursor(c)
            };
        }
        writeIntoCursor(value: TypeName, c: Cursor): void {
            FfiConverterString.writeIntoCursor(value.profile, c);
            FfiConverterString.writeIntoCursor(value.host, c);
            FfiConverterTypeStorage.writeIntoCursor(value.storage, c);
        }
        allocationSize(value: TypeName): number {
            return FfiConverterString.allocationSize(value.profile) +
             FfiConverterString.allocationSize(value.host) +
             FfiConverterTypeStorage.allocationSize(value.storage);

        }
    };
    return new FFIConverter();
})();

export interface PersistentAuthLike {

    challenge(asyncOpts_?: { signal: AbortSignal }) /*throws*/: Promise<void>;
    forceRefreshToken(asyncOpts_?: { signal: AbortSignal }) /*throws*/: Promise<AccessToken>;
    logout(asyncOpts_?: { signal: AbortSignal }) /*throws*/: Promise<void>;
    refreshRejectedToken(staleAccessToken: string, asyncOpts_?: { signal: AbortSignal }) /*throws*/: Promise<AccessToken>;
    status(): DatabricksAuthStatus;
    token(login?: boolean | undefined, asyncOpts_?: { signal: AbortSignal }) /*throws*/: Promise<AccessToken>;
}
/**
 * @deprecated Use `PersistentAuthLike` instead.
 */
export type PersistentAuthInterface = PersistentAuthLike;


export class PersistentAuth extends UniffiAbstractObject implements PersistentAuthLike {

    readonly [uniffiTypeNameSymbol] = "PersistentAuth";
    readonly [destructorGuardSymbol]: UniffiGcObject;
    readonly [pointerLiteralSymbol]: UniffiHandle;
    // No primary constructor declared for this class.
private constructor(pointer: UniffiHandle) {
    super();
    this[pointerLiteralSymbol] = pointer;
    this[destructorGuardSymbol] = uniffiTypePersistentAuthObjectFactory.bless(pointer);
}




    async challenge(asyncOpts_?: { signal: AbortSignal }): Promise<void> /*throws*/ {
    const __stack = uniffiIsDebug ? new Error().stack : undefined;
    try {
        return await uniffiRustCallAsync(
            /*rustCaller:*/ uniffiCaller,
            /*rustFutureFunc:*/ () => {
                return nativeModule().uniffi_dbx_tools_databricks_auth_fn_method_persistentauth_challenge(
                    uniffiTypePersistentAuthObjectFactory.clonePointer(this)
                );
            },
            /*pollFunc:*/ nativeModule().ffi_dbx_tools_databricks_auth_rust_future_poll_void,
            /*cancelFunc:*/ nativeModule().ffi_dbx_tools_databricks_auth_rust_future_cancel_void,
            /*completeFunc:*/ nativeModule().ffi_dbx_tools_databricks_auth_rust_future_complete_void,
            /*freeFunc:*/ nativeModule().ffi_dbx_tools_databricks_auth_rust_future_free_void,
            /*liftFunc:*/ (_v) => {},
            /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString),
            /*asyncOpts:*/ asyncOpts_,
            /*errorHandler:*/ FfiConverterTypeAuthError.lift.bind(FfiConverterTypeAuthError)
        );
    } catch (__error: any) {
        if (uniffiIsDebug && __error instanceof Error) {
            __error.stack = __stack;
        }
        throw __error;
    }
    }

    async forceRefreshToken(asyncOpts_?: { signal: AbortSignal }): Promise<AccessToken> /*throws*/ {
    const __stack = uniffiIsDebug ? new Error().stack : undefined;
    try {
        return await uniffiRustCallAsync(
            /*rustCaller:*/ uniffiCaller,
            /*rustFutureFunc:*/ () => {
                return nativeModule().uniffi_dbx_tools_databricks_auth_fn_method_persistentauth_force_refresh_token(
                    uniffiTypePersistentAuthObjectFactory.clonePointer(this)
                );
            },
            /*pollFunc:*/ nativeModule().ffi_dbx_tools_databricks_auth_rust_future_poll_rust_buffer,
            /*cancelFunc:*/ nativeModule().ffi_dbx_tools_databricks_auth_rust_future_cancel_rust_buffer,
            /*completeFunc:*/ nativeModule().ffi_dbx_tools_databricks_auth_rust_future_complete_rust_buffer,
            /*freeFunc:*/ nativeModule().ffi_dbx_tools_databricks_auth_rust_future_free_rust_buffer,
            // Async returns always go through the JS-side converter: the
            // FFI symbol returns the future handle (u64), and the user-level
            // RustBuffer comes back via the shared `rust_future_complete_*`
            // export. The bytes the runtime hands back must be deserialized
            // here using the per-callable return-type converter.
            // Borrowed view over foreign memory: the call site owns the free,
            // as on the sync paths. Unconditional — a no-op where buffers are
            // already JS-owned.
            /*liftFunc:*/ (__rb) => {
                try {
                    return FfiConverterTypeAccessToken.lift(__rb);
                } finally {
                    nativeModule().rustbuffer_free(__rb);
                }
            },
            /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString),
            /*asyncOpts:*/ asyncOpts_,
            /*errorHandler:*/ FfiConverterTypeAuthError.lift.bind(FfiConverterTypeAuthError)
        );
    } catch (__error: any) {
        if (uniffiIsDebug && __error instanceof Error) {
            __error.stack = __stack;
        }
        throw __error;
    }
    }

    async logout(asyncOpts_?: { signal: AbortSignal }): Promise<void> /*throws*/ {
    const __stack = uniffiIsDebug ? new Error().stack : undefined;
    try {
        return await uniffiRustCallAsync(
            /*rustCaller:*/ uniffiCaller,
            /*rustFutureFunc:*/ () => {
                return nativeModule().uniffi_dbx_tools_databricks_auth_fn_method_persistentauth_logout(
                    uniffiTypePersistentAuthObjectFactory.clonePointer(this)
                );
            },
            /*pollFunc:*/ nativeModule().ffi_dbx_tools_databricks_auth_rust_future_poll_void,
            /*cancelFunc:*/ nativeModule().ffi_dbx_tools_databricks_auth_rust_future_cancel_void,
            /*completeFunc:*/ nativeModule().ffi_dbx_tools_databricks_auth_rust_future_complete_void,
            /*freeFunc:*/ nativeModule().ffi_dbx_tools_databricks_auth_rust_future_free_void,
            /*liftFunc:*/ (_v) => {},
            /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString),
            /*asyncOpts:*/ asyncOpts_,
            /*errorHandler:*/ FfiConverterTypeAuthError.lift.bind(FfiConverterTypeAuthError)
        );
    } catch (__error: any) {
        if (uniffiIsDebug && __error instanceof Error) {
            __error.stack = __stack;
        }
        throw __error;
    }
    }

    async refreshRejectedToken(staleAccessToken: string, asyncOpts_?: { signal: AbortSignal }): Promise<AccessToken> /*throws*/ {
    const __stack = uniffiIsDebug ? new Error().stack : undefined;
    try {
        return await uniffiRustCallAsync(
            /*rustCaller:*/ uniffiCaller,
            /*rustFutureFunc:*/ () => {
                return nativeModule().uniffi_dbx_tools_databricks_auth_fn_method_persistentauth_refresh_rejected_token(
                    uniffiTypePersistentAuthObjectFactory.clonePointer(this),FfiConverterString.lower(staleAccessToken, nativeModule().rustbuffer_alloc)
                );
            },
            /*pollFunc:*/ nativeModule().ffi_dbx_tools_databricks_auth_rust_future_poll_rust_buffer,
            /*cancelFunc:*/ nativeModule().ffi_dbx_tools_databricks_auth_rust_future_cancel_rust_buffer,
            /*completeFunc:*/ nativeModule().ffi_dbx_tools_databricks_auth_rust_future_complete_rust_buffer,
            /*freeFunc:*/ nativeModule().ffi_dbx_tools_databricks_auth_rust_future_free_rust_buffer,
            // Async returns always go through the JS-side converter: the
            // FFI symbol returns the future handle (u64), and the user-level
            // RustBuffer comes back via the shared `rust_future_complete_*`
            // export. The bytes the runtime hands back must be deserialized
            // here using the per-callable return-type converter.
            // Borrowed view over foreign memory: the call site owns the free,
            // as on the sync paths. Unconditional — a no-op where buffers are
            // already JS-owned.
            /*liftFunc:*/ (__rb) => {
                try {
                    return FfiConverterTypeAccessToken.lift(__rb);
                } finally {
                    nativeModule().rustbuffer_free(__rb);
                }
            },
            /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString),
            /*asyncOpts:*/ asyncOpts_,
            /*errorHandler:*/ FfiConverterTypeAuthError.lift.bind(FfiConverterTypeAuthError)
        );
    } catch (__error: any) {
        if (uniffiIsDebug && __error instanceof Error) {
            __error.stack = __stack;
        }
        throw __error;
    }
    }

    status(): DatabricksAuthStatus {
    const __rb: Uint8Array = uniffiCaller.rustCall(
            /*caller:*/ (callStatus) => {
                return nativeModule().uniffi_dbx_tools_databricks_auth_fn_method_persistentauth_status(
                uniffiTypePersistentAuthObjectFactory.clonePointer(this),
                callStatus);
            },
            /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString),
    );
    try {
        return FfiConverterTypeDatabricksAuthStatus.lift(__rb);
    } finally {
        nativeModule().rustbuffer_free(__rb);
    }
    }

    async token(login: boolean | undefined = undefined, asyncOpts_?: { signal: AbortSignal }): Promise<AccessToken> /*throws*/ {
    const __stack = uniffiIsDebug ? new Error().stack : undefined;
    try {
        return await uniffiRustCallAsync(
            /*rustCaller:*/ uniffiCaller,
            /*rustFutureFunc:*/ () => {
                return nativeModule().uniffi_dbx_tools_databricks_auth_fn_method_persistentauth_token(
                    uniffiTypePersistentAuthObjectFactory.clonePointer(this),FfiConverterOptionalBoolean.lower(login, nativeModule().rustbuffer_alloc)
                );
            },
            /*pollFunc:*/ nativeModule().ffi_dbx_tools_databricks_auth_rust_future_poll_rust_buffer,
            /*cancelFunc:*/ nativeModule().ffi_dbx_tools_databricks_auth_rust_future_cancel_rust_buffer,
            /*completeFunc:*/ nativeModule().ffi_dbx_tools_databricks_auth_rust_future_complete_rust_buffer,
            /*freeFunc:*/ nativeModule().ffi_dbx_tools_databricks_auth_rust_future_free_rust_buffer,
            // Async returns always go through the JS-side converter: the
            // FFI symbol returns the future handle (u64), and the user-level
            // RustBuffer comes back via the shared `rust_future_complete_*`
            // export. The bytes the runtime hands back must be deserialized
            // here using the per-callable return-type converter.
            // Borrowed view over foreign memory: the call site owns the free,
            // as on the sync paths. Unconditional — a no-op where buffers are
            // already JS-owned.
            /*liftFunc:*/ (__rb) => {
                try {
                    return FfiConverterTypeAccessToken.lift(__rb);
                } finally {
                    nativeModule().rustbuffer_free(__rb);
                }
            },
            /*liftString:*/ FfiConverterString.lift.bind(FfiConverterString),
            /*asyncOpts:*/ asyncOpts_,
            /*errorHandler:*/ FfiConverterTypeAuthError.lift.bind(FfiConverterTypeAuthError)
        );
    } catch (__error: any) {
        if (uniffiIsDebug && __error instanceof Error) {
            __error.stack = __stack;
        }
        throw __error;
    }
    }


    uniffiDestroy(): void {
        const ptr = (this as any)[destructorGuardSymbol];
        if (ptr !== undefined) {
            const pointer = uniffiTypePersistentAuthObjectFactory.pointer(this);
            uniffiTypePersistentAuthObjectFactory.freePointer(pointer);
            uniffiTypePersistentAuthObjectFactory.unbless(ptr);
            delete (this as any)[destructorGuardSymbol];
        }
    }

    static instanceOf(obj_: any): obj_ is PersistentAuth {
        return uniffiTypePersistentAuthObjectFactory.isConcreteType(obj_);
    }


}

const uniffiTypePersistentAuthObjectFactory: UniffiObjectFactory<PersistentAuthLike> = (() => {

    /// <reference lib="es2021" />
    const registry = typeof FinalizationRegistry !== 'undefined' ? new FinalizationRegistry<UniffiHandle>((heldValue: UniffiHandle) => {
        uniffiTypePersistentAuthObjectFactory.freePointer(heldValue);
    }) : null;

    return {
    create(pointer: UniffiHandle): PersistentAuthLike {
        const instance = Object.create(PersistentAuth.prototype);
        instance[pointerLiteralSymbol] = pointer;
        instance[destructorGuardSymbol] = this.bless(pointer);
        instance[uniffiTypeNameSymbol] = "PersistentAuth";
        return instance;
    },


    bless(p: UniffiHandle): UniffiGcObject {
        const ptr = {
            p, // make sure this object doesn't get optimized away.
            markDestroyed: () => undefined,
        };
        if (registry) {
            registry.register(ptr, p, ptr);
        }
        return ptr;
    },

    unbless(ptr_: UniffiGcObject) {
        if (registry) {
            registry.unregister(ptr_);
        }
    },

    pointer(obj_: PersistentAuthLike): UniffiHandle {
        if ((obj_ as any)[destructorGuardSymbol] === undefined) {
            throw new UniffiInternalError.UnexpectedNullPointer();
        }
        return (obj_ as any)[pointerLiteralSymbol];
    },

    clonePointer(obj_: PersistentAuthLike): UniffiHandle {
        const pointer = this.pointer(obj_);
        return uniffiCaller.rustCall(
            /*caller:*/ (callStatus) => nativeModule().uniffi_dbx_tools_databricks_auth_fn_clone_persistentauth(pointer, callStatus),
            /*liftString:*/ FfiConverterString.lift
        );
    },

    freePointer(pointer: UniffiHandle): void {
        uniffiCaller.rustCall(
            /*caller:*/ (callStatus) => nativeModule().uniffi_dbx_tools_databricks_auth_fn_free_persistentauth(pointer, callStatus),
            /*liftString:*/ FfiConverterString.lift
        );
    },

    isConcreteType(obj_: any): obj_ is PersistentAuthLike {
        return obj_[destructorGuardSymbol] && obj_[uniffiTypeNameSymbol] === "PersistentAuth";
    },
}})();
const FfiConverterTypePersistentAuth = new FfiConverterObject(uniffiTypePersistentAuthObjectFactory);

// FfiConverter for string | undefined
const FfiConverterOptionalString = new FfiConverterOptional(FfiConverterString);

// FfiConverter for Array<string>
const FfiConverterSequenceString = new FfiConverterArray(FfiConverterString);

// FfiConverter for Array<string> | undefined
const FfiConverterOptionalSequenceString = new FfiConverterOptional(FfiConverterSequenceString);

// FfiConverter for boolean | undefined
const FfiConverterOptionalBoolean = new FfiConverterOptional(FfiConverterBool);

// FfiConverter for Storage | undefined
const FfiConverterOptionalTypeStorage = new FfiConverterOptional(FfiConverterTypeStorage);


/**
 * This should be called before anything else.
 *
 * It is likely that this is being done for you by the library's `index.ts`.
 *
 * It checks versions of uniffi between when the Rust scaffolding was generated
 * and when the bindings were generated.
 *
 * It also initializes the machinery to enable Rust to talk back to Javascript.
 */
function uniffiEnsureInitialized() {
    // Get the bindings contract version from our ComponentInterface
    const bindingsContractVersion = 30;
    // Get the scaffolding contract version by calling the into the dylib
    const scaffoldingContractVersion = nativeModule().ffi_dbx_tools_databricks_auth_uniffi_contract_version();
    if (bindingsContractVersion !== scaffoldingContractVersion) {
        throw new UniffiInternalError.ContractVersionMismatch(scaffoldingContractVersion, bindingsContractVersion);
    }
    if (nativeModule().uniffi_dbx_tools_databricks_auth_checksum_func_create_persistent_auth() !== 40656) {
        throw new UniffiInternalError.ApiChecksumMismatch("uniffi_dbx_tools_databricks_auth_checksum_func_create_persistent_auth");
    }
    if (nativeModule().uniffi_dbx_tools_databricks_auth_checksum_func_create_persistent_auth_with_storage() !== 1043) {
        throw new UniffiInternalError.ApiChecksumMismatch("uniffi_dbx_tools_databricks_auth_checksum_func_create_persistent_auth_with_storage");
    }
    if (nativeModule().uniffi_dbx_tools_databricks_auth_checksum_method_persistentauth_challenge() !== 39859) {
        throw new UniffiInternalError.ApiChecksumMismatch("uniffi_dbx_tools_databricks_auth_checksum_method_persistentauth_challenge");
    }
    if (nativeModule().uniffi_dbx_tools_databricks_auth_checksum_method_persistentauth_force_refresh_token() !== 21349) {
        throw new UniffiInternalError.ApiChecksumMismatch("uniffi_dbx_tools_databricks_auth_checksum_method_persistentauth_force_refresh_token");
    }
    if (nativeModule().uniffi_dbx_tools_databricks_auth_checksum_method_persistentauth_logout() !== 42685) {
        throw new UniffiInternalError.ApiChecksumMismatch("uniffi_dbx_tools_databricks_auth_checksum_method_persistentauth_logout");
    }
    if (nativeModule().uniffi_dbx_tools_databricks_auth_checksum_method_persistentauth_refresh_rejected_token() !== 23475) {
        throw new UniffiInternalError.ApiChecksumMismatch("uniffi_dbx_tools_databricks_auth_checksum_method_persistentauth_refresh_rejected_token");
    }
    if (nativeModule().uniffi_dbx_tools_databricks_auth_checksum_method_persistentauth_status() !== 24573) {
        throw new UniffiInternalError.ApiChecksumMismatch("uniffi_dbx_tools_databricks_auth_checksum_method_persistentauth_status");
    }
    if (nativeModule().uniffi_dbx_tools_databricks_auth_checksum_method_persistentauth_token() !== 42981) {
        throw new UniffiInternalError.ApiChecksumMismatch("uniffi_dbx_tools_databricks_auth_checksum_method_persistentauth_token");
    }

    }

export default Object.freeze({
  initialize: uniffiEnsureInitialized,
  converters: {
    FfiConverterTypeDatabricksAuthOptions,
    FfiConverterTypeDatabricksAuthStatus,
    FfiConverterTypePersistentAuth,
  }
});