# GENERATED by projen/tasks/python-node-bindings.ts - DO NOT EDIT.
# Regenerated from @dbx-tools/postgres#identity configured by packages/py/postgres/pyproject.toml.
# Hand edits are overwritten; this file is read-only.

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, NotRequired, Protocol, TypedDict

from .._runtime import MISSING as _MISSING
from .._runtime import invoke_positioned as _invoke_positioned
from .._runtime import invoke_positioned_sync as _invoke_positioned_sync



class LakebaseConnectionInputsResponse(TypedDict):
    project: NotRequired[str]
    branch: NotRequired[str]
    endpoint: NotRequired[str]
    endpointId: NotRequired[str]
    database: NotRequired[str]
    databaseResourceId: NotRequired[str]
    user: NotRequired[str]
    host: NotRequired[str]
    port: NotRequired[int | float]
    sslMode: NotRequired[str | None]



def advisory_lock_id(
    key: Any,
    explicit: bool | object = _MISSING,
) -> str:
    arguments: list[tuple[int, Any]] = []
    arguments.append((0, key))
    if explicit is not _MISSING:
        arguments.append((1, explicit))
    return _invoke_positioned_sync("postgres__identity", "advisoryLockId", arguments)


def channel_name(
    value: Any,
) -> str:
    arguments: list[tuple[int, Any]] = []
    arguments.append((0, value))
    return _invoke_positioned_sync("postgres__identity", "channelName", arguments)


def parse_address(
    input: str | None,
) -> LakebaseConnectionInputsResponse:
    arguments: list[tuple[int, Any]] = []
    arguments.append((0, input))
    return _invoke_positioned_sync("postgres__identity", "parseAddress", arguments)


def parse_resource_path(
    input: str | None,
) -> LakebaseConnectionInputsResponse:
    arguments: list[tuple[int, Any]] = []
    arguments.append((0, input))
    return _invoke_positioned_sync("postgres__identity", "parseResourcePath", arguments)


def parse_ssl_mode(
    input: str | None,
) -> str | None:
    arguments: list[tuple[int, Any]] = []
    arguments.append((0, input))
    return _invoke_positioned_sync("postgres__identity", "parseSslMode", arguments)


__all__ = [
    "LakebaseConnectionInputsResponse",
    "advisory_lock_id",
    "channel_name",
    "parse_address",
    "parse_resource_path",
    "parse_ssl_mode",
]
