# dbx-tools binding inputs sha256: c4dceaee9b367f73e52a94117f23f1dec01322844f66553c90dcdead02c4ea20
# dbx-tools binding content sha256: 4032545bc00b12ea3e0c859e45e9f4ee9a9a78c0ccde43aacb24b1790313f59c
# GENERATED by projen/tasks/python-node-bindings.ts - DO NOT EDIT.
# Regenerated from @dbx-tools/lakebase#bindings configured by packages/py/graphiti/pyproject.toml.
# Hand edits are overwritten; this file is read-only.

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Protocol, TypedDict

from typing_extensions import NotRequired

from .._runtime import MISSING as _MISSING
from .._runtime import invoke_positioned as _invoke_positioned
from .._runtime import invoke_positioned_sync as _invoke_positioned_sync


@dataclass(kw_only=True)
class AuthOptions:
    refresh_buffer_ms: int | float | None = field(
        default=None,
        metadata={"javascript_name": "refreshBufferMs"},
    )
    lock_timeout_ms: int | float | None = field(
        default=None,
        metadata={"javascript_name": "lockTimeoutMs"},
    )
    login_timeout_ms: int | float | None = field(
        default=None,
        metadata={"javascript_name": "loginTimeoutMs"},
    )


@dataclass(kw_only=True)
class DatabricksAuthOptions:
    auth: AuthOptions | None = field(
        default=None,
        metadata={"javascript_name": "auth"},
    )
    profile: str | None = field(
        default=None,
        metadata={"javascript_name": "profile"},
    )
    host: str | None = field(
        default=None,
        metadata={"javascript_name": "host"},
    )
    account_id: str | None = field(
        default=None,
        metadata={"javascript_name": "accountId"},
    )
    workspace_id: str | None = field(
        default=None,
        metadata={"javascript_name": "workspaceId"},
    )
    config_file: str | None = field(
        default=None,
        metadata={"javascript_name": "configFile"},
    )
    client_id: str | None = field(
        default=None,
        metadata={"javascript_name": "clientId"},
    )
    client_secret: str | None = field(
        default=None,
        metadata={"javascript_name": "clientSecret"},
    )
    access_token: str | None = field(
        default=None,
        metadata={"javascript_name": "accessToken"},
    )
    group_id: str | None = field(
        default=None,
        metadata={"javascript_name": "groupId"},
    )
    auth_type: str | None = field(
        default=None,
        metadata={"javascript_name": "authType"},
    )
    scopes: list[str] | None = field(
        default=None,
        metadata={"javascript_name": "scopes"},
    )
    target: str | None = field(
        default=None,
        metadata={"javascript_name": "target"},
    )
    request_headers: dict[str, str] | None = field(
        default=None,
        metadata={"javascript_name": "requestHeaders"},
    )
    access_token_header: str | None = field(
        default=None,
        metadata={"javascript_name": "accessTokenHeader"},
    )
    prefer_user_to_machine: bool | None = field(
        default=None,
        metadata={"javascript_name": "preferUserToMachine"},
    )


class LakebaseConnectionInputsResponse(TypedDict):
    project: NotRequired[str]
    branch: NotRequired[str]
    endpoint: NotRequired[str]
    endpointId: NotRequired[str]
    database: NotRequired[str]
    databaseResourceId: NotRequired[str]
    user: NotRequired[str]
    host: NotRequired[str]
    port: NotRequired[int | float]
    sslMode: NotRequired[str | None]


class ParsedAddressResponse(TypedDict):
    project: NotRequired[str]
    branch: NotRequired[str]
    endpoint: NotRequired[str]
    endpointId: NotRequired[str]
    database: NotRequired[str]
    databaseResourceId: NotRequired[str]
    user: NotRequired[str]
    host: NotRequired[str]
    port: NotRequired[int | float]
    sslMode: NotRequired[str | None]


class ResolvedLakebaseResponse(TypedDict):
    host: str
    port: int | float
    database: str
    user: str
    endpoint: str
    project: str
    branch: str


class LakebaseClient(Protocol):
    async def resolve(
        self,
        target: LakebaseConnectionInputsResponse,
        startup_user: str = ...,
    ) -> ResolvedLakebaseResponse: ...

    async def generate_database_credential(
        self,
        endpoint: str,
        startup_user: str = ...,
    ) -> str: ...


def create_lakebase_client(
    options: DatabricksAuthOptions | dict[str, Any] | None | object = _MISSING,
) -> LakebaseClient:
    arguments: list[tuple[int, Any]] = []
    if options is not _MISSING:
        arguments.append((0, options))
    return _invoke_positioned_sync("lakebase__bindings", "createLakebaseClient", arguments)


def parse_address(
    input: str | None,
) -> ParsedAddressResponse:
    arguments: list[tuple[int, Any]] = []
    arguments.append((0, input))
    return _invoke_positioned_sync("lakebase__bindings", "parseAddress", arguments)


__all__ = [
    "AuthOptions",
    "DatabricksAuthOptions",
    "LakebaseClient",
    "LakebaseConnectionInputsResponse",
    "ParsedAddressResponse",
    "ResolvedLakebaseResponse",
    "create_lakebase_client",
    "parse_address",
]
