// GENERATED by projen watch - DO NOT EDIT.
// Regenerated from the exporting modules in ./src.
// Hand edits are overwritten on the next watch; this file is read-only.

export const PACKAGE_IDENTIFIER = "@dbx-tools/genie";
export const PACKAGE_VERSION = "0.6.178";
export * as chat from "./src/chat.ts";
export * as space from "./src/space.ts";
export type { GenieChatOptions } from "./src/chat.ts";
export type { GetGenieSpaceOptions } from "./src/space.ts";
