// GENERATED by projen watch - DO NOT EDIT.
// Regenerated from the exporting modules in ./src.
// Hand edits are overwritten on the next watch; this file is read-only.

export * as brand from "./src/brand.ts";
export * as config from "./src/config.ts";
export * as defaults from "./src/defaults.ts";
export * as emailHtml from "./src/email-html.ts";
export * as markdown from "./src/markdown.ts";
export * as outbox from "./src/outbox.ts";
export * as plugin from "./src/plugin.ts";
export * as sender from "./src/sender.ts";
export * as tool from "./src/tool.ts";
export * as transport from "./src/transport.ts";
export { DEFAULT_SMTP_PORT, IMPLICIT_TLS_SMTP_PORT, EMAIL_CONFIG_SCHEMA } from "./src/config.ts";
export type { SenderPolicy, SmtpConfig, EmailPluginConfig, ResolvedSmtpConfig, ResolvedFileConfig, ResolvedEmailConfig } from "./src/config.ts";
export { SEND_TIMEOUT_MS, VERIFY_TIMEOUT_MS, VERIFY_ATTEMPTS, MAX_ATTACHMENT_BYTES, MAX_ATTACHMENTS_TOTAL_BYTES, MAX_ATTACHMENT_COUNT, MAX_BODY_CHARS, EMAIL_SEND_SETTINGS, EMAIL_VERIFY_SETTINGS, EMAIL_SENDERS_SETTINGS } from "./src/defaults.ts";
export type { EmailExecuteConfig, EmailExecutionSettings } from "./src/defaults.ts";
export { escapeHtml } from "./src/email-html.ts";
export type { EmailHtmlOptions } from "./src/email-html.ts";
export { normalizeMarkdown } from "./src/markdown.ts";
export { EmailPlugin, email } from "./src/plugin.ts";
export { SEND_EMAIL_DESCRIPTION } from "./src/tool.ts";
export type { EmailToolOptions } from "./src/tool.ts";
export type { EmailExecutor, EmailRuntime } from "./src/transport.ts";
