// GENERATED by projen - DO NOT EDIT.
// Rust release package options are the source of truth.

export const RELEASE_BINARY_COMMANDS = [
  {
    "command": "lakebase-proxy",
    "description": "Loopback PostgreSQL proxy for Databricks Lakebase",
    "binaryName": "dbx-lakebase-proxy",
    "hidden": false,
    "unit": "rs-lakebase-proxy",
    "component": "rs-lakebase-proxy",
    "version": "0.9.21",
    "tagPrefix": "v",
    "tag": "v0.9.21",
    "repository": "https://github.com/reggie-db/dbx-tools",
    "crateName": "dbx-tools-lakebase-proxy",
    "cargoFeatures": [],
    "assets": [
      {
        "os": "linux",
        "cpu": "x64",
        "name": "dbx-lakebase-proxy-linux-x64-gnu.tar.gz"
      },
      {
        "os": "linux",
        "cpu": "arm64",
        "name": "dbx-lakebase-proxy-linux-arm64-gnu.tar.gz"
      },
      {
        "os": "darwin",
        "cpu": "x64",
        "name": "dbx-lakebase-proxy-darwin-x64.tar.gz"
      },
      {
        "os": "darwin",
        "cpu": "arm64",
        "name": "dbx-lakebase-proxy-darwin-arm64.tar.gz"
      }
    ]
  },
  {
    "command": "model-proxy",
    "description": "Multi-protocol Databricks model proxy",
    "binaryName": "dbx-model-proxy",
    "hidden": false,
    "unit": "rs-model-proxy",
    "component": "rs-model-proxy",
    "version": "0.9.21",
    "tagPrefix": "v",
    "tag": "v0.9.21",
    "repository": "https://github.com/reggie-db/dbx-tools",
    "crateName": "dbx-tools-model-proxy",
    "cargoFeatures": [],
    "assets": [
      {
        "os": "linux",
        "cpu": "x64",
        "name": "dbx-model-proxy-linux-x64-gnu.tar.gz"
      },
      {
        "os": "linux",
        "cpu": "arm64",
        "name": "dbx-model-proxy-linux-arm64-gnu.tar.gz"
      },
      {
        "os": "darwin",
        "cpu": "x64",
        "name": "dbx-model-proxy-darwin-x64.tar.gz"
      },
      {
        "os": "darwin",
        "cpu": "arm64",
        "name": "dbx-model-proxy-darwin-arm64.tar.gz"
      },
      {
        "os": "win32",
        "cpu": "x64",
        "name": "dbx-model-proxy-win32-x64-msvc.zip"
      },
      {
        "os": "win32",
        "cpu": "arm64",
        "name": "dbx-model-proxy-win32-arm64-msvc.zip"
      }
    ]
  },
  {
    "command": "model-proxy-tray",
    "description": "Native tray controls for the dbx-model-proxy service",
    "binaryName": "dbx-model-proxy-tray",
    "hidden": true,
    "unit": "rs-model-proxy",
    "component": "rs-model-proxy",
    "version": "0.9.21",
    "tagPrefix": "v",
    "tag": "v0.9.21",
    "repository": "https://github.com/reggie-db/dbx-tools",
    "crateName": "dbx-tools-model-proxy",
    "cargoFeatures": [
      "tray"
    ],
    "assets": [
      {
        "os": "linux",
        "cpu": "x64",
        "name": "dbx-model-proxy-tray-linux-x64-gnu.tar.gz"
      },
      {
        "os": "linux",
        "cpu": "arm64",
        "name": "dbx-model-proxy-tray-linux-arm64-gnu.tar.gz"
      },
      {
        "os": "darwin",
        "cpu": "x64",
        "name": "dbx-model-proxy-tray-darwin-x64.tar.gz"
      },
      {
        "os": "darwin",
        "cpu": "arm64",
        "name": "dbx-model-proxy-tray-darwin-arm64.tar.gz"
      },
      {
        "os": "win32",
        "cpu": "x64",
        "name": "dbx-model-proxy-tray-win32-x64-msvc.zip"
      },
      {
        "os": "win32",
        "cpu": "arm64",
        "name": "dbx-model-proxy-tray-win32-arm64-msvc.zip"
      }
    ]
  }
] as const;