// GENERATED by UniFFI binding generation - DO NOT EDIT.
// Regenerated from the dbx-tools-auth Rust exports.
// Hand edits are overwritten on the next watch; this file is read-only.

/* eslint-disable */
// @ts-nocheck
export * from './_bindings.ts';
import uniffiModule from './_bindings.ts';
uniffiModule.initialize();
export { uniffiModule };
export async function uniffiInitAsync() {}
export type { ProviderAuthLike, StorageAdapter, StorageHandleLike } from './_bindings.ts';
