from __future__ import annotations

import asyncio
import base64
import datetime as dt
import json
import math
import re
from collections.abc import AsyncIterator, Callable, Mapping, Sequence
from contextlib import asynccontextmanager
from dataclasses import dataclass
from decimal import Decimal
from enum import Enum
from typing import Any, Protocol
from uuid import UUID

from graphiti_core.driver.driver import GraphDriver, GraphDriverSession
from graphiti_core.driver.query_executor import Transaction
from graphiti_core.utils.maintenance.graph_data_operations import clear_data
from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncEngine

"""Durable write journaling for ephemeral Graphiti graph drivers."""

_TAG = "__graphiti_type__"
_TABLE_COMPONENT = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")
_WRITE_KEYWORD = re.compile(r"\b(?:CREATE|DELETE|DETACH|MERGE|REMOVE|SET)\b", re.IGNORECASE)

WritePredicate = Callable[[str, Mapping[str, Any]], bool]


@dataclass(frozen=True, slots=True)
class GraphWrite:
    """One replayable Graphiti driver mutation."""

    query: str
    parameters: Mapping[str, Any]
    sequence: int | None = None


class WriteStorageDriver(Protocol):
    """Durable ordered storage used by `DelegatingGraphDriver`."""

    async def setup(self) -> None: ...

    async def append(self, writes: Sequence[GraphWrite]) -> None: ...

    async def load(self) -> list[GraphWrite]: ...

    async def close(self) -> None: ...


class PostgresWriteStorage:
    """Store replayable Graphiti mutations in an append-only Postgres journal."""

    def __init__(
        self,
        engine: AsyncEngine,
        *,
        namespace: str = "default",
        table: str = "graphiti_write_journal",
        close_engine: bool = False,
    ) -> None:
        if not namespace:
            raise ValueError("namespace must not be empty")
        self._engine = engine
        self._namespace = namespace
        self._table = _quote_table(table)
        self._index = _quote_identifier(f"{table.rsplit('.', 1)[-1]}_namespace_sequence_idx")
        self._close_engine = close_engine

    async def setup(self) -> None:
        """Create the journal table and replay index when absent."""
        async with self._engine.begin() as connection:
            await connection.execute(
                text(
                    f"""
                    CREATE TABLE IF NOT EXISTS {self._table} (
                        sequence BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        namespace TEXT NOT NULL,
                        query TEXT NOT NULL,
                        parameters JSONB NOT NULL,
                        recorded_at TIMESTAMPTZ NOT NULL DEFAULT now()
                    )
                    """
                )
            )
            await connection.execute(
                text(
                    f"""
                    CREATE INDEX IF NOT EXISTS {self._index}
                    ON {self._table} (namespace, sequence)
                    """
                )
            )

    async def append(self, writes: Sequence[GraphWrite]) -> None:
        """Append a committed mutation batch in one Postgres transaction."""
        if not writes:
            return
        values = [
            {
                "namespace": self._namespace,
                "query": write.query,
                "parameters": json.dumps(_encode_value(dict(write.parameters))),
            }
            for write in writes
        ]
        async with self._engine.begin() as connection:
            await connection.execute(
                text(
                    f"""
                    INSERT INTO {self._table} (namespace, query, parameters)
                    VALUES (:namespace, :query, CAST(:parameters AS JSONB))
                    """
                ),
                values,
            )

    async def load(self) -> list[GraphWrite]:
        """Load this namespace's mutations in commit order."""
        async with self._engine.connect() as connection:
            result = await connection.execute(
                text(
                    f"""
                    SELECT sequence, query, parameters
                    FROM {self._table}
                    WHERE namespace = :namespace
                    ORDER BY sequence
                    """
                ),
                {"namespace": self._namespace},
            )
            rows = result.mappings().all()
        return [
            GraphWrite(
                sequence=int(row["sequence"]),
                query=str(row["query"]),
                parameters=_decode_parameters(row["parameters"]),
            )
            for row in rows
        ]

    async def close(self) -> None:
        """Dispose the engine when this storage instance owns it."""
        if self._close_engine:
            await self._engine.dispose()


class DelegatingGraphDriver(GraphDriver):
    """Delegate Graphiti behavior while durably journaling graph mutations."""

    def __init__(
        self,
        delegate: GraphDriver,
        storage: WriteStorageDriver,
        *,
        write_predicate: WritePredicate | None = None,
        close_storage: bool = True,
    ) -> None:
        super().__init__()
        self._delegate = delegate
        self._storage = storage
        self._write_predicate = write_predicate or is_write_query
        self._close_storage = close_storage
        self._database = delegate._database
        self.provider = delegate.provider
        self.default_group_id = delegate.default_group_id
        self.search_interface = delegate.search_interface
        self.graph_operations_interface = delegate.graph_operations_interface
        self.aoss_client = getattr(delegate, "aoss_client", None)
        self._write_lock = asyncio.Lock()
        self._storage_ready = False
        self._hydrated = False

    @property
    def delegate(self) -> GraphDriver:
        """Return the live graph driver receiving delegated operations."""
        return self._delegate

    @property
    def entity_node_ops(self):
        return self._delegate.entity_node_ops

    @property
    def episode_node_ops(self):
        return self._delegate.episode_node_ops

    @property
    def community_node_ops(self):
        return self._delegate.community_node_ops

    @property
    def saga_node_ops(self):
        return self._delegate.saga_node_ops

    @property
    def entity_edge_ops(self):
        return self._delegate.entity_edge_ops

    @property
    def episodic_edge_ops(self):
        return self._delegate.episodic_edge_ops

    @property
    def community_edge_ops(self):
        return self._delegate.community_edge_ops

    @property
    def has_episode_edge_ops(self):
        return self._delegate.has_episode_edge_ops

    @property
    def next_episode_edge_ops(self):
        return self._delegate.next_episode_edge_ops

    @property
    def search_ops(self):
        return self._delegate.search_ops

    @property
    def graph_ops(self):
        return self._delegate.graph_ops

    async def execute_query(self, cypher_query_: str, **kwargs: Any) -> Any:
        """Journal a mutation before executing it through the delegate."""
        if not self._write_predicate(cypher_query_, kwargs):
            return await self._delegate.execute_query(cypher_query_, **kwargs)
        async with self._write_lock:
            await self._ensure_storage()
            await self._storage.append([GraphWrite(query=cypher_query_, parameters=dict(kwargs))])
            return await self._delegate.execute_query(cypher_query_, **kwargs)

    def session(self, database: str | None = None) -> GraphDriverSession:
        """Return a session that journals direct and transactional writes."""
        return _DelegatingSession(self._delegate.session(database), self)

    @asynccontextmanager
    async def transaction(self) -> AsyncIterator[Transaction]:
        """Journal a delegated transaction's mutations before commit."""
        writes: list[GraphWrite] = []
        async with self._write_lock:
            await self._ensure_storage()
            async with self._delegate.transaction() as transaction:
                yield _RecordingTransaction(transaction, writes, self._write_predicate)
                await self._storage.append(writes)

    async def close(self) -> None:
        """Close the delegate and the supplied storage driver."""
        try:
            await self._delegate.close()
        finally:
            if self._close_storage:
                await self._storage.close()

    def delete_all_indexes(self):
        """Delegate index deletion without recording schema maintenance."""
        return self._delegate.delete_all_indexes()

    async def build_indices_and_constraints(self, delete_existing: bool = False) -> None:
        """Build delegated indices and hydrate the graph once from Postgres."""
        async with self._write_lock:
            await self._ensure_storage()
            await self._delegate.build_indices_and_constraints(delete_existing)
            if self._hydrated:
                return
            writes = await self._storage.load()
            await clear_data(self._delegate)
            for write in writes:
                await self._delegate.execute_query(write.query, **dict(write.parameters))
            self._hydrated = True

    def with_database(self, database: str) -> DelegatingGraphDriver:
        """Return a wrapper over the delegate's selected database."""
        return self._copy_with_delegate(self._delegate.with_database(database))

    def clone(self, database: str) -> DelegatingGraphDriver:
        """Clone the delegated backend while retaining the journal."""
        return self._copy_with_delegate(self._delegate.clone(database))

    def build_fulltext_query(
        self,
        query: str,
        group_ids: list[str] | None = None,
        max_query_length: int = 128,
    ) -> str:
        """Build provider-specific full-text syntax through the delegate."""
        return self._delegate.build_fulltext_query(query, group_ids, max_query_length)

    def _copy_with_delegate(self, delegate: GraphDriver) -> DelegatingGraphDriver:
        """Wrap a selected delegate without transferring storage ownership."""
        return type(self)(
            delegate,
            self._storage,
            write_predicate=self._write_predicate,
            close_storage=False,
        )

    async def _ensure_storage(self) -> None:
        """Initialize the supplied storage driver once before journal access."""
        if not self._storage_ready:
            await self._storage.setup()
            self._storage_ready = True


class _DelegatingSession(GraphDriverSession):
    """Graphiti session adapter that records writes after delegated success."""

    def __init__(self, delegate: GraphDriverSession, driver: DelegatingGraphDriver) -> None:
        self._delegate = delegate
        self._driver = driver
        self.provider = driver.provider

    async def __aenter__(self):
        await self._delegate.__aenter__()
        return self

    async def __aexit__(self, exc_type, exc, tb):
        return await self._delegate.__aexit__(exc_type, exc, tb)

    async def run(self, query: str, **kwargs: Any) -> Any:
        if not self._driver._write_predicate(query, kwargs):
            return await self._delegate.run(query, **kwargs)
        async with self._driver._write_lock:
            await self._driver._ensure_storage()
            await self._driver._storage.append([GraphWrite(query=query, parameters=dict(kwargs))])
            return await self._delegate.run(query, **kwargs)

    async def close(self) -> None:
        await self._delegate.close()

    async def execute_write(self, func, *args, **kwargs):
        async def record_attempt(transaction, *callback_args, **callback_kwargs):
            """Journal each transaction attempt before the driver commits it."""
            attempt: list[GraphWrite] = []
            result = await func(
                _RecordingTransaction(
                    transaction,
                    attempt,
                    self._driver._write_predicate,
                ),
                *callback_args,
                **callback_kwargs,
            )
            await self._driver._storage.append(attempt)
            return result

        async with self._driver._write_lock:
            await self._driver._ensure_storage()
            result = await self._delegate.execute_write(record_attempt, *args, **kwargs)
            return result


class _RecordingTransaction(Transaction):
    """Transaction adapter that buffers successful writes until commit."""

    def __init__(
        self,
        delegate: Transaction,
        writes: list[GraphWrite],
        write_predicate: WritePredicate,
    ) -> None:
        self._delegate = delegate
        self._writes = writes
        self._write_predicate = write_predicate

    async def run(self, query: str, **kwargs: Any) -> Any:
        result = await self._delegate.run(query, **kwargs)
        if self._write_predicate(query, kwargs):
            self._writes.append(GraphWrite(query=query, parameters=dict(kwargs)))
        return result


def is_write_query(query: str, parameters: Mapping[str, Any] | None = None) -> bool:
    """Return whether a Cypher statement mutates graph data."""
    del parameters
    return _WRITE_KEYWORD.search(query) is not None


def _quote_table(value: str) -> str:
    """Validate and quote a possibly schema-qualified Postgres table."""
    components = value.split(".")
    if not components or any(not _TABLE_COMPONENT.fullmatch(component) for component in components):
        raise ValueError(f"Invalid Postgres table name: {value!r}")
    return ".".join(_quote_identifier(component) for component in components)


def _quote_identifier(value: str) -> str:
    """Validate and quote one Postgres identifier component."""
    if not _TABLE_COMPONENT.fullmatch(value):
        raise ValueError(f"Invalid Postgres identifier: {value!r}")
    if len(value.encode()) > 63:
        raise ValueError(f"Postgres identifier is longer than 63 bytes: {value!r}")
    return f'"{value}"'


def _encode_value(value: Any) -> Any:
    """Encode Graphiti query parameters into unambiguous JSON values."""
    if value is None or isinstance(value, (bool, int, str)):
        return value
    if isinstance(value, float):
        if not math.isfinite(value):
            raise TypeError("Graphiti journal values must contain only finite numbers")
        return value
    if isinstance(value, dt.datetime):
        return {_TAG: "datetime", "value": value.isoformat()}
    if isinstance(value, dt.date):
        return {_TAG: "date", "value": value.isoformat()}
    if isinstance(value, dt.time):
        return {_TAG: "time", "value": value.isoformat()}
    if isinstance(value, dt.timedelta):
        return {_TAG: "timedelta", "seconds": value.total_seconds()}
    if isinstance(value, Decimal):
        return {_TAG: "decimal", "value": str(value)}
    if isinstance(value, UUID):
        return {_TAG: "uuid", "value": str(value)}
    if isinstance(value, bytes):
        return {_TAG: "bytes", "value": base64.b64encode(value).decode("ascii")}
    if isinstance(value, Enum):
        return _encode_value(value.value)
    if isinstance(value, Mapping):
        encoded: dict[str, Any] = {}
        for key, item in value.items():
            if not isinstance(key, str):
                raise TypeError("Graphiti journal mapping keys must be strings")
            encoded[key] = _encode_value(item)
        return {_TAG: "mapping", "value": encoded} if _TAG in encoded else encoded
    if isinstance(value, (list, tuple)):
        return [_encode_value(item) for item in value]
    raise TypeError(f"Unsupported Graphiti journal value: {type(value).__name__}")


def _decode_value(value: Any) -> Any:
    """Decode tagged JSON values into Graphiti query parameter values."""
    if isinstance(value, list):
        return [_decode_value(item) for item in value]
    if not isinstance(value, dict):
        return value
    value_type = value.get(_TAG)
    if value_type == "datetime":
        return dt.datetime.fromisoformat(value["value"])
    if value_type == "date":
        return dt.date.fromisoformat(value["value"])
    if value_type == "time":
        return dt.time.fromisoformat(value["value"])
    if value_type == "timedelta":
        return dt.timedelta(seconds=value["seconds"])
    if value_type == "decimal":
        return Decimal(value["value"])
    if value_type == "uuid":
        return UUID(value["value"])
    if value_type == "bytes":
        return base64.b64decode(value["value"])
    if value_type == "mapping":
        return {key: _decode_value(item) for key, item in value["value"].items()}
    return {key: _decode_value(item) for key, item in value.items()}


def _decode_parameters(value: Any) -> Mapping[str, Any]:
    """Decode one persisted query-parameter mapping."""
    parsed = json.loads(value) if isinstance(value, str) else value
    decoded = _decode_value(parsed)
    if not isinstance(decoded, dict):
        raise TypeError("Graphiti journal parameters must decode to a mapping")
    return decoded
