# dbx-tools binding inputs sha256: b8e0abf8a8155d02b8cdb8d64518aa9b01f7994e6d48c24f46e36f4329914527
# dbx-tools binding content sha256: bdcb6a1439007f4686973fb42853e1e6a34c2b91dcc6e6de491b6d2bb8aaf680
# GENERATED by projen/tasks/python-node-bindings.ts - DO NOT EDIT.
# Regenerated from @dbx-tools/shared-model#display configured by packages/py/graphiti/pyproject.toml.
# Hand edits are overwritten; this file is read-only.

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Protocol, TypedDict

from typing_extensions import NotRequired

from .._runtime import MISSING as _MISSING
from .._runtime import invoke_positioned as _invoke_positioned
from .._runtime import invoke_positioned_sync as _invoke_positioned_sync





def to_model_display_name(
    name: str,
    provided: str | None | object = _MISSING,
) -> str:
    arguments: list[tuple[int, Any]] = []
    arguments.append((0, name))
    if provided is not _MISSING:
        arguments.append((1, provided))
    return _invoke_positioned_sync("shared_model__display", "toModelDisplayName", arguments)


__all__ = [
    "to_model_display_name",
]
