# dbx-tools binding inputs sha256: f3ee5da7472a2a3b776146d78d20ad035a3c9de5d036805f4b582303627a2fce
# dbx-tools binding content sha256: 4ad1aade826d817f4ba199d3f2b72bf6cf26cd77f866442763f1a9f18be066ad
# GENERATED by projen/tasks/python-node-bindings.ts - DO NOT EDIT.
# Regenerated from @dbx-tools/shared-model#openaiChat configured by packages/py/graphiti/pyproject.toml.
# Hand edits are overwritten; this file is read-only.

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Protocol, TypedDict

from typing_extensions import NotRequired

from .._runtime import MISSING as _MISSING
from .._runtime import invoke_positioned as _invoke_positioned
from .._runtime import invoke_positioned_sync as _invoke_positioned_sync


@dataclass(kw_only=True)
class ChatContentToTextOptions:
    separator: str | None = field(
        default=None,
        metadata={"javascript_name": "separator"},
    )
    types: list[str] | None = field(
        default=None,
        metadata={"javascript_name": "types"},
    )




def chat_content_parts(
    content: Any,
) -> list[dict[str, Any]] | None:
    arguments: list[tuple[int, Any]] = []
    arguments.append((0, content))
    return _invoke_positioned_sync("shared_model__openai_chat", "chatContentParts", arguments)


def chat_content_to_text(
    content: Any,
    options: ChatContentToTextOptions | dict[str, Any] | None | object = _MISSING,
) -> str:
    arguments: list[tuple[int, Any]] = []
    arguments.append((0, content))
    if options is not _MISSING:
        arguments.append((1, options))
    return _invoke_positioned_sync("shared_model__openai_chat", "chatContentToText", arguments)


def strip_unsupported_chat_fields(
    body: dict[str, Any],
    extra: list[str] | object = _MISSING,
) -> list[str]:
    arguments: list[tuple[int, Any]] = []
    arguments.append((0, body))
    if extra is not _MISSING:
        arguments.append((1, extra))
    return _invoke_positioned_sync("shared_model__openai_chat", "stripUnsupportedChatFields", arguments)


__all__ = [
    "ChatContentToTextOptions",
    "chat_content_parts",
    "chat_content_to_text",
    "strip_unsupported_chat_fields",
]
