# GENERATED by projen synth (rs-packages) - DO NOT EDIT.
# Regenerated from rs-packages/shared/core/src/string-example.ts.
# Hand edits are overwritten; edit the Rosetta source instead.

from typing import Any


def trim_to_empty(value: Any) -> str:
    return value.strip() if isinstance(value, str) else ""


def trim_to_null(value: Any) -> str | None:
    return trim_to_empty(value) or None


def first_non_empty(*values: Any) -> str | None:
    for value in values:
        trimmed = trim_to_null(value)
        if trimmed:
            return trimmed
    return None


def capitalize(value: str) -> str:
    return value[:1].upper() + value[1:] if value else value
