// GENERATED by UniFFI binding generation - DO NOT EDIT.
// Regenerated from the dbx-tools-core Rust exports.
// Hand edits are overwritten on the next watch; this file is read-only.

/* eslint-disable */
// @ts-nocheck
// This file was autogenerated by some hot garbage in the `uniffi-bindgen-react-native` crate.
// Trust me, you don't want to mess with it!
import lib from "@ubjs/node";
const { UniffiNativeModule, FfiType, resolveLibPath } = lib;

import {
  type StructuralEquality as UniffiStructuralEquality,
  type UniffiForeignFuture as RuntimeUniffiForeignFuture,
  type UniffiRustCallStatus,
  type UniffiGcObject,
  type UniffiRustFutureContinuationCallback as RuntimeUniffiRustFutureContinuationCallback,
  type UniffiResult,
} from '@ubjs/core';

const DEFINITIONS = {
  symbols: {
    rustbuffer_alloc: "ffi_dbx_tools_core_rustbuffer_alloc",
    rustbuffer_free: "ffi_dbx_tools_core_rustbuffer_free",
    rustbuffer_from_bytes: "ffi_dbx_tools_core_rustbuffer_from_bytes",
  },
  functions: {
    "ffi_dbx_tools_core_rust_future_poll_u8": {
      args: [FfiType.Handle, FfiType.Callback("RustFutureContinuationCallback"), FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_dbx_tools_core_rust_future_cancel_u8": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_dbx_tools_core_rust_future_complete_u8": {
      args: [FfiType.Handle],
      ret: FfiType.UInt8,
      hasRustCallStatus: true,
    },
    "ffi_dbx_tools_core_rust_future_free_u8": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_dbx_tools_core_rust_future_poll_i8": {
      args: [FfiType.Handle, FfiType.Callback("RustFutureContinuationCallback"), FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_dbx_tools_core_rust_future_cancel_i8": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_dbx_tools_core_rust_future_complete_i8": {
      args: [FfiType.Handle],
      ret: FfiType.Int8,
      hasRustCallStatus: true,
    },
    "ffi_dbx_tools_core_rust_future_free_i8": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_dbx_tools_core_rust_future_poll_u16": {
      args: [FfiType.Handle, FfiType.Callback("RustFutureContinuationCallback"), FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_dbx_tools_core_rust_future_cancel_u16": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_dbx_tools_core_rust_future_complete_u16": {
      args: [FfiType.Handle],
      ret: FfiType.UInt16,
      hasRustCallStatus: true,
    },
    "ffi_dbx_tools_core_rust_future_free_u16": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_dbx_tools_core_rust_future_poll_i16": {
      args: [FfiType.Handle, FfiType.Callback("RustFutureContinuationCallback"), FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_dbx_tools_core_rust_future_cancel_i16": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_dbx_tools_core_rust_future_complete_i16": {
      args: [FfiType.Handle],
      ret: FfiType.Int16,
      hasRustCallStatus: true,
    },
    "ffi_dbx_tools_core_rust_future_free_i16": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_dbx_tools_core_rust_future_poll_u32": {
      args: [FfiType.Handle, FfiType.Callback("RustFutureContinuationCallback"), FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_dbx_tools_core_rust_future_cancel_u32": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_dbx_tools_core_rust_future_complete_u32": {
      args: [FfiType.Handle],
      ret: FfiType.UInt32,
      hasRustCallStatus: true,
    },
    "ffi_dbx_tools_core_rust_future_free_u32": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_dbx_tools_core_rust_future_poll_i32": {
      args: [FfiType.Handle, FfiType.Callback("RustFutureContinuationCallback"), FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_dbx_tools_core_rust_future_cancel_i32": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_dbx_tools_core_rust_future_complete_i32": {
      args: [FfiType.Handle],
      ret: FfiType.Int32,
      hasRustCallStatus: true,
    },
    "ffi_dbx_tools_core_rust_future_free_i32": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_dbx_tools_core_rust_future_poll_u64": {
      args: [FfiType.Handle, FfiType.Callback("RustFutureContinuationCallback"), FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_dbx_tools_core_rust_future_cancel_u64": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_dbx_tools_core_rust_future_complete_u64": {
      args: [FfiType.Handle],
      ret: FfiType.Handle,
      hasRustCallStatus: true,
    },
    "ffi_dbx_tools_core_rust_future_free_u64": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_dbx_tools_core_rust_future_poll_i64": {
      args: [FfiType.Handle, FfiType.Callback("RustFutureContinuationCallback"), FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_dbx_tools_core_rust_future_cancel_i64": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_dbx_tools_core_rust_future_complete_i64": {
      args: [FfiType.Handle],
      ret: FfiType.Int64,
      hasRustCallStatus: true,
    },
    "ffi_dbx_tools_core_rust_future_free_i64": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_dbx_tools_core_rust_future_poll_f32": {
      args: [FfiType.Handle, FfiType.Callback("RustFutureContinuationCallback"), FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_dbx_tools_core_rust_future_cancel_f32": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_dbx_tools_core_rust_future_complete_f32": {
      args: [FfiType.Handle],
      ret: FfiType.Float32,
      hasRustCallStatus: true,
    },
    "ffi_dbx_tools_core_rust_future_free_f32": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_dbx_tools_core_rust_future_poll_f64": {
      args: [FfiType.Handle, FfiType.Callback("RustFutureContinuationCallback"), FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_dbx_tools_core_rust_future_cancel_f64": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_dbx_tools_core_rust_future_complete_f64": {
      args: [FfiType.Handle],
      ret: FfiType.Float64,
      hasRustCallStatus: true,
    },
    "ffi_dbx_tools_core_rust_future_free_f64": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_dbx_tools_core_rust_future_poll_rust_buffer": {
      args: [FfiType.Handle, FfiType.Callback("RustFutureContinuationCallback"), FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_dbx_tools_core_rust_future_cancel_rust_buffer": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_dbx_tools_core_rust_future_complete_rust_buffer": {
      args: [FfiType.Handle],
      ret: FfiType.RustBuffer,
      hasRustCallStatus: true,
    },
    "ffi_dbx_tools_core_rust_future_free_rust_buffer": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_dbx_tools_core_rust_future_poll_void": {
      args: [FfiType.Handle, FfiType.Callback("RustFutureContinuationCallback"), FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_dbx_tools_core_rust_future_cancel_void": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_dbx_tools_core_rust_future_complete_void": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: true,
    },
    "ffi_dbx_tools_core_rust_future_free_void": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "uniffi_dbx_tools_core_fn_clone_persistentauth": {
      args: [FfiType.Handle],
      ret: FfiType.Handle,
      hasRustCallStatus: true,
    },
    "uniffi_dbx_tools_core_fn_free_persistentauth": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: true,
    },
    "uniffi_dbx_tools_core_fn_clone_providerauth": {
      args: [FfiType.Handle],
      ret: FfiType.Handle,
      hasRustCallStatus: true,
    },
    "uniffi_dbx_tools_core_fn_free_providerauth": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: true,
    },
    "uniffi_dbx_tools_core_fn_clone_storageadapter": {
      args: [FfiType.Handle],
      ret: FfiType.Handle,
      hasRustCallStatus: true,
    },
    "uniffi_dbx_tools_core_fn_free_storageadapter": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: true,
    },
    "uniffi_dbx_tools_core_fn_clone_storagehandle": {
      args: [FfiType.Handle],
      ret: FfiType.Handle,
      hasRustCallStatus: true,
    },
    "uniffi_dbx_tools_core_fn_free_storagehandle": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: true,
    },
    "uniffi_dbx_tools_core_fn_init_callback_vtable_storageadapter": {
      args: [FfiType.Reference(FfiType.Struct("VTableCallbackInterfaceDbxToolsCoreStorageAdapter"))],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "uniffi_dbx_tools_core_fn_func_canonical_scopes": {
      args: [FfiType.RustBuffer],
      ret: FfiType.RustBuffer,
      hasRustCallStatus: true,
    },
    "uniffi_dbx_tools_core_fn_func_create_persistent_auth": {
      args: [FfiType.RustBuffer, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_dbx_tools_core_fn_func_create_persistent_auth_with_storage": {
      args: [FfiType.RustBuffer, FfiType.Handle],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_dbx_tools_core_fn_func_create_provider_auth": {
      args: [FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_dbx_tools_core_fn_func_create_provider_auth_with_storage": {
      args: [FfiType.RustBuffer, FfiType.Handle],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_dbx_tools_core_fn_func_create_storage_handle": {
      args: [FfiType.Handle],
      ret: FfiType.Handle,
      hasRustCallStatus: true,
    },
    "uniffi_dbx_tools_core_fn_func_credential_key": {
      args: [FfiType.RustBuffer, FfiType.RustBuffer, FfiType.RustBuffer],
      ret: FfiType.RustBuffer,
      hasRustCallStatus: true,
    },
    "uniffi_dbx_tools_core_fn_func_databricks_cli_available": {
      args: [],
      ret: FfiType.Int8,
      hasRustCallStatus: true,
    },
    "uniffi_dbx_tools_core_fn_func_is_databricks_app": {
      args: [],
      ret: FfiType.Int8,
      hasRustCallStatus: true,
    },
    "uniffi_dbx_tools_core_fn_func_parse_address": {
      args: [FfiType.RustBuffer],
      ret: FfiType.RustBuffer,
      hasRustCallStatus: true,
    },
    "uniffi_dbx_tools_core_fn_func_parse_resource_path": {
      args: [FfiType.RustBuffer],
      ret: FfiType.RustBuffer,
      hasRustCallStatus: true,
    },
    "uniffi_dbx_tools_core_fn_method_persistentauth_authorization_header_for_url": {
      args: [FfiType.Handle, FfiType.RustBuffer, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_dbx_tools_core_fn_method_persistentauth_challenge": {
      args: [FfiType.Handle],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_dbx_tools_core_fn_method_persistentauth_force_refresh_token": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_dbx_tools_core_fn_method_persistentauth_logout": {
      args: [FfiType.Handle],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_dbx_tools_core_fn_method_persistentauth_refresh_rejected_token": {
      args: [FfiType.Handle, FfiType.RustBuffer, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_dbx_tools_core_fn_method_persistentauth_status": {
      args: [FfiType.Handle],
      ret: FfiType.RustBuffer,
      hasRustCallStatus: true,
    },
    "uniffi_dbx_tools_core_fn_method_persistentauth_token": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_dbx_tools_core_fn_method_providerauth_force_refresh_token": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_dbx_tools_core_fn_method_providerauth_logout": {
      args: [FfiType.Handle],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_dbx_tools_core_fn_method_providerauth_refresh_rejected_token": {
      args: [FfiType.Handle, FfiType.RustBuffer, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_dbx_tools_core_fn_method_providerauth_token": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_dbx_tools_core_fn_method_storageadapter_load": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_dbx_tools_core_fn_method_storageadapter_prepare_write": {
      args: [FfiType.Handle],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_dbx_tools_core_fn_method_storageadapter_save": {
      args: [FfiType.Handle, FfiType.RustBuffer, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_dbx_tools_core_fn_method_storageadapter_remove": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_dbx_tools_core_fn_method_storageadapter_acquire_lock": {
      args: [FfiType.Handle, FfiType.RustBuffer, FfiType.UInt64],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_dbx_tools_core_fn_method_storageadapter_release_lock": {
      args: [FfiType.Handle, FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_dbx_tools_core_fn_method_storageadapter_name": {
      args: [FfiType.Handle],
      ret: FfiType.RustBuffer,
      hasRustCallStatus: true,
    },
    "ffi_dbx_tools_core_uniffi_contract_version": {
      args: [],
      ret: FfiType.UInt32,
      hasRustCallStatus: false,
    },
    "uniffi_dbx_tools_core_checksum_func_canonical_scopes": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_dbx_tools_core_checksum_func_create_persistent_auth": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_dbx_tools_core_checksum_func_create_persistent_auth_with_storage": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_dbx_tools_core_checksum_func_create_provider_auth": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_dbx_tools_core_checksum_func_create_provider_auth_with_storage": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_dbx_tools_core_checksum_func_create_storage_handle": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_dbx_tools_core_checksum_func_credential_key": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_dbx_tools_core_checksum_func_databricks_cli_available": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_dbx_tools_core_checksum_func_is_databricks_app": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_dbx_tools_core_checksum_func_parse_address": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_dbx_tools_core_checksum_func_parse_resource_path": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_dbx_tools_core_checksum_method_persistentauth_authorization_header_for_url": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_dbx_tools_core_checksum_method_persistentauth_challenge": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_dbx_tools_core_checksum_method_persistentauth_force_refresh_token": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_dbx_tools_core_checksum_method_persistentauth_logout": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_dbx_tools_core_checksum_method_persistentauth_refresh_rejected_token": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_dbx_tools_core_checksum_method_persistentauth_status": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_dbx_tools_core_checksum_method_persistentauth_token": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_dbx_tools_core_checksum_method_providerauth_force_refresh_token": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_dbx_tools_core_checksum_method_providerauth_logout": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_dbx_tools_core_checksum_method_providerauth_refresh_rejected_token": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_dbx_tools_core_checksum_method_providerauth_token": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_dbx_tools_core_checksum_method_storageadapter_load": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_dbx_tools_core_checksum_method_storageadapter_prepare_write": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_dbx_tools_core_checksum_method_storageadapter_save": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_dbx_tools_core_checksum_method_storageadapter_remove": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_dbx_tools_core_checksum_method_storageadapter_acquire_lock": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_dbx_tools_core_checksum_method_storageadapter_release_lock": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_dbx_tools_core_checksum_method_storageadapter_name": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
  },
  callbacks: {
    "RustFutureContinuationCallback": {
      args: [FfiType.Handle, FfiType.Int8],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ForeignFutureDroppedCallback": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ForeignFutureCompleterust_buffer": {
      args: [FfiType.Handle, FfiType.Struct("ForeignFutureResultRustBuffer")],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "CallbackInterfaceDbxToolsCoreStorageAdapterMethod0": {
      args: [FfiType.Handle, FfiType.RustBuffer, FfiType.Callback("ForeignFutureCompleterust_buffer"), FfiType.Handle],
      ret: FfiType.Struct("ForeignFutureDroppedCallbackStruct"),
      hasRustCallStatus: false,
      outReturn: true,
    },
    "ForeignFutureCompletevoid": {
      args: [FfiType.Handle, FfiType.Struct("ForeignFutureResultVoid")],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "CallbackInterfaceDbxToolsCoreStorageAdapterMethod1": {
      args: [FfiType.Handle, FfiType.Callback("ForeignFutureCompletevoid"), FfiType.Handle],
      ret: FfiType.Struct("ForeignFutureDroppedCallbackStruct"),
      hasRustCallStatus: false,
      outReturn: true,
    },
    "CallbackInterfaceDbxToolsCoreStorageAdapterMethod2": {
      args: [FfiType.Handle, FfiType.RustBuffer, FfiType.RustBuffer, FfiType.Callback("ForeignFutureCompletevoid"), FfiType.Handle],
      ret: FfiType.Struct("ForeignFutureDroppedCallbackStruct"),
      hasRustCallStatus: false,
      outReturn: true,
    },
    "CallbackInterfaceDbxToolsCoreStorageAdapterMethod3": {
      args: [FfiType.Handle, FfiType.RustBuffer, FfiType.Callback("ForeignFutureCompletevoid"), FfiType.Handle],
      ret: FfiType.Struct("ForeignFutureDroppedCallbackStruct"),
      hasRustCallStatus: false,
      outReturn: true,
    },
    "CallbackInterfaceDbxToolsCoreStorageAdapterMethod4": {
      args: [FfiType.Handle, FfiType.RustBuffer, FfiType.UInt64, FfiType.Callback("ForeignFutureCompleterust_buffer"), FfiType.Handle],
      ret: FfiType.Struct("ForeignFutureDroppedCallbackStruct"),
      hasRustCallStatus: false,
      outReturn: true,
    },
    "CallbackInterfaceDbxToolsCoreStorageAdapterMethod5": {
      args: [FfiType.Handle, FfiType.RustBuffer, FfiType.Callback("ForeignFutureCompletevoid"), FfiType.Handle],
      ret: FfiType.Struct("ForeignFutureDroppedCallbackStruct"),
      hasRustCallStatus: false,
      outReturn: true,
    },
    "CallbackInterfaceDbxToolsCoreStorageAdapterMethod6": {
      args: [FfiType.Handle],
      ret: FfiType.RustBuffer,
      hasRustCallStatus: true,
      outReturn: true,
    },
    "CallbackInterfaceCloneDbxToolsCore_StorageAdapter": {
      args: [FfiType.Handle],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "CallbackInterfaceFreeDbxToolsCore_StorageAdapter": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
  },
  structs: {
    "ForeignFutureDroppedCallbackStruct": [
      { name: "handle", type: FfiType.Handle },
      { name: "free", type: FfiType.Callback("ForeignFutureDroppedCallback") },
    ],
    "ForeignFutureResultRustBuffer": [
      { name: "return_value", type: FfiType.RustBuffer },
      { name: "call_status", type: FfiType.RustCallStatus },
    ],
    "ForeignFutureResultVoid": [
      { name: "call_status", type: FfiType.RustCallStatus },
    ],
    "VTableCallbackInterfaceDbxToolsCoreStorageAdapter": [
      { name: "uniffi_free", type: FfiType.Callback("CallbackInterfaceFreeDbxToolsCore_StorageAdapter") },
      { name: "uniffi_clone", type: FfiType.Callback("CallbackInterfaceCloneDbxToolsCore_StorageAdapter") },
      { name: "load", type: FfiType.Callback("CallbackInterfaceDbxToolsCoreStorageAdapterMethod0") },
      { name: "prepare_write", type: FfiType.Callback("CallbackInterfaceDbxToolsCoreStorageAdapterMethod1") },
      { name: "save", type: FfiType.Callback("CallbackInterfaceDbxToolsCoreStorageAdapterMethod2") },
      { name: "remove", type: FfiType.Callback("CallbackInterfaceDbxToolsCoreStorageAdapterMethod3") },
      { name: "acquire_lock", type: FfiType.Callback("CallbackInterfaceDbxToolsCoreStorageAdapterMethod4") },
      { name: "release_lock", type: FfiType.Callback("CallbackInterfaceDbxToolsCoreStorageAdapterMethod5") },
      { name: "name", type: FfiType.Callback("CallbackInterfaceDbxToolsCoreStorageAdapterMethod6") },
    ],
  },
} as const;

interface NativeModuleInterface {
    ffi_dbx_tools_core_rust_future_poll_u8(handle: bigint, callback: UniffiRustFutureContinuationCallback, callbackData: bigint): void;
    ffi_dbx_tools_core_rust_future_cancel_u8(handle: bigint): void;
    ffi_dbx_tools_core_rust_future_complete_u8(handle: bigint, uniffi_out_err: UniffiRustCallStatus): number;
    ffi_dbx_tools_core_rust_future_free_u8(handle: bigint): void;
    ffi_dbx_tools_core_rust_future_poll_i8(handle: bigint, callback: UniffiRustFutureContinuationCallback, callbackData: bigint): void;
    ffi_dbx_tools_core_rust_future_cancel_i8(handle: bigint): void;
    ffi_dbx_tools_core_rust_future_complete_i8(handle: bigint, uniffi_out_err: UniffiRustCallStatus): number;
    ffi_dbx_tools_core_rust_future_free_i8(handle: bigint): void;
    ffi_dbx_tools_core_rust_future_poll_u16(handle: bigint, callback: UniffiRustFutureContinuationCallback, callbackData: bigint): void;
    ffi_dbx_tools_core_rust_future_cancel_u16(handle: bigint): void;
    ffi_dbx_tools_core_rust_future_complete_u16(handle: bigint, uniffi_out_err: UniffiRustCallStatus): number;
    ffi_dbx_tools_core_rust_future_free_u16(handle: bigint): void;
    ffi_dbx_tools_core_rust_future_poll_i16(handle: bigint, callback: UniffiRustFutureContinuationCallback, callbackData: bigint): void;
    ffi_dbx_tools_core_rust_future_cancel_i16(handle: bigint): void;
    ffi_dbx_tools_core_rust_future_complete_i16(handle: bigint, uniffi_out_err: UniffiRustCallStatus): number;
    ffi_dbx_tools_core_rust_future_free_i16(handle: bigint): void;
    ffi_dbx_tools_core_rust_future_poll_u32(handle: bigint, callback: UniffiRustFutureContinuationCallback, callbackData: bigint): void;
    ffi_dbx_tools_core_rust_future_cancel_u32(handle: bigint): void;
    ffi_dbx_tools_core_rust_future_complete_u32(handle: bigint, uniffi_out_err: UniffiRustCallStatus): number;
    ffi_dbx_tools_core_rust_future_free_u32(handle: bigint): void;
    ffi_dbx_tools_core_rust_future_poll_i32(handle: bigint, callback: UniffiRustFutureContinuationCallback, callbackData: bigint): void;
    ffi_dbx_tools_core_rust_future_cancel_i32(handle: bigint): void;
    ffi_dbx_tools_core_rust_future_complete_i32(handle: bigint, uniffi_out_err: UniffiRustCallStatus): number;
    ffi_dbx_tools_core_rust_future_free_i32(handle: bigint): void;
    ffi_dbx_tools_core_rust_future_poll_u64(handle: bigint, callback: UniffiRustFutureContinuationCallback, callbackData: bigint): void;
    ffi_dbx_tools_core_rust_future_cancel_u64(handle: bigint): void;
    ffi_dbx_tools_core_rust_future_complete_u64(handle: bigint, uniffi_out_err: UniffiRustCallStatus): bigint;
    ffi_dbx_tools_core_rust_future_free_u64(handle: bigint): void;
    ffi_dbx_tools_core_rust_future_poll_i64(handle: bigint, callback: UniffiRustFutureContinuationCallback, callbackData: bigint): void;
    ffi_dbx_tools_core_rust_future_cancel_i64(handle: bigint): void;
    ffi_dbx_tools_core_rust_future_complete_i64(handle: bigint, uniffi_out_err: UniffiRustCallStatus): bigint;
    ffi_dbx_tools_core_rust_future_free_i64(handle: bigint): void;
    ffi_dbx_tools_core_rust_future_poll_f32(handle: bigint, callback: UniffiRustFutureContinuationCallback, callbackData: bigint): void;
    ffi_dbx_tools_core_rust_future_cancel_f32(handle: bigint): void;
    ffi_dbx_tools_core_rust_future_complete_f32(handle: bigint, uniffi_out_err: UniffiRustCallStatus): number;
    ffi_dbx_tools_core_rust_future_free_f32(handle: bigint): void;
    ffi_dbx_tools_core_rust_future_poll_f64(handle: bigint, callback: UniffiRustFutureContinuationCallback, callbackData: bigint): void;
    ffi_dbx_tools_core_rust_future_cancel_f64(handle: bigint): void;
    ffi_dbx_tools_core_rust_future_complete_f64(handle: bigint, uniffi_out_err: UniffiRustCallStatus): number;
    ffi_dbx_tools_core_rust_future_free_f64(handle: bigint): void;
    ffi_dbx_tools_core_rust_future_poll_rust_buffer(handle: bigint, callback: UniffiRustFutureContinuationCallback, callbackData: bigint): void;
    ffi_dbx_tools_core_rust_future_cancel_rust_buffer(handle: bigint): void;
    ffi_dbx_tools_core_rust_future_complete_rust_buffer(handle: bigint, uniffi_out_err: UniffiRustCallStatus): Uint8Array;
    ffi_dbx_tools_core_rust_future_free_rust_buffer(handle: bigint): void;
    ffi_dbx_tools_core_rust_future_poll_void(handle: bigint, callback: UniffiRustFutureContinuationCallback, callbackData: bigint): void;
    ffi_dbx_tools_core_rust_future_cancel_void(handle: bigint): void;
    ffi_dbx_tools_core_rust_future_complete_void(handle: bigint, uniffi_out_err: UniffiRustCallStatus): void;
    ffi_dbx_tools_core_rust_future_free_void(handle: bigint): void;
    uniffi_dbx_tools_core_fn_clone_persistentauth(ptr: bigint, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_dbx_tools_core_fn_free_persistentauth(ptr: bigint, uniffi_out_err: UniffiRustCallStatus): void;
    uniffi_dbx_tools_core_fn_clone_providerauth(ptr: bigint, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_dbx_tools_core_fn_free_providerauth(ptr: bigint, uniffi_out_err: UniffiRustCallStatus): void;
    uniffi_dbx_tools_core_fn_clone_storageadapter(ptr: bigint, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_dbx_tools_core_fn_free_storageadapter(ptr: bigint, uniffi_out_err: UniffiRustCallStatus): void;
    uniffi_dbx_tools_core_fn_clone_storagehandle(ptr: bigint, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_dbx_tools_core_fn_free_storagehandle(ptr: bigint, uniffi_out_err: UniffiRustCallStatus): void;
    uniffi_dbx_tools_core_fn_init_callback_vtable_storageadapter(vtable: UniffiVTableCallbackInterfaceDbxToolsCoreStorageAdapter): void;
    uniffi_dbx_tools_core_fn_func_canonical_scopes(scopes: Uint8Array, uniffi_out_err: UniffiRustCallStatus): Uint8Array;
    uniffi_dbx_tools_core_fn_func_create_persistent_auth(options: Uint8Array, storage: Uint8Array): bigint;
    uniffi_dbx_tools_core_fn_func_create_persistent_auth_with_storage(options: Uint8Array, storage: bigint): bigint;
    uniffi_dbx_tools_core_fn_func_create_provider_auth(options: Uint8Array): bigint;
    uniffi_dbx_tools_core_fn_func_create_provider_auth_with_storage(options: Uint8Array, storage: bigint): bigint;
    uniffi_dbx_tools_core_fn_func_create_storage_handle(storage: bigint, uniffi_out_err: UniffiRustCallStatus): bigint;
    uniffi_dbx_tools_core_fn_func_credential_key(provider: Uint8Array, profile: Uint8Array, scopes: Uint8Array, uniffi_out_err: UniffiRustCallStatus): Uint8Array;
    uniffi_dbx_tools_core_fn_func_databricks_cli_available(uniffi_out_err: UniffiRustCallStatus): number;
    uniffi_dbx_tools_core_fn_func_is_databricks_app(uniffi_out_err: UniffiRustCallStatus): number;
    uniffi_dbx_tools_core_fn_func_parse_address(input: Uint8Array, uniffi_out_err: UniffiRustCallStatus): Uint8Array;
    uniffi_dbx_tools_core_fn_func_parse_resource_path(input: Uint8Array, uniffi_out_err: UniffiRustCallStatus): Uint8Array;
    uniffi_dbx_tools_core_fn_method_persistentauth_authorization_header_for_url(uniffiSelf: bigint, requestUrl: Uint8Array, login: Uint8Array): bigint;
    uniffi_dbx_tools_core_fn_method_persistentauth_challenge(uniffiSelf: bigint): bigint;
    uniffi_dbx_tools_core_fn_method_persistentauth_force_refresh_token(uniffiSelf: bigint, login: Uint8Array): bigint;
    uniffi_dbx_tools_core_fn_method_persistentauth_logout(uniffiSelf: bigint): bigint;
    uniffi_dbx_tools_core_fn_method_persistentauth_refresh_rejected_token(uniffiSelf: bigint, staleAccessToken: Uint8Array, login: Uint8Array): bigint;
    uniffi_dbx_tools_core_fn_method_persistentauth_status(uniffiSelf: bigint, uniffi_out_err: UniffiRustCallStatus): Uint8Array;
    uniffi_dbx_tools_core_fn_method_persistentauth_token(uniffiSelf: bigint, login: Uint8Array): bigint;
    uniffi_dbx_tools_core_fn_method_providerauth_force_refresh_token(uniffiSelf: bigint, login: Uint8Array): bigint;
    uniffi_dbx_tools_core_fn_method_providerauth_logout(uniffiSelf: bigint): bigint;
    uniffi_dbx_tools_core_fn_method_providerauth_refresh_rejected_token(uniffiSelf: bigint, staleAccessToken: Uint8Array, login: Uint8Array): bigint;
    uniffi_dbx_tools_core_fn_method_providerauth_token(uniffiSelf: bigint, login: Uint8Array): bigint;
    uniffi_dbx_tools_core_fn_method_storageadapter_load(uniffiSelf: bigint, profile: Uint8Array): bigint;
    uniffi_dbx_tools_core_fn_method_storageadapter_prepare_write(uniffiSelf: bigint): bigint;
    uniffi_dbx_tools_core_fn_method_storageadapter_save(uniffiSelf: bigint, profile: Uint8Array, token: Uint8Array): bigint;
    uniffi_dbx_tools_core_fn_method_storageadapter_remove(uniffiSelf: bigint, profile: Uint8Array): bigint;
    uniffi_dbx_tools_core_fn_method_storageadapter_acquire_lock(uniffiSelf: bigint, profile: Uint8Array, timeoutMillis: bigint): bigint;
    uniffi_dbx_tools_core_fn_method_storageadapter_release_lock(uniffiSelf: bigint, lease: Uint8Array): bigint;
    uniffi_dbx_tools_core_fn_method_storageadapter_name(uniffiSelf: bigint, uniffi_out_err: UniffiRustCallStatus): Uint8Array;
    ffi_dbx_tools_core_uniffi_contract_version(): number;
    uniffi_dbx_tools_core_checksum_func_canonical_scopes(): number;
    uniffi_dbx_tools_core_checksum_func_create_persistent_auth(): number;
    uniffi_dbx_tools_core_checksum_func_create_persistent_auth_with_storage(): number;
    uniffi_dbx_tools_core_checksum_func_create_provider_auth(): number;
    uniffi_dbx_tools_core_checksum_func_create_provider_auth_with_storage(): number;
    uniffi_dbx_tools_core_checksum_func_create_storage_handle(): number;
    uniffi_dbx_tools_core_checksum_func_credential_key(): number;
    uniffi_dbx_tools_core_checksum_func_databricks_cli_available(): number;
    uniffi_dbx_tools_core_checksum_func_is_databricks_app(): number;
    uniffi_dbx_tools_core_checksum_func_parse_address(): number;
    uniffi_dbx_tools_core_checksum_func_parse_resource_path(): number;
    uniffi_dbx_tools_core_checksum_method_persistentauth_authorization_header_for_url(): number;
    uniffi_dbx_tools_core_checksum_method_persistentauth_challenge(): number;
    uniffi_dbx_tools_core_checksum_method_persistentauth_force_refresh_token(): number;
    uniffi_dbx_tools_core_checksum_method_persistentauth_logout(): number;
    uniffi_dbx_tools_core_checksum_method_persistentauth_refresh_rejected_token(): number;
    uniffi_dbx_tools_core_checksum_method_persistentauth_status(): number;
    uniffi_dbx_tools_core_checksum_method_persistentauth_token(): number;
    uniffi_dbx_tools_core_checksum_method_providerauth_force_refresh_token(): number;
    uniffi_dbx_tools_core_checksum_method_providerauth_logout(): number;
    uniffi_dbx_tools_core_checksum_method_providerauth_refresh_rejected_token(): number;
    uniffi_dbx_tools_core_checksum_method_providerauth_token(): number;
    uniffi_dbx_tools_core_checksum_method_storageadapter_load(): number;
    uniffi_dbx_tools_core_checksum_method_storageadapter_prepare_write(): number;
    uniffi_dbx_tools_core_checksum_method_storageadapter_save(): number;
    uniffi_dbx_tools_core_checksum_method_storageadapter_remove(): number;
    uniffi_dbx_tools_core_checksum_method_storageadapter_acquire_lock(): number;
    uniffi_dbx_tools_core_checksum_method_storageadapter_release_lock(): number;
    uniffi_dbx_tools_core_checksum_method_storageadapter_name(): number;
    // Codegen call sites use these via `nativeModule().rustbuffer_alloc(...)`
    // and `nativeModule().rustbuffer_free(...)`. The runtime's registered
    // module exposes them as method properties.
    rustbuffer_alloc(n: number): Uint8Array;
    rustbuffer_free(view: Uint8Array): void;
}
let _nativeModule: NativeModuleInterface | undefined;
const getter: () => NativeModuleInterface = () => {
  if (!_nativeModule) {
    const libPath = resolveLibPath({
      crateName: "dbx_tools_core",
      callerUrl: import.meta.url,
    });
    const mod_ = UniffiNativeModule.open(libPath);
    _nativeModule = mod_.register(DEFINITIONS) as unknown as NativeModuleInterface;
  }
  return _nativeModule;
};
export default getter;

// Structs and function types for calling back into Typescript from Rust.
export type UniffiRustFutureContinuationCallback = (data: bigint, pollResult: number) => void;
export type UniffiForeignFutureDroppedCallback = (handle: bigint) => void;
export type UniffiForeignFutureDroppedCallbackStruct = {
  handle: bigint;
  free: UniffiForeignFutureDroppedCallback;
};
export type UniffiForeignFutureResultRustBuffer = {
  return_value: Uint8Array;
  call_status: UniffiRustCallStatus;
};
export type UniffiForeignFutureCompleterustBuffer = (callbackData: bigint, result: UniffiForeignFutureResultRustBuffer) => void;
type UniffiCallbackInterfaceDbxToolsCoreStorageAdapterMethod0 = (uniffiHandle: bigint, profile: Uint8Array, uniffiFutureCallback: UniffiForeignFutureCompleterustBuffer, uniffiCallbackData: bigint) => UniffiForeignFutureDroppedCallbackStruct;
export type UniffiForeignFutureResultVoid = {
  call_status: UniffiRustCallStatus;
};
export type UniffiForeignFutureCompletevoid = (callbackData: bigint, result: UniffiForeignFutureResultVoid) => void;
type UniffiCallbackInterfaceDbxToolsCoreStorageAdapterMethod1 = (uniffiHandle: bigint, uniffiFutureCallback: UniffiForeignFutureCompletevoid, uniffiCallbackData: bigint) => UniffiForeignFutureDroppedCallbackStruct;
type UniffiCallbackInterfaceDbxToolsCoreStorageAdapterMethod2 = (uniffiHandle: bigint, profile: Uint8Array, token: Uint8Array, uniffiFutureCallback: UniffiForeignFutureCompletevoid, uniffiCallbackData: bigint) => UniffiForeignFutureDroppedCallbackStruct;
type UniffiCallbackInterfaceDbxToolsCoreStorageAdapterMethod3 = (uniffiHandle: bigint, profile: Uint8Array, uniffiFutureCallback: UniffiForeignFutureCompletevoid, uniffiCallbackData: bigint) => UniffiForeignFutureDroppedCallbackStruct;
type UniffiCallbackInterfaceDbxToolsCoreStorageAdapterMethod4 = (uniffiHandle: bigint, profile: Uint8Array, timeoutMillis: bigint, uniffiFutureCallback: UniffiForeignFutureCompleterustBuffer, uniffiCallbackData: bigint) => UniffiForeignFutureDroppedCallbackStruct;
type UniffiCallbackInterfaceDbxToolsCoreStorageAdapterMethod5 = (uniffiHandle: bigint, lease: Uint8Array, uniffiFutureCallback: UniffiForeignFutureCompletevoid, uniffiCallbackData: bigint) => UniffiForeignFutureDroppedCallbackStruct;
type UniffiCallbackInterfaceDbxToolsCoreStorageAdapterMethod6 = (uniffiHandle: bigint) => Uint8Array;
type UniffiCallbackInterfaceCloneDbxToolsCoreStorageAdapter = (handle: bigint) => UniffiResult<void>;
type UniffiCallbackInterfaceFreeDbxToolsCoreStorageAdapter = (handle: bigint) => void;
export type UniffiVTableCallbackInterfaceDbxToolsCoreStorageAdapter = {
  uniffi_free: UniffiCallbackInterfaceFreeDbxToolsCoreStorageAdapter;
  uniffi_clone: UniffiCallbackInterfaceCloneDbxToolsCoreStorageAdapter;
  load: UniffiCallbackInterfaceDbxToolsCoreStorageAdapterMethod0;
  prepare_write: UniffiCallbackInterfaceDbxToolsCoreStorageAdapterMethod1;
  save: UniffiCallbackInterfaceDbxToolsCoreStorageAdapterMethod2;
  remove: UniffiCallbackInterfaceDbxToolsCoreStorageAdapterMethod3;
  acquire_lock: UniffiCallbackInterfaceDbxToolsCoreStorageAdapterMethod4;
  release_lock: UniffiCallbackInterfaceDbxToolsCoreStorageAdapterMethod5;
  name: UniffiCallbackInterfaceDbxToolsCoreStorageAdapterMethod6;
};