# dbx-tools binding inputs sha256: b2d40d20ac19c6b234686e4e1b3ddcdbec13541ad2e231f50ae7a353bfc41203
# dbx-tools binding content sha256: 2f8c8da9ea3d88831b58d0c4741fc63f4d783ca09a7ed2f5f2d983a3dbe11f33
# GENERATED by projen/tasks/python-node-bindings.ts - DO NOT EDIT.
# Regenerated from @dbx-tools/shared-core#bindings configured by packages/py/graphiti/pyproject.toml.
# Hand edits are overwritten; this file is read-only.

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Protocol, TypedDict

from typing_extensions import NotRequired

from .._runtime import MISSING as _MISSING
from .._runtime import invoke_positioned as _invoke_positioned
from .._runtime import invoke_positioned_sync as _invoke_positioned_sync





def log_active_level() -> str:
    arguments: list[tuple[int, Any]] = []
    return _invoke_positioned_sync("shared_core__bindings", "logActiveLevel", arguments)


def log_level_enabled(
    level: str,
) -> bool:
    arguments: list[tuple[int, Any]] = []
    arguments.append((0, level))
    return _invoke_positioned_sync("shared_core__bindings", "logLevelEnabled", arguments)


__all__ = [
    "log_active_level",
    "log_level_enabled",
]
