// GENERATED by projen watch - DO NOT EDIT.
// Regenerated from the exporting modules in ./src.
// Hand edits are overwritten on the next watch; this file is read-only.

export const PACKAGE_IDENTIFIER = "@dbx-tools/teams";
export const PACKAGE_VERSION = "0.6.171";
export * as auth from "./src/auth.ts";
export * as builder from "./src/builder.ts";
export * as config from "./src/config.ts";
export * as connector from "./src/connector.ts";
export * as conversation from "./src/conversation.ts";
export * as defaults from "./src/defaults.ts";
export * as messaging from "./src/messaging.ts";
export * as plugin from "./src/plugin.ts";
export * as runtime from "./src/runtime.ts";
export * as tool from "./src/tool.ts";
export { BOT_OPENID_METADATA, resetTeamsAuth, verifyBotToken, connectorToken, isAllowedServiceUrl } from "./src/auth.ts";
export type { VerifiedBotToken, VerifyOptions } from "./src/auth.ts";
export { CARD_VERSION_ENV, WEBHOOK_URL_ENV, AGENT_PLUGIN_ENV, APP_ID_ENVS, APP_PASSWORD_ENVS, APP_TENANT_ENVS, ALLOW_UNAUTHENTICATED_ENV, DEFAULT_AGENT_PLUGIN, TEAMS_CONFIG_SCHEMA } from "./src/config.ts";
export type { TeamsPluginConfig, ResolvedTeamsConfig } from "./src/config.ts";
export { sendActivity, sendTyping } from "./src/connector.ts";
export type { ConnectorTarget } from "./src/connector.ts";
export { BOT_ACCOUNT, CARD_FORMAT_INSTRUCTIONS, CARD_ANSWER_INSTRUCTIONS, resolveCardAgent, resolveCardContextFactory, promptOf, toReplyActivity, documentCardSpec, rejectedCardSpec, runCardTurn } from "./src/conversation.ts";
export type { CardAgentLike, AgentResult, AgentProviderLike, CardTurnOptions, CardContextFactory } from "./src/conversation.ts";
export { BUILD_TIMEOUT_MS, POST_TIMEOUT_MS, POST_ATTEMPTS, TEAMS_BUILD_SETTINGS, TURN_TIMEOUT_MS, TEAMS_TURN_SETTINGS, TEAMS_POST_SETTINGS } from "./src/defaults.ts";
export type { TeamsExecuteConfig, TeamsExecutionSettings } from "./src/defaults.ts";
export { resolveServiceUrl, deliverTurn } from "./src/messaging.ts";
export type { BotCredentials, DeliverTurnOptions } from "./src/messaging.ts";
export { TeamsPlugin, teams } from "./src/plugin.ts";
export type { TeamsExecutor, TeamsRuntime } from "./src/runtime.ts";
export { CREATE_CARD_DESCRIPTION } from "./src/tool.ts";
export type { TeamsCardToolOptions } from "./src/tool.ts";
