// GENERATED by projen watch - DO NOT EDIT.
// Regenerated from the exporting modules in ./src.
// Hand edits are overwritten on the next watch; this file is read-only.

export const PACKAGE_IDENTIFIER = "@dbx-tools/test-polyglot";
export const PACKAGE_VERSION = "0.6.175";
export * as polygotTest from "./src/polygot-test.ts";
export * as pythonTest from "./src/python-test.ts";
export { Language } from "./src/polygot-test.ts";
export type { PolyglotTarget, ModuleReference, PolyglotOptions } from "./src/polygot-test.ts";
