// GENERATED by projen watch - DO NOT EDIT.
// Regenerated from the exporting modules in ./src.
// Hand edits are overwritten on the next watch; this file is read-only.

export const PACKAGE_IDENTIFIER = "@dbx-tools/openapi-model-proxy";
export const PACKAGE_VERSION = "0.9.23";
export * as client from "./src/client.ts";
export * as schema from "./src/schema.ts";
export type { paths, webhooks, components, $defs, operations } from "./src/schema.ts";
