// GENERATED by projen/tasks/python-node-bindings.ts - DO NOT EDIT.
// Regenerated from @dbx-tools/auth for PythonMonkey.
// Hand edits are overwritten on the next watch; this file is read-only.

var __defProp = Object.defineProperty;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __hasOwnProp = Object.prototype.hasOwnProperty;
function __accessProp(key) {
  return this[key];
}
var __toCommonJS = (from) => {
  var entry = (__moduleCache ??= new WeakMap).get(from), desc;
  if (entry)
    return entry;
  entry = __defProp({}, "__esModule", { value: true });
  if (from && typeof from === "object" || typeof from === "function") {
    for (var key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(entry, key))
        __defProp(entry, key, {
          get: __accessProp.bind(from, key),
          enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable
        });
  }
  __moduleCache.set(from, entry);
  return entry;
};
var __moduleCache;
var __returnValue = (v) => v;
function __exportSetter(name, newValue) {
  this[name] = __returnValue.bind(null, newValue);
}
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, {
      get: all[name],
      enumerable: true,
      configurable: true,
      set: __exportSetter.bind(all, name)
    });
};

// packages/js/node/auth/src/_python-bridge.ts
var exports__python_bridge = {};
__export(exports__python_bridge, {
  resolveDatabricksCliProfile: () => resolveDatabricksCliProfile,
  createAuthClient: () => createAuthClient
});
module.exports = __toCommonJS(exports__python_bridge);

// packages/js/node/auth/src/errors.ts
class AuthError extends Error {
  kind;
  constructor(kind, message, options) {
    super(message, options);
    this.kind = kind;
    this.name = "AuthError";
  }
}

// packages/js/node/auth/src/lifecycle.ts
class AuthClient {
  key;
  provider;
  store;
  options;
  now;
  constructor(key, provider, store, options, now = () => new Date) {
    this.key = key;
    this.provider = provider;
    this.store = store;
    this.options = options;
    this.now = now;
  }
  storeName() {
    return this.store.name();
  }
  async login() {
    return this.withLock(async () => {
      await this.store.prepareWrite();
      const token = validateToken(await this.provider.login(this.options.loginTimeoutSeconds * 1000));
      await this.store.save(this.key, token);
      return publicToken(token);
    });
  }
  token() {
    return this.loadToken(false);
  }
  tokenOrLogin() {
    return this.loadToken(true);
  }
  async tokenWithLogin(login) {
    if (login === true)
      return this.login();
    if (login === false)
      return this.token();
    return this.tokenOrLogin();
  }
  forceRefresh(login = true) {
    return this.refreshRejected(undefined, login);
  }
  refreshRejectedToken(staleAccessToken, login = true) {
    return this.refreshRejected(staleAccessToken, login);
  }
  async logout() {
    await this.withLock(() => this.store.remove(this.key));
  }
  async loadToken(login) {
    const existing = await this.store.load(this.key);
    if (existing && this.canReuse(existing))
      return publicToken(existing);
    return this.withLock(async () => {
      const current = await this.store.load(this.key);
      if (current && this.canReuse(current))
        return publicToken(current);
      return this.renew(current, login);
    });
  }
  async refreshRejected(staleAccessToken, login) {
    return this.withLock(async () => {
      const current = await this.store.load(this.key);
      if (staleAccessToken && current?.accessToken && current.accessToken !== staleAccessToken && isValid(current, this.now())) {
        return publicToken(current);
      }
      return this.renew(current, login);
    });
  }
  async renew(current, login) {
    let token;
    if (current) {
      try {
        token = await this.provider.refresh(current);
      } catch (error) {
        if (!login)
          throw error;
        token = await this.provider.login(this.options.loginTimeoutSeconds * 1000);
      }
    } else if (this.provider.canAuthenticateSilently()) {
      try {
        token = await this.provider.authenticate(this.options.loginTimeoutSeconds * 1000);
      } catch (error) {
        if (!login)
          throw error;
        token = await this.provider.login(this.options.loginTimeoutSeconds * 1000);
      }
    } else if (login) {
      token = await this.provider.login(this.options.loginTimeoutSeconds * 1000);
    } else {
      throw new AuthError("oauth", "No stored credential is available and interactive login is disabled");
    }
    token = validateToken(token, current);
    await this.store.prepareWrite();
    await this.store.save(this.key, token);
    return publicToken(token);
  }
  canReuse(token) {
    if (!isValid(token, this.now()))
      return false;
    if (!token.expiry)
      return true;
    return Date.parse(token.expiry) - this.now().getTime() > this.options.refreshBufferSeconds * 1000;
  }
  async withLock(action) {
    const lease = await this.store.acquireLock(this.key, this.options.lockTimeoutSeconds * 1000);
    let failure;
    try {
      return await action();
    } catch (error) {
      failure = error;
      throw error;
    } finally {
      try {
        await this.store.releaseLock(lease);
      } catch (releaseError) {
        if (failure === undefined)
          throw releaseError;
      }
    }
  }
}
function publicToken(token) {
  return {
    accessToken: token.accessToken,
    tokenType: token.tokenType,
    ...token.expiry ? { expiry: token.expiry } : {},
    scopes: [...token.scopes]
  };
}
function validateToken(token, previous) {
  if (!token.accessToken.trim())
    throw new AuthError("oauth", "Token response did not contain an access token");
  return {
    accessToken: token.accessToken,
    tokenType: token.tokenType || "Bearer",
    refreshToken: token.refreshToken ?? previous?.refreshToken,
    expiry: token.expiry,
    scopes: token.scopes.length ? [...token.scopes] : [...previous?.scopes ?? []]
  };
}
function isValid(token, now) {
  return Boolean(token.accessToken) && (!token.expiry || Date.parse(token.expiry) > now.getTime());
}

// packages/js/node/auth/src/types.ts
var AUTH_DEFAULTS = {
  refreshBufferSeconds: 300,
  lockTimeoutSeconds: 30,
  loginTimeoutSeconds: 900
};
var AuthOptions = {
  create(options = {}) {
    return { ...AUTH_DEFAULTS, ...options };
  },
  defaults() {
    return Object.freeze({ ...AUTH_DEFAULTS });
  }
};
var AUTH_TYPE_APP_OBO = "app_obo";
var AUTH_TYPE_APP_SP = "app_sp";

// packages/js/node/auth/src/_profile-core.ts
var SETTINGS_SECTION = "__settings__";
function parseDatabricksConfig(source) {
  const config = new Map;
  let section;
  for (const rawLine of source.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith("#") || line.startsWith(";"))
      continue;
    const sectionMatch = /^\[([^\]]+)]$/.exec(line);
    if (sectionMatch) {
      const name = sectionMatch[1].trim();
      if (!name)
        throw new AuthError("config", "Databricks profile section must not be empty");
      section = config.get(name) ?? new Map;
      config.set(name, section);
      continue;
    }
    const delimiter = line.indexOf("=");
    if (delimiter < 0 || !section) {
      throw new AuthError("config", `Invalid Databricks configuration line: ${rawLine}`);
    }
    const key = line.slice(0, delimiter).trim().toLowerCase();
    const value = line.slice(delimiter + 1).trim();
    if (!key)
      throw new AuthError("config", `Invalid Databricks configuration key: ${rawLine}`);
    section.set(key, value);
  }
  return config;
}
function loadRawProfile(config, name) {
  const section = config?.get(name);
  return {
    host: section?.get("host"),
    accountId: section?.get("account_id"),
    workspaceId: section?.get("workspace_id"),
    clientId: section?.get("client_id"),
    clientSecret: section?.get("client_secret"),
    accessToken: section?.get("token"),
    groupId: section?.get("group_id"),
    scopes: section?.get("scopes"),
    authType: nonempty(section?.get("auth_type"))?.toLowerCase()
  };
}
function resolveProfileName(requested, explicit, config, preferUserToMachine) {
  let selected = requested;
  if (!selected)
    selected = nonempty(config?.get(SETTINGS_SECTION)?.get("default_profile"));
  if (!selected && config?.has("DEFAULT"))
    selected = "DEFAULT";
  if (!selected) {
    const profiles = [...config?.keys() ?? []].filter((name) => name !== SETTINGS_SECTION);
    if (profiles.length === 1)
      selected = profiles[0];
  }
  selected ??= "DEFAULT";
  if (selected === SETTINGS_SECTION)
    throw new AuthError("config", `${SETTINGS_SECTION} is reserved`);
  if (explicit || !preferUserToMachine || !config)
    return selected;
  const current = loadRawProfile(config, selected);
  if (!isM2mProfile(current) || !current.host)
    return selected;
  const matches = [...config.keys()].filter((name) => {
    if (name === selected || name === SETTINGS_SECTION)
      return false;
    const candidate = loadRawProfile(config, name);
    return candidate.authType === "databricks-cli" && sameTarget(current, candidate);
  });
  return matches.length === 1 ? matches[0] : selected;
}
function normalizeHost(value, profile = "DEFAULT") {
  const selected = nonempty(value);
  if (!selected)
    throw new AuthError("config", `Profile ${profile} has no host`);
  const withScheme = /^https?:\/\//i.test(selected) ? selected : `https://${selected}`;
  let url;
  try {
    url = new URL(withScheme);
  } catch (cause) {
    throw new AuthError("config", `Profile ${profile} has an invalid host`, { cause });
  }
  if (url.protocol !== "https:" && url.hostname !== "localhost" && url.hostname !== "127.0.0.1") {
    throw new AuthError("config", "Databricks host must use HTTPS");
  }
  return url.toString().replace(/\/$/, "");
}
function resolveAuthKind(authType, clientId, clientSecret, accessToken) {
  switch (authType) {
    case "databricks-cli":
    case "oauth-u2m":
      return "user-to-machine" /* UserToMachine */;
    case "oauth-m2m":
      if (!clientId || !clientSecret)
        throw new AuthError("config", "oauth-m2m requires client_id and client_secret");
      return "machine-to-machine" /* MachineToMachine */;
    case "pat":
      if (!accessToken)
        throw new AuthError("config", "pat requires token");
      return "personal-access-token" /* PersonalAccessToken */;
    case AUTH_TYPE_APP_OBO:
    case "app-obo":
      if (!accessToken)
        throw new AuthError("config", "app_obo requires the configured access token header");
      return "app-on-behalf-of" /* AppOnBehalfOf */;
    case AUTH_TYPE_APP_SP:
    case "app-sp":
      if (!clientId || !clientSecret)
        throw new AuthError("config", "app_sp requires client id and secret");
      return "app-service-principal" /* AppServicePrincipal */;
    case undefined:
      if (clientId && clientSecret)
        return "machine-to-machine" /* MachineToMachine */;
      if (clientSecret)
        throw new AuthError("config", "oauth-m2m client_secret requires client_id");
      return accessToken ? "personal-access-token" /* PersonalAccessToken */ : "user-to-machine" /* UserToMachine */;
    default:
      throw new AuthError("config", `Authentication type ${authType} is not supported`);
  }
}
function nonempty(value) {
  const selected = value?.trim();
  return selected ? selected : undefined;
}
function sameTarget(left, right) {
  try {
    if (normalizeHost(left.host) !== normalizeHost(right.host))
      return false;
  } catch {
    return false;
  }
  return (!left.accountId || left.accountId === right.accountId) && (!left.workspaceId || left.workspaceId === right.workspaceId);
}
function isM2mProfile(profile) {
  return profile.authType === "oauth-m2m" || !profile.authType && Boolean(profile.clientId && profile.clientSecret);
}

// packages/js/node/auth/src/_python-bridge.ts
function createAuthClient(key, provider, store, options = {}) {
  const client = new AuthClient(key, provider, store, AuthOptions.create(options));
  return {
    storeName: () => client.storeName(),
    login: () => client.login(),
    token: (login) => client.tokenWithLogin(login),
    forceRefresh: (login) => client.forceRefresh(login),
    refreshRejectedToken: (staleAccessToken, login) => client.refreshRejectedToken(staleAccessToken, login),
    logout: () => client.logout()
  };
}
function resolveDatabricksCliProfile(configSource, requested, preferUserToMachine = true) {
  const selected = requested?.trim() || undefined;
  const config = configSource.trim() ? parseDatabricksConfig(configSource) : undefined;
  const name = resolveProfileName(selected, Boolean(selected), config, preferUserToMachine);
  const profile = loadRawProfile(config, name);
  const authKind = resolveAuthKind(profile.authType, profile.clientId, profile.clientSecret, profile.accessToken);
  if (!["user-to-machine" /* UserToMachine */, "personal-access-token" /* PersonalAccessToken */].includes(authKind)) {
    throw new AuthError("config", `Profile ${name} cannot expose a bearer token through the Databricks CLI`);
  }
  return {
    name,
    authKind,
    ...profile.host ? { host: normalizeHost(profile.host, name) } : {},
    ...profile.workspaceId ? { workspaceId: profile.workspaceId } : {}
  };
}
