// GENERATED by projen watch - DO NOT EDIT.
// Regenerated from the exporting modules in ./src.
// Hand edits are overwritten on the next watch; this file is read-only.

export const PACKAGE_IDENTIFIER = "@dbx-tools/shared-fs";
export const PACKAGE_VERSION = "0.6.169";
export * as baseFS from "./src/base-fs.ts";
export * as fs from "./src/fs.ts";
export * as memoryFS from "./src/memory-fs.ts";
export * as posixPath from "./src/posix-path.ts";
export { FileSystemError, BaseFileSystem } from "./src/base-fs.ts";
export type { FileSystemRootSegment, FileSystemRootInput, FileSystemErrorCode, BaseFileSystemOptions } from "./src/base-fs.ts";
export type { FileContent, FileEntryType, FileEntry, FileStat, ReadFileOptions, WriteFileOptions, RemoveOptions, CopyOptions, MakeDirectoryOptions, ListOptions, FileSystem } from "./src/fs.ts";
export { MemoryFileSystem } from "./src/memory-fs.ts";
export type { MemoryFileSystemOptions } from "./src/memory-fs.ts";
export type { NormalizeResult } from "./src/posix-path.ts";
